### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#1000]
Alcuni gate in inglese dicono di raccogliere l'accetta, il dagger ecc dal tavolo, ma effettivamente sono per terra
Cambiare la scritta o mettere dei tavoli :)

**Comment by Darksuitjer** [comment]
nella stanza della forgia, iron e oro dice lo step 4) di doppiocliccare gli iron ore che stanno in ..... .... .. . . .

**Comment by morpheus8888** [comment]
facciamo prima a metterli sul tavolo @kentar91

**Comment by kentar91** [comment]
li ho messi da mappa
