### ISSUE TITLE
gump log out da letto

### ISSUE THREAD

**Issue by GiovGiorgio** [uomars/UOMars#1001]
il nuovo gump per il log out del letto non avvisa se il log out istant non va a buon fine. Con quello precedente appariva invece un messaggio di errore e non si veniva disconnessi

**Comment by giga487** [comment]
Se clicchi sul letto e sei attaccato non succede niente, se puoi sloggare ti fa sloggare.

C'è qualcosa che non sto considerando?

**Comment by GiovGiorgio** [comment]
se per esempio sono in heat of  battle (capita che non sia presente l'icona), oppure sono ad 1 tile di distanza dal letto ti disconnette, ma il pg non scompare

**Comment by giga487** [comment]
risolto
