### ISSUE TITLE
rewards x worker

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#1004]
![image](https://user-images.githubusercontent.com/83588629/153833579-31c114d1-9758-45bc-b926-e0bc8bac0582.png)

@morpheus8888 Ikea ha il tamer a 100 e 102 worker points disponibili.. si può pensare di usare anche questi per la conversione rewards?

**Comment by Ket4mina** [comment]
@morpheus8888 confermo che Kentar non sta dicendo bugie

**Comment by morpheus8888** [comment]
lol no non si può proprio perché il tamer è stato reso troppo facile da salire, non essendoci equivalenza non si può fare
