### ISSUE TITLE
caratteri speciali vietati ai player

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#1005]
con l'ultima quest abbiamo notato che i player, rinominando le sacchine, possono bypassare i controlli della quest
ti propongo di rendere impossibile rinominare una sacca usando i caratteri speciali come *, così ai prossimi libri quest/oggetti quest metto questo carattere e i player non buggano +

grazie

**Comment by gmocciaro** [comment]
non sapevo manco potevi rinominare le sacche, come si fa?

**Comment by kentar91** [comment]
Un click con il sinistro 
Rename
Inserisci testo 


Stesso discorso dei chest

**Comment by kentar91** [comment]
Un click con il sinistro 
Rename
Inserisci testo 


Stesso discorso dei chest

**Comment by gmocciaro** [comment]
fatto
