### ISSUE TITLE
chain lightning e current target

### ISSUE THREAD

**Issue by GiovGiorgio** [uomars/UOMars#1006]
Salve a tutti, vi segnalo che la magia chain lightning è utilizzabile in macro con "current target", invece non funziona con "last target". Dati i danni eccessivi sul singolo target, a mio avviso ciò la rende utilizzabile troppo facilmente (in alternativa al flamestrike) sul singolo bersaglio che è isolato perché scappa

**Comment by Ale1991** [comment]
fixato
