### ISSUE TITLE
reset name statichousechest

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#1010]
ho aggiunto il rename alle chest delle case fisse, ma mi hanno fatto notare che se si elimina un chest si resettano tutti i nomi, secondo te si può fare qualcosa?

**Comment by gmocciaro** [comment]
strano, lato codice non vedo nulla che possa causare questa cosa, appena posso testo e vedo

**Comment by daffy55** [comment]
anche se si aggiunge una nuova chest succede

**Comment by gmocciaro** [comment]
fixed
