### ISSUE TITLE
Travelbook in Jail

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#1011]
si puo' uscire dalla Jail col travelbook e si rimane invulnerabili (potendo comunque fare tutto)

**Comment by gmocciaro** [comment]
io avevo fatto le modifiche sul check del travel nella region, ma se non ricordo male lo avevo testato, ritestatelo per favore

**Comment by gmocciaro** [comment]
![image](https://user-images.githubusercontent.com/12816659/154804847-295301cf-9bd7-46fe-abad-6538c6833d16.png)
a me funziona e chiudo
