### ISSUE TITLE
medaglione e shared

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#1018]
![immagine](https://user-images.githubusercontent.com/17385984/154683169-00fd28fa-2f68-4ea3-9c5d-80a5529e800e.png)

il sistema lo rileva condiviso con lux e gli scende

**Comment by morpheus8888** [comment]
come possiamo verificare se la condivisione con lux è reale o è un bug?

**Comment by thepatriot87** [comment]
secondo me verificando anche a livello di client gli account loggati

**Comment by Ale1991** [comment]
rimosso il controllo sullo shared al talismano
