### ISSUE TITLE
[Bug ]la macro con "SelectNearest--->Hostile" tagetta le evocazioni amiche/alleate/in party

### ISSUE THREAD

**Issue by ilmastro79** [uomars/UOMars#102]

**Comment by giga487** [comment]
Molto interessante, domani vedo

**Comment by giga487** [comment]
Select Nearest, non targetta più i membri del party che il gioco ritiene ostili.
Ogni oggetto "mobile" viene però visto a se dal clientm, mentre lato server è conosciuto il genitore del "Mobile summonato", lato client no.

Quindi due possibilità:
1) STI CAZZI, va bene così ( molto a favore )
2) Dobbiamo far inviare dal server il parent di ogni mobile, se esiste, e a quel punto checkare se il genitore è ostile.

Se bene la 2 opzione è molto elegante, secondo me il lavoro non è veramente worth e quindi non lo farò.

**Comment by lyon1235** [comment]
Ciao a tutti su razor c’è la possibilità di targhetta i next humanoid enemy target … è così via per i blu, grigi e compagni di Gilda (Verdi). Non è possibile implementare la stessa cosa ??? 

Perché non vorrei che in mezzo ad un dung vai a tarrghettare mostri e player nemici …

**Comment by giga487** [comment]
> Ciao a tutti su razor c’è la possibilità di targhetta i next humanoid enemy target … è così via per i blu, grigi e compagni di Gilda (Verdi). Non è possibile implementare la stessa cosa ??? 
> 
> Perché non vorrei che in mezzo ad un dung vai a tarrghettare mostri e player nemici … 

Allora questa è una proposta da valutare, io posso fare il controllo sul target se umanoide o no.

**Comment by lyon1235** [comment]
Basta che apri un razor di un server qualunque vai su hotkeys-target-ti escono tutti i tipi di target che si possono prendere …

**Comment by giga487** [comment]
@lyon1235 bravissimo.
Fallo e scrivili qui

**Comment by giga487** [comment]
@lyon1235 mi hai fatto venire in mente che quando giocavo su Dreams, utilizzavamo un client esterno per targettare le persone.
Questo programmino, andava in combo con uno script di easy UO in cui tenevamo salvate i seriali dei nostri alleati.
QUESTO, era un target vero, però c'era un sistema di bonding quindi c'era un file con il seriale di ogni persona e dei suoi pet, così il last target skippava automaticamente le persone.

**Comment by giga487** [comment]
Ok,
ho effettuato una modifica sul Select Nearest Target, viene effettuata la possibilità di sceglere tra:
Player,
NotPlayer,
All

Effettivamente è stata una bella esperienza, lo trovato nel prossimo Client.

Viene aggiunto anche a target Next e target Previous appena posso.

**Comment by giga487** [comment]
@lyon1235

**Comment by lyon1235** [comment]
Ok ok può andare stasera ti metto uno screen dei target di razor così guardi come sono fatti li

**Comment by lyon1235** [comment]
Questa è la lista dei target possibili. 
le varie opzioni valgono per blu enemy grey ecc come da foto. 
![Uploading 4DE21507-D6A6-4024-8C76-33BE3266EB9A.png…]()

**Comment by giga487** [comment]
Da testare:

Select Nearest
Select Next
Select Previous 

funzionano e vanno testati, è possibile selezionare All/Player/NotPlayer per le categorie Hostile e Mobile.

Chiudo
