### ISSUE TITLE
tutorial worker e young

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#1020]
anche se  young non puo resettare il worker
@morpheus8888

**Comment by daffy55** [comment]
![image](https://user-images.githubusercontent.com/83860614/154800309-8723f58a-34f8-4af2-b5b0-464e12194735.png)

**Comment by thepatriot87** [comment]
![immagine](https://user-images.githubusercontent.com/17385984/154811406-d0ae0b9d-8489-48dc-9e9d-11abcb4e4248.png)

l'ho spostato alla fine del tutorial e tolto tag worker altrimenti non gli da il deed

**Comment by thepatriot87** [comment]
questo dice che fa .reset ma i punti non gli calano o mi sta perculando o é da controllare ps si potrebbero fare gli exppoints modificabili? ora sono read only @Ale1991 
![immagine](https://user-images.githubusercontent.com/17385984/154811945-47e6f12a-78e2-41d3-8f56-d248cd9de0ab.png)

**Comment by morpheus8888** [comment]
fixato
