### ISSUE TITLE
wall of stone location is blocked molto fuori dalla citta order

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#1021]
![immagine](https://user-images.githubusercontent.com/17385984/154812550-ab5f5419-bdc9-449f-af6d-f015676f813f.png)

voluto o bug?

**Comment by thepatriot87** [comment]
2114 1623

**Comment by morpheus8888** [comment]
non ho ben capito qual è il problema

**Comment by Ale1991** [comment]
![image](https://user-images.githubusercontent.com/21221719/155116821-f05d06e9-abcd-4c50-891f-2383b7cceb1e.png)
ho appena controllato ma va tutto liscio

**Comment by thepatriot87** [comment]
é buggato il mio pg
