### ISSUE TITLE
lord di fazione non può buttare fuori una gilda

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#1049]
gli order vogliono buttare fuori una gilda della loro fazione perchè attaccano la fazione anzichè il nemico.
andando in ranking hanno provato ad espellere carcass, lord di questa gilda, ma cliccavano carcass e cacciava una altro... poi cliccando su un altro player a caso ha kickato carcass... ma la gilda resta lo stesso in fazione

**Comment by Ale1991** [comment]
fatto, adesso quando il commander kicka fuori dalla fazione un capogilda, verranno kickati anche tutti i membri di quella gilda
