### ISSUE TITLE
[Scripting] PVM Ultima Online Scalable System.

### ISSUE THREAD

**Issue by andreadellacorte** [uomars/UOMars#11]

**Comment by giga487** [comment]
Per favore, sign Giga487, facci divertire col tuo pvm system.

**Comment by Ale1991** [comment]
@giga487 aggiornaci sullo stato di avanzamento di questo sistema. Valuta anche se aprire una discussion sull'argomento. Stiamo tirando le somme per capire cosa effettivamente manca per decidere una data per l'apertura

**Comment by giga487** [comment]
Il sistema è funzionante e replicabile ma va testato con tutte le sue particolarità.

Se vogliamo testare il sistema e non il dungeon possiamo mettere dei mob a caso e verificare.

Per finire il dungeon (arredare) ed i mob ci vorrà del tempo. Nella mia lista delle cose da fare è prioritario e vorrei finire per settembre.
