### ISSUE TITLE
[server] modifica grafica depositi

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#116]
Rilevare tutti gli id dei depositi, duplicarli e renderli calpestabili, in questo modo gli scripter possono modificarli lato codicd.
In questo modo si risolvono un sacco di problemi si bodyblock @daffy55 @Ale1991 @morpheus8888 e non dobbiamo trovare nuovi item
Penso sia da assegnare a jespo o il nuovo grafico

**Comment by morpheus8888** [comment]
@daffy55 ricordami come avevamo deciso?

**Comment by morpheus8888** [comment]
@kentar91 @daffy55 rinnovo richiesta di aggiornamenti

**Comment by Ale1991** [comment]
> concordo con @morpheus8888 , tanto deforestando il mondo si risolve di gran lunga il problema del bodyblock, ma PREGHEREI di cambiare le grafiche dei seguenti depositi:
> reagenti (cespuglio) @kentar91 avevi trovato un id di un cespuglio fico
> legna base (alberi marroni fanno cacare)
> reagenti (spider) cambierei il colore in 1154

reagenti (spider) colore cambiato in 2726

**Comment by morpheus8888** [comment]
chiudo, al massimo si riapre in base al bisogno
