### ISSUE TITLE
[server] il player odino dell'account floki ha un problema con la casa

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#125]
Il player ha una casa intestata ma dal props le variabili della casa sono tutte null, non sappiamo se è successo anche ad altri player

**Comment by gmocciaro** [comment]
è possibile sapere quale è la casa intestata? Ricordo inoltre che se la casa è di un altro pg all'interno dell'account, conta come OWNER ma la variabile del player è null perchè va a fare il check di tutto l'account

![image](https://user-images.githubusercontent.com/12816659/131798764-dd9f382b-9c71-47f3-8d2e-c827e9bfd07c.png)

Quindi anche se la casa non è direttamente sua (quindi ha le famose variabili a NULL) ma è di un pg all'interno del suo account, comunuque risulta owner

**Comment by morpheus8888** [comment]
spiego meglio il problema, sul travelbook.cs ho fatto un metodo che si chiama houselocation alla riga 520, questo metodo non mi restituisce la posizione della casa che mi serve per il travelbook, cosa sto sbagliando? @gmocciaro

**Comment by gmocciaro** [comment]
il problema è che tu fai il check direttamente sulla variabile di quel pg. In quella variabile la trovi solo se la casa è stata comprata da quel pg, tu devi fare il check sull'account che invece ha sempre l'informazione di tutte le case di tutti i pg, quindi (questo codice è quello che uso io per il check sulle case)

```
Account playerAccount = player.Account as Account;
if (playerAccount == null) return false;

if (playerAccount.StaticHouseCaos != null) {...}
```

quindi fai il check sulle 4 variabile delle case fisse, ma invece di farle sul PlayerMobile le fai sull'Account

**Comment by gmocciaro** [comment]
puoi vedere come faccio io per il check al file **StaticHouseSign.cs** riga 82

**Comment by gmocciaro** [comment]
questo per ora lo chiudo, se hai problemi o lo riapri o mi scrivi su telegram direttamente
