### ISSUE TITLE
MARKER IN GAME E .GO - FELUCCA

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#144]
in collaborazione con @daffy55 

OrderCity

IngressoNord 2084,1886,0
IngressoSud 2085,2099,0
banca 1990,1977,0
locanda	2074,1818,0
prison 2037,1881,0
workerpoint 2027,1958,0
mercato 1953,2113,4
porto 1855,1998,0
caveau 1955,1974,20
castle 1831,1832,10

ChaosCity

IngressoNord 4100,2065,0
IngressoSud 4098,2171,0
Banca 4166,2172,0
Locanda	4222,1929,0
Prison 4117,2119,-20
WorkerPoint 4182,2117,0
Mercato 4272,1899,0
Porto 4298,2336,0
Caveau 4293,2088,0
Castle 4425,2069,5

MurdererCity

IngressoSud 3465,842,0
IngressoEst 3737,680,2
Banca 	3619,808,35
Locanda	3669,830,30
Prison 3643,838,10
WorkerPoint 3663,745,10
Mercato 3136,713,5
Porto 3549,595,0
Caveau 3531,697,-30

Pryma

IngressoNord 3014,3519,0
Banca 	2961,3578,0
Locanda	3006,3669,0
Prison 2965,3544,0
WorkerPoint 2965,3620,0
Mercato 2725,3771,6
Porto 3013,3850,2
Caveau 2955,3725,0

**Comment by kentar91** [comment]
Fortezze 
Enigma 2816,3227,0
Dragon 3402,1112,0
Order Fort 2404,2134,0
Chaos Fort 3915,2429,0

**Comment by kentar91** [comment]
Mines
The Worker 3022,2537,0
Pryma Mine 3221,3334,0
PK Mine East 3701,1218,0
PK Mine Ovest 2703,1192,0
Chaos Mine 3736,2289,0
Order Mine 2528,1956,0

**Comment by kentar91** [comment]
Vulcano
Vulcano 3173,1822,0
Pryma Enter 3074,2136,0
Order Enter 2868,1784,6
Chaos Enter 3459,1615,0
Murderer Enter 3189,1489,6

**Comment by kentar91** [comment]
Ext Worker Points
Order Nord 2589,1398,0
Order Sud 2443,2287,0
Chaos Nord 3485,1419,0
Chaos Sud 3492,2309,0
Neutral 2852,2839,0

**Comment by kentar91** [comment]
Sites
Nord Order Beach 1961,1339,0
West Neutral Beach 2417,3232,0
East Neutral Beach 3629,3085,0
East PK Beach 4275,1229,0

**Comment by kentar91** [comment]
Bridges
LeWorker East Bridge 3338,2522,10      
LeWorker West Bridge 2575,2512,30      
Central Bridge 2733,2018,21      
Order North Bridge 2615,1353,16      
Meridian Bridge 2700,740,40      
    </parent>

**Comment by kentar91** [comment]
Logs

HeartWood
HeartWood Swamp East 4021,2657,0
HeartWood OrderSouth 2477,2591,0
HeartWood Order SwampSouth" x="2286" y="2707" z="0" />
HeartWood NeutralEast 3813,2890,0

FrostWood
FrostWoodMurdererEast 2720,1015,0
FrostWoodLeWorker  3180,2405,92
FrostWood MurdererSouth 4000,1110,0
FrostWood OrderNorth 2205,1053,0
FrostWood Murderer 3502,1120,0

BloodWood
BloodWood North 3010,2160,0
BloodWood South 2650,2455,0

Ash
Ash West 2294,1371,0
Ash River 2601,1498,0
Ash Lake 3815,1435,0

Oak
Oak East 3515,1725,0
Oak West 2745,1667,0

**Comment by kentar91** [comment]
StrongShrub
StrongShrub Vulcano NE 3500,1587,0
StrongShrub Vulcano SE 3550,2050,0
StrongShrub CentralBridge 2690,2135,0
StrongShrub NorthBridge 2605,1480,0

**Comment by kentar91** [comment]
SpiderRocks
SpiderRocks Vulcano N 3145,1465,0
SpiderRocks Vulcano SE 3440,2090,0
 SpiderRocks Murderer South 3433,973,0
 SpiderRocks Vulcano NW 2790,1600,0
 SpiderRocks Vulcano W 2830,1775,0
 SpiderRocks Vulcano S 3300,2175

**Comment by kentar91** [comment]
Sand
Murderer East 4215,1135,0
Neutral West 2395,3285,0
Neutral East 3525,3140,0
Neutral West 2395,3290,0
Order NW 1925,1415,0

**Comment by kentar91** [comment]
Cotton
Le Worker Cotton Depo 3085,2653,0
S-E Order Cotton Depo 2405,2387,0
N-O Order Cotton Depo 2306,1442,0
Ovest PK Cotton Depo 3023 1192,0
Est PK Cotton Depo 3545,1141,0
N-O Chaos Cotton Depo 3761,1497,0
S-E Chaos Cotton Depo 3541,2437,0

**Comment by kentar91** [comment]
Beach/Shells
Nord Order Beach 1961,1339,0
West Neutral Beach 2417,3232,0
East Neutral Beach 3629,3085,0
East PK Beach 4275,1229,0

**Comment by kentar91** [comment]
Fishing
Neutral Lake 3280,3100,0
Order River North 2677,1464,0
Murderer Bay 4229,1108,0
Order NW Bay 1951,1342,0
LeWorker North 2880,2213,0

**Comment by kentar91** [comment]
NormalHides
LeWorker West 2666,2620,0
Order East 2448,1940,0
Chaos West 3854,2154,0
Vulcano NNW 2950,1185,0

**Comment by kentar91** [comment]
NormalWood
Neutral NE 3515,3070,0
Neutral NW 2500,3035,0
Order SE 2500,2095,0
Murderer South 3300,1135,0
Chaos West 3745,2456,0
Order NE 2315,1505,0
North Bridge 2571,1235,0
Chaos NE 3875,1515,0

**Comment by kentar91** [comment]
Hides
Hides Murderer W  2810,1285,0  
Hides Order SE 2785,2215,0  
Hides LeWorker NE 3185,2335,0  
Hides LeWorker NW 2765,2250,0  
Hides Order NE 2265,1305,0  
Hides Murderer S 3345,1300,0

**Comment by kentar91** [comment]
DungeonSpotFelucca
Egypt 2882,3098,0      
The Farm 2159,1535,0      
Orchi Goblin 4023,1609,0
Spectral 2975,820,0

**Comment by kentar91** [comment]
@Ale1991 ti ho inviato i file per la mappa di felucca con tutti i marker

**Comment by daffy55** [comment]
portale uscita Haven 3647 2593 0 (trammel)

**Comment by giga487** [comment]
+ Camp 3122	1056	0	false
+ Pryma   3032 3526	0	false
+ Pryma   3000 3626	0	false
+ Fort Order   2435 2290	0	false
+ Lost Lands House   5726 3988	1	false
+ Camp   3136 2839	0	false
+ Worker PK   3721 1216	0	false
+ Worker Order   2518 1976	0	false
+ Chaos City   4152 2192	0	false
+ Pryma Merchant   2754 3693	0	false
+ Grey Bank   3061 3113	0	false
+ Camp  2398 660 0	false
+ Camp  2581 602 0	false
+ Near Order Fort   2327 2317	0	false
+ Worker Point Chaos   3751 2283	0	false
+ Orc Cove  2204 1262	0	false
+ Camp 2557 692	0	false
+ Worker Pigrizio 2543 1468	0	false
+ Pk Mine Ovest 2702 1172	0	false
+ Pk Worker 3478 1441	0	false
+ Pigrizio 3125 1248	0	false
+ Neutral Fish 3295 2998	0	false
+ Camp 2404 1061	0	false
+ Worker Neutral 2904 2823	0	false
+ Order 1998 1954	0	false
+ Worker Chaos 3433 2412	0	false
+ Worker 3063 2534	0	false
+ Camp 2445 592	0	false
+ Camp 3894 2214	0	false
+ Camp 3487 3370	0	false
+ Camp 2295 895	0	false
+ Camp 2522 769	0	false
+ Camp 2356 611	0	false
+ Camp 2349 705	0	false

**Comment by giga487** [comment]
+	SpiderRocks Grey Bank	3173	3012	0	false
