### ISSUE TITLE
Auto-Backup dei WAYPOINT

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#164]
vi chiedo di creare un autobackup dei waypoint, così come ideato per gli spawn
@gmocciaro @Ale1991 @morpheus8888

**Comment by gmocciaro** [comment]
non so nemmeno di che stai parlando, spiega meglio

**Comment by morpheus8888** [comment]
lo fa alessio

**Comment by Ale1991** [comment]
Chiudo. Nuove specifiche nel #329
