### ISSUE TITLE
modifiche grafiche mob(2)

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#179]
rimettere vecchio cushide
![image](https://user-images.githubusercontent.com/83588629/131197844-769e45a7-8229-45d3-b16f-8fe998e187b1.png)

**Comment by kentar91** [comment]
oppure trovare la statuetta nuova e convincere @gmocciaro a sistemare il .premium

**Comment by Fred1990007** [comment]
ho caricato io quello nuovo volendo posso rimettere il vecchio

**Comment by kentar91** [comment]
![image](https://user-images.githubusercontent.com/83588629/131220744-c2287c98-76c7-4e8c-9f7d-f2b25e871d18.png)

da modificare

**Comment by kentar91** [comment]
risolto
