### ISSUE TITLE
Aggiungere al guild gump la lista delle gilde

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#18]
sul guild gump, mettere una schermata con l'elenco delle gilde attuali, quantità di membri e lord e reclutatore (sarebbe il top la possibilità di mandargli un mex ma non è obbligatorio), e non so se c'è un modo di far vedere anche se sono attive o "morte". In questo modo il player, specialmente uno senza gruppi ha la possibilità di contattare + velocemente il lord/reclutatore di una gilda. E in ultimo, se la ritieni una buona idea, si potrebbe fare una sorta di mini bg ( non so se esiste già) della gilda, così che un player prima di contattare una gilda legge l'orientamento.

**Comment by gmocciaro** [comment]
credo di no

**Comment by morpheus8888** [comment]
@gmocciaro basterebbe la possibilità di ordinare per last member added o una roba easy, niente di complesso

**Comment by gmocciaro** [comment]
Fatto un sistema che tenendo conto delle ultime 24h, ranka le gilde su 3 livelli:

- **Not really active...** (pallino rosso) meno di 2 player hanno loggato nelle ultime 24h
- **There is activity in this guild** (pallino blu) da 2 a 4 giocatori hanno loggato nelle ultime 24h
- This guild is really active! (pallino verde) 5+ giocatori hanno loggato nelle ultime 24h

ovviamente il tempo e il numero è modificabile in base a quello che ci interessa

![image](https://user-images.githubusercontent.com/12816659/131565560-b9041e68-a264-45cf-bb9c-6dacedebb01d.png)

**Comment by gmocciaro** [comment]
per ora chiudo se ci sono modifiche le discutiamo
