### ISSUE TITLE
codice non raggiungibile

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#183]
![image](https://user-images.githubusercontent.com/49568239/131220736-2624cbf2-9d86-49e6-875b-fa8db74c1523.png)

si può commentare quel codice sotto il return? se no visual studio mi manda sempre il warning

**Comment by gmocciaro** [comment]
l'ha fatta @Ale1991 sta cosa ma suppongo di si

**Comment by morpheus8888** [comment]
@gmocciaro dalle differenze su git mi diceva che eri tu l'autore

**Comment by gmocciaro** [comment]
ah si mi sono confuso con il cambio pass che abbiamo fatto qualche mese fa del forum, questo invece è il comando .password che anzi dobbiamo totalmente levare perchè la password sarà modificabile solo dal forum e non dal gioco

**Comment by gmocciaro** [comment]
mi sono creato la issue, questo lo chiudo
https://github.com/uomars/UOMars/issues/194
