### ISSUE TITLE
Rescripting bilanciamento Caos

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#186]
Il metodo che avevo fatto io per bilanciare i caos si trova in faction.cs linea 1719

Note utili:
- il metodo si basa su un conteggio (mi sono reso conto che su playermobile hai già dei metodi per contare che non ho usato) integrato dei player e poi singolarmente trasforma i caos;
- il metodo non controlla assolutamente i bountyhunter quindi andrebbe modificato considerato anche quello.

**Comment by Ale1991** [comment]
Quando si verifica la condizione di inferiorità numerica dei blu rispetto ai rossi+grigi, i chaos (che probabilmente in precedenza erano tutti grigi) dovrebbero tornare blu. Per evitare che cio' avvenga istantaneamente verrà istanziato un timer che ritenterà la trasformazione dei chaos (da grigi a blu). Il cambiamento avrà luogo solo se TUTTI i chaos non sono attaccati da altri player.

**Comment by Ale1991** [comment]
finito
