### ISSUE TITLE
DungeonGate

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#189]
Ogni città deve avere un dungeonmoongate, piazzalo con lo spowner. Il punto sceglilo tu basta che sia top.

**Comment by kentar91** [comment]
Spawn pronto, chiedo agli @arredatori (@daffy55 @Fred1990007 ) di crearmi le aree nelle città.

**Comment by Fred1990007** [comment]
serve fare un piccolo build per il gate? decido io dove ?

**Comment by kentar91** [comment]
si esatto
scegli tu, hai sicuramente più occhio di me

**Comment by daffy55** [comment]
> serve fare un piccolo build per il gate? decido io dove ?

Fede, scrivi le coordinate che scegli, cosi' sappiamo tutti dove si trova
