### ISSUE TITLE
Mob Lockpicker DungeonSpot

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#195]
https://docs.google.com/spreadsheets/d/1-xXKUaAZZBgAYU-gO90fkhzfBbDqtVxUYjwGyZV645U/edit#gid=0

da completare quelli della palude

**Comment by morpheus8888** [comment]
quali sono quelli della palude in quel documento?

**Comment by kentar91** [comment]
![![Screenshot_20210902-201723_Gallery.jpg](https://user-images.githubusercontent.com/83588629/131896031-e8dead52-144c-47ce-b904-497d079d9219.jpg)

**Comment by morpheus8888** [comment]
lo sai che plague non significa palude? :D

**Comment by kentar91** [comment]
Si... Certo... Ma mi piaceva come nome 3 ambientazione ... verranno messi nella palude della seconda mappa, quindi puoi anche chiamarli Swamp... basta che me li fai, soprattutto il tangle che è il boss hahahahaha

**Comment by morpheus8888** [comment]
fatti
