### ISSUE TITLE
ShootingBar

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#196]
@giga487 Come dicevamo ieri, ti ricordo il problema della shoot bar.
Ogni fottuta volta che attacco qualcosa con l'arciere, mi appare sta cazzo di barra in mezzo allo schermo..
Sia che l'abbia spostata, sia che disabilitata, mi compare ad ogni log in!!!
So che puoi fare il miracolo!!! :D quindi conto su di te!

**Comment by gmocciaro** [comment]
partendo dal presupposto che non ho idea di che cazzo state parlando, ma più in generale:

tutti i gump in teoria (lato client) salvano la posizione finale del gump, quindi se un player lo sposta e poi si riapre, viene riaperto nell'ultima posizione dove il player lo ha spostato.

Il problema è che al logout questa informazione si resetta (è un informazione in ram non viene salvata fisicamente sul disco), magari lato client possiamo salvare un file json o quello che sia in modo da rendere permanenti le posizioni dei gump.

lato server possiamo decidere quale deve essere la posizione di default, magari possiamo metterla di default in un posto meno invasivo, se poi c'è un modo di disabilitare il gump e non sta funzionando magari è un bug del gump stesso

**Comment by giga487** [comment]
la shooting bar, esiste lato client? pensavo fosse un gump lato server.

posso indagare su cosa avviene in questi giorni e poi riscrivo cosa penso di fare.

**Comment by Darksuitjer** [comment]
> partendo dal presupposto che non ho idea di che cazzo state parlando, ma più in generale:
> 
> tutti i gump in teoria (lato client) salvano la posizione finale del gump, quindi se un player lo sposta e poi si riapre, viene riaperto nell'ultima posizione dove il player lo ha spostato.
> 
> Il problema è che al logout questa informazione si resetta (è un informazione in ram non viene salvata fisicamente sul disco), magari lato client possiamo salvare un file json o quello che sia in modo da rendere permanenti le posizioni dei gump.
> 
> lato server possiamo decidere quale deve essere la posizione di default, magari possiamo metterla di default in un posto meno invasivo, se poi c'è un modo di disabilitare il gump e non sta funzionando magari è un bug del gump stesso

**Comment by Darksuitjer** [comment]
> partendo dal presupposto che non ho idea di che cazzo state parlando, ma più in generale:
> 
> tutti i gump in teoria (lato client) salvano la posizione finale del gump, quindi se un player lo sposta e poi si riapre, viene riaperto nell'ultima posizione dove il player lo ha spostato.
> 
> Il problema è che al logout questa informazione si resetta (è un informazione in ram non viene salvata fisicamente sul disco), magari lato client possiamo salvare un file json o quello che sia in modo da rendere permanenti le posizioni dei gump.
> 
> lato server possiamo decidere quale deve essere la posizione di default, magari possiamo metterla di default in un posto meno invasivo, se poi c'è un modo di disabilitare il gump e non sta funzionando magari è un bug del gump stesso

Prova a mettere in mano un arco e attacca qualsiasi cosa, sto parlando della barra di caricamento (Delay della scoccata) che si apre in mezzo allo schermo

**Comment by giga487** [comment]
@kentar91 grazie, non so come hai fatto ma hai letto nel mio pensiero

**Comment by gmocciaro** [comment]
> la shooting bar, esiste lato client? pensavo fosse un gump lato server.
> 
> posso indagare su cosa avviene in questi giorni e poi riscrivo cosa penso di fare.

no, ovviamente il gump è lato server, io parlavo più generalmente di come funziona la gestione di tutti i gump, nel client viene renderizzato ad una certa X-Y decisa dal server, ma se un player la sposta, il client salva la nuova X-Y in una sorta di cache in modo che se quello stesso gump (immagino si basa sul nome della classe) viene riaperto, lo apre direttamente con le nuove coordinate

**Comment by giga487** [comment]
Si questo lo sapevo anche io, non pensavo che i Gump lato server venissero salvati sul file dove vengono salvate le posizioni dei Gump.

Non penso che avvenga per i Gump lato server, ma posso indagare

**Comment by gmocciaro** [comment]
> Si questo lo sapevo anche io, non pensavo che i Gump lato server venissero salvati sul file dove vengono salvate le posizioni dei Gump.
> 
> Non penso che avvenga per i Gump lato server, ma posso indagare

si, nel costruttore il BaseGump vuole la X e la Y della posizione nello schermo

**Comment by Ale1991** [comment]
allora: 
1) Un comando molto importante è .helpinfo che fa vedere tutti i comandi che potete lanciare in base al livello di privilegi che avete, soprattutto per i player è un must.
2) Per disattivare quelle barre e non farle comparire mai potete usare i comandi evidenziati di seguito:
![image](https://user-images.githubusercontent.com/21221719/131649262-da6f204c-5d7c-4f82-84dc-84996d0f7bbb.png)

Se volete riabilitarli esiste il comando opporto °Enable...°

**Comment by Darksuitjer** [comment]
> allora:
> 
> 1. Un comando molto importante è .helpinfo che fa vedere tutti i comandi che potete lanciare in base al livello di privilegi che avete, soprattutto per i player è un must.
> 2. Per disattivare quelle barre e non farle comparire mai potete usare i comandi evidenziati di seguito:
>    ![image](https://user-images.githubusercontent.com/21221719/131649262-da6f204c-5d7c-4f82-84dc-84996d0f7bbb.png)
> 
> Se volete riabilitarli esiste il comando opporto °Enable...°

non è la stessa cosa del .disableshootbar?  ora provo cliccando manualmente.. ma il comando esiste solo che ogni volta che loggo, anche se disabilitata, ricompare

**Comment by Darksuitjer** [comment]
forse ha gia fixato... si puo chiudere 👯

**Comment by kentar91** [comment]
ok boss, avevo sbagliato tasto sul cell

**Comment by morpheus8888** [comment]
allora ho appena controllato ed effettivamente non serializzo il disable della shooting bar, per fare in modo che non compaia più la devo serializzare. Per il resto la proposta di @gmocciaro  secondo me è fondamentale per risolvere altre problematiche collegate allo spostamento dei gump, io procederei in tal senso

**Comment by Ale1991** [comment]
> allora ho appena controllato ed effettivamente non serializzo il disable della shooting bar, per fare in modo che non compaia più la devo serializzare. Per il resto la proposta di @gmocciaro secondo me è fondamentale per risolvere altre problematiche collegate allo spostamento dei gump, io procederei in tal senso

ho serializzato già io, il fix è up

**Comment by morpheus8888** [comment]
ok, o chiudiamo questa e ne ripriamo una dedicata solo alla gestione dei gump o lasciamo direttamente aperta questa

**Comment by gmocciaro** [comment]
https://github.com/uomars/UOMars/issues/216
