### ISSUE TITLE
Tutorial & Altro

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#197]
Hola!!! ieri pomeriggio è passato a casa mia un amico per una birretta, intanto che aspettavamo un terzo per uscire a berne un'altra...
E' uno che non ha praticamente mai giocato ad uo, se non installato su qualche shard, provato a creare il pg, ma di base non ha mai giocato attivamente e di sicuro non ha mai capito niente (non che su altri giochi sia un fenomeno...)
Fatto sta che volevo fargli provare il tutorial per vedere se tutto andava bene, quindi gli ho creato un pg nuovo e portato al punto di partenza.
Al primo gate la reazione è stata: "che cazzo c'è scritto????" :\ purtroppo se riesce a capire una parola su una frase fatta in inglese è già troppo...

**Comment by morpheus8888** [comment]
proponi di fare il tutorial anche in italiano?

**Comment by Darksuitjer** [comment]
> proponi di fare il tutorial anche in italiano?

Decisamente si, per gente come il mio amico che non sa l'inglese. altrimenti sarebbe una domanda unica.
:cosa c'è scritto?
:come si fa?
:cosa vuol dire?
magari con l'italiano riuscirebbe a cavarsela da solo!

**Comment by giga487** [comment]
Questi gump sono lato server, il client non c'entra niente, sarebbe bello poter selezionare la lingua o addirittura fare tutti i gump con 2 pagine Ita/Eng.

grz
