### ISSUE TITLE
Skill cap 

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#198]
Buonasera
Ho riscontrato che con il nuovo gump dello skill cap si riescono ad aggiungere punti skill oltre i 700. Ieri provando sono arrivato a 780 su 700. Vi prego verificare @gmocciaro

**Comment by gmocciaro** [comment]
prendo in carico, appena posso lo guardo e sistemo

**Comment by gmocciaro** [comment]
fixato
