### ISSUE TITLE
Aggiornare  Avamposti

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#204]
Neutral - FATTO
Aggiungere:

- Banchiere
- Miniera
- Spawn Boss
- Worker Point
- Zona Reagenti
- Zona Cotone
- Zona Legna
- Zona Pelli
- Zona Pesci
- Zona Sabbia
- Chest per posare i materiali o altro
- Solo Uscite (dalle mura)

**Comment by gmocciaro** [comment]
il banchiere lo mettete voi? perchè era messo che spawnava lato codice in modo da poter gestire chi potesse usarlo (solo quelli che hanno conquistato).

Se poi la logica è cambiata non lo so

**Comment by daffy55** [comment]
Il bankiere perfetto come dici te, però ho cmq dovuto arredare, quindi ti darò io le coordinate, se per voi non è un problema

**Comment by daffy55** [comment]
Promemoria per me:

Campo Cotone Order
Campo cotone Caos
Banca Caos (arredamento)
Deforestare dagli statici l'interno di Pk, order e caos in base al numero spawn piazzati

**Comment by kentar91** [comment]
ho creato gli spawn di tutto, 3 quantità a tipo, bisogna verificare.

fatemi sapere

**Comment by kentar91** [comment]
ma anche l'avamposto trammel deve avere i respawn? se si me lo dovete allargare...

**Comment by daffy55** [comment]
penso di no, le lost son gia piene, la comodità di quell'avamposto sono gli strumenti di raffinazione e lavoro

**Comment by kentar91** [comment]
> penso di no, le lost son gia piene, la comodità di quell'avamposto sono gli strumenti di raffinazione e lavoro

ok

**Comment by kentar91** [comment]
c'è un problema 
gli avamposti su felucca sono 4. le risorse 5 qualità. che faccio? una la lascio fuori o ogni avamposto ha random tutte le risorse?
@morpheus8888

**Comment by morpheus8888** [comment]
tutti gli avamposti hanno tutte le risorse, lo dobbiamo bilanciare con le quantità

**Comment by daffy55** [comment]
Mi mancano solo da arredare i worker point all'interno degli Avamposti, per il resto sono pronti!

Coordinate BANKIERI:
order: 2355 2076 22
pk: 3410 1039 -30
caos: 3846 2408 26
neutral: 2677 3255 40

@morpheus8888

**Comment by morpheus8888** [comment]
@daffy55 coordinate chest?
