### ISSUE TITLE
mob bardabili in base al livello di difficoltà

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#206]
in base al livello cLevel del mob, al suo aumentare si incrementa anche la difficoltà nel bardarlo (inteso usare pacemaking, provocation etc).

quindi creare 5 livelli di difficoltà di "bardingdifficulty" che vanno pari passo al cLevel

non sò se ho reso l'idea..

**Comment by morpheus8888** [comment]
https://github.com/uomars/UOMars/discussions/151

Non serve, leggiti questo, per farlo più difficile per il bardo basta aumentare le rispettive resistenze
