### ISSUE TITLE
invertiti macro di lancio pozze con uso normale

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#207]
@morpheus8888 io e  Dark abbiamo constatato che in alcuni casi le macro .heal etc, che fanno bere le pozioni, si invertono con il lancio delle pozioni

esempio: bevo la prima heal con .heal, la seconda volta che uso .heal mi compare il targhet.

per ulteriori info chiedi a Dark

**Comment by morpheus8888** [comment]
dovrebbe essere fixato, provate
