### ISSUE TITLE
bug craft system

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#209]
Se sposto la schermata di craft mentre sto craftando se ne crea un altra che si sovrappone a quella già presente e così via
Fino alla fine del craft. Ad esempio io avevo messo a fare 100 pozze
![IMG_20210902_140818](https://user-images.githubusercontent.com/49568239/131841460-53f80d0e-0779-4754-8cc4-abf9cc04a6bd.jpg)

**Comment by morpheus8888** [comment]
Anche aprendo options finisce sempre in secondo piano rispetto alla schermata di craft appena parte un nuovo craft. Non so se mi sono spiegato bene. Volevo sistemare una macro ma non ho potuto farlo fino alla fine delle 100 pozzo perché ogni secondo partiva un nuovo craft

**Comment by gmocciaro** [comment]
possibilmente mi sono dimenticato di chiudere il gump sotto quando ne apro un nuovo, fixo in giornata

**Comment by Ket4mina** [comment]
Aggiungo che, sempre durante il craft di pozioni o in generale roba che si fa in 1sec, non è possibile scrivere credo a causa del continuo refresh del gump. Praticamente mentre crafto devo stare zitto.

**Comment by Ket4mina** [comment]
Forse senza refresh andrebbe bene lo stesso. Uno sceglie la quantità, fa partire il craft e via. Nel frattempo si fa una chiacchiera con il vicino di banco

**Comment by morpheus8888** [comment]
@gmocciaro  possiamo mettere che l'autorefresh è un opzione spuntabile dal player nel gump?

**Comment by gmocciaro** [comment]
Ho fatto svariati fix al crafting system, di preciso:

- Fixato il fatto che si aprivano tante finestre
- Aggiunta la possibilità di stoppare un crafting in corso
- Fixato il fatto che non potevi scrivere durante il craft

Piccolo video:


https://user-images.githubusercontent.com/12816659/131897959-baf5c08b-5134-4650-9eff-2d23645383e7.mp4
