### ISSUE TITLE
Problema .city

### ISSUE THREAD

**Issue by Ket4mina** [uomars/UOMars#210]
Faccio .city, TP-Points, Banker, Kal ort por, clicco ok sulla scherta di warning che si apre (di cui non ho capito la funzione) e crasha il server.

**Comment by gmocciaro** [comment]
ci guardo più tardi :ok_person:

**Comment by gmocciaro** [comment]
ho testato tutti i punti e non è crashato, magari era una cosa momentanea...

che città era?

comunque il gump ti avvisa che se ti recalli con oggetti recentemente craftati o recentemente lootati, te li fa cadere a terra perchè non puoi portarteli con te

**Comment by Ket4mina** [comment]
Si la storia del warning che appare l'ho capita dopo aver letto un po' le novità. Anche se devo capire come muovermi con le cose appena Craftate. Per il crash invece prima ho riprovato, sempre dentro Pryma ma con un altro pg e mi ha crashato lo stesso. Forse sono io

**Comment by gmocciaro** [comment]
ok ho visto l'errore, è un errore più generico sul recall che ora stiamo vedendo

**Comment by morpheus8888** [comment]
fixed
