### ISSUE TITLE
Ritualism da client

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#211]
@giga487 manca nella schermata del client, su options, useskill, la skill ritualism

**Comment by giga487** [comment]
@Darksuitjer stai esagerando ora

**Comment by giga487** [comment]
@Darksuitjer testala appena puoi.
Ora è una possibilità della  macro USE SKILL

**Comment by Darksuitjer** [comment]
> @Darksuitjer testala appena puoi.
> Ora è una possibilità della macro USE SKILL

tu menti!!! 🗡️

**Comment by giga487** [comment]
Io non mento, ma mento perché apprezzo le mentine.

Cmq tutto quello fatto durante le mie ore di lavoro verrà rilasciato appena ho voglia.
