### ISSUE TITLE
Region da rimuovere da vs e auctionsystem

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#212]
Mi servirebbe che nella region di jhelom il .vs e il .auction non funzionino

**Comment by gmocciaro** [comment]
messo un ulteriore check, speriamo bene

**Comment by morpheus8888** [comment]
lasciamelo aperto fino a quando non verifichiamo pls

**Comment by gmocciaro** [comment]
okke

**Comment by morpheus8888** [comment]
infatti non funziona nemmeno sta volta top XD

**Comment by gmocciaro** [comment]
fixed, controlla e in caso chiudi

**Comment by morpheus8888** [comment]
funziona
