### ISSUE TITLE
[Client] Salvare l'ultima posizione dei gump

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#216]
Attualmente, quando un gump viene aperto da un player pe la prima volta, viene renderizzato ad una certa X-Y decisa dal server. Se un player decide di spostare il gump, le nuove X-Y vengono salvate in variabile, in modo che se quello stesso player riapre quello stesso gump, viene aperto direttamente nell'ultima posizione scelta dal player.

Questa "preferenza" però viene persa quando il client viene chiuso.

Sarebbe carino salvare in qualche file di config (json o XML) tutte le posizioni dei gump, così i player se le ritrovano sempre nella zona dello schermo che più gradiscono.

Attualmente esistono già dei gump che hanno questo esatto comportamento, come il gump del paperdoll (anche se viene generato direttamente dal client), magari si può vedere come si comporta in quel caso.

**Comment by gmocciaro** [comment]
ci do un occhiata io @giga487

**Comment by giga487** [comment]
> ci do un occhiata io @giga487

Ma questo gia avviene nel file gumps.xml

Di quali gump parli?

**Comment by gmocciaro** [comment]
di tutti i gump, anche quelli che invia il server che si resettano le x-y quando chiudi il client

ho visto che viene gestito qui:
`UIManager.GetGumpCachePosition(gumpID, out Point pos)`

**Comment by gmocciaro** [comment]
fatto! aspetto di capire come sta messo @giga487 per poterlo rialsciare

**Comment by giga487** [comment]
Grande!
