### ISSUE TITLE
bug cavalcature premium

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#217]
quando scendi dalla cavalcatura windrunner mette 5 e non ti aggiorna i followers

**Comment by morpheus8888** [comment]
@Ale1991 ricordami come si setta l'hue

**Comment by Ale1991** [comment]
> @Ale1991 ricordami come si setta l'hue

Nel costruttore della statuetta, oltre a settare la var Hue, va settata la var. NonTransparentMountedHue = Hue;

**Comment by morpheus8888** [comment]
fixed
