### ISSUE TITLE
log out gump

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#219]
modificare il logout gump in modo che avvisi il player che è nella condizione di ritrovarsi morto a causa del fatto che sta sloggando fuori da felucca.

Ne possiamo approfittare per parlare di tempistiche se si slogga lontano da un letto e spiegare la dinamica del letto per sloggare istant

**Comment by giga487** [comment]
Vorresti un gump che ti spiega come si slogga o che in base a dove si slogga cambia?

**Comment by morpheus8888** [comment]
both

**Comment by Ale1991** [comment]
fatto
