### ISSUE TITLE
Cavalcature Premium

### ISSUE THREAD

**Issue by Ket4mina** [uomars/UOMars#221]
Apro un nuovo post per riunire tutte le problematiche qui. 

Avevo deciso di provare tutte le mount questa mattina facendo questo procedimento.

1) .premiun
2) Scelta della mount
3) Doppio click sulla mount
4) Acquisto del cavallo da sacrificare 
5) Mount sotto il sedere
6) .premium 
7) e tutto da capo

Mi sono dovuto fermare allo swamp dragon (senza poterlo cavalcare) perchè tutti gli slot dei follower si sono riempiti 5/5. Facendo .petlist non risultano pet collegati a me 

Wild Tiger – OK *
Wild White Tiger – Non è Bianca *
Wild Black Tiger – Non è Nera *
Kirin – OK * 
Red Kirin – OK *
Shadow Beetle – OK * 
Swamp Dragon – Esce ethereal nella sacca ma una volta evocato esce giusto *
Scaled Swamp Dragon – Esce ethereal nella sacca e rimane ethereal anche una volta evocato *
Lion nigthmare – Esce ethereal nella sacca e rimane ethereal anche una volta evocato *
Trojan Horse – Esce ethereal nella sacca a rimane ethereal anche una volta evocato *
Eowmu – Esce ethereal nella sacca e rimane ethereal anche una volta evocato
Tarantula – Esce ethereal nella sacca ma una volta evocato esce giusto *
Polar Bear – OK *
Hiryu – Esce Ethereal nella sacca ma una volta evocato esce giusto *
Reptalon – Esce ethereal nella sacca e rimane ethereal una volta evocato *
Cu Sidhe – Esce ethereal nella sacca ma una volta evocato esce giusto *
Wind Runner – Esce ethereal nella sacca ma una volta evocato esce giusto *
Skeletal Horse – Esce ethereal nella sacca e rimane ethereal una volta evocato *
Unicorn – Esce ethereal nella sacca e rimane ethereal una volta evocato *
Lasher – OK *
Pony – Esce ethereal nella sacca e rimane ethereal una volta evocato *
Serpetntine Dragon – Esce thereal nella sacca ma una volta evocato esce giusto *
Boura – OK *
Ancient Hell Hound – OK *

Le mount con l'asterisco sono quelle che mi hanno lasciato 1 punto nei follower una volta scelta la nuova mount

Allora le ho provate tutte. Il problema del follower lo fanno tutte alla fine perchè ho ricontrollato bene. I colori ed i nomi delle mount sono tutti scritti qui sopra così potete sistemarle

**Comment by gmocciaro** [comment]
@morpheus8888 tu fai logiche all'ondelete dell'animale? perchè forse si sta buggando nel meccanismo che cancella la vecchia mount quando richiedi la nuova, ora in caso faccio un controllo lato codice

**Comment by gmocciaro** [comment]
> > @morpheus8888 tu fai logiche all'ondelete dell'animale? perchè forse si sta buggando nel meccanismo che cancella la vecchia mount quando richiedi la nuova, ora in caso faccio un controllo lato codice
> 
> Ora sono full follower e non posso provare le altre. Appena mi sistemate continuo a testare anche le altre per i colori e bug vari

io ora sono in ufficio e non posso aiutarti, appena qualcuno può andare online te lo fixa

**Comment by morpheus8888** [comment]
@gmocciaro  non ricordo, se ti serve dimmelo che controllo anche io

**Comment by kentar91** [comment]
Grande ike!

**Comment by Ale1991** [comment]
Quale colore scegliereste?
2500
![image](https://user-images.githubusercontent.com/21221719/131986483-f3f1f301-aa77-4904-b292-f6c455fb22bc.png)
oppure 
1154
![image](https://user-images.githubusercontent.com/21221719/131986592-4214173a-5104-4a8c-80b6-b8140035c76f.png)
@Ket4mina

**Comment by gmocciaro** [comment]
ho fixato il discorso del follower , ci pensi tu per il discorso dei colori @morpheus8888?

**Comment by morpheus8888** [comment]
@gmocciaro se lo segui tu mi fai un favore che sto concentrato sulle creature per kentar

**Comment by gmocciaro** [comment]
fixato tutto
