### ISSUE TITLE
Skill utilizzabile e skill attive.

### ISSUE THREAD

**Issue by giga487** [uomars/UOMars#222]
### Discussed in https://github.com/uomars/UOMars/discussions/87

<div type='discussions-op-text'>

<sup>Originally posted by **giga487** May  9, 2021</sup>
blob:file:///c3d793ce-d24d-43e4-bf9c-e3164d17328c

Ho la necessità di allineare il client lato skillGump e lato macro delle options. Ho bisogno di sapere quali sono le skill attive e no.</div>

**Comment by giga487** [comment]
Anatomy, Detecting Hidden, Hiding, Parry, Animal Taming, Animal Lore, Discordance, Pacemaking, Provocation, Stealing, Tracking

**Comment by giga487** [comment]
sicuramente manca ritualism.

**Comment by Darksuitjer** [comment]
Meditation, Tracking, Evaluating Intellligence, Inscription

Arms lore? Poisoning?

**Comment by Darksuitjer** [comment]
ah ps Arms Lore manca nello skill gump del paperdoll 🍡

**Comment by Ale1991** [comment]
> Meditation, Tracking, Evaluating Intellligence, Inscription
> 
> Arms lore? Poisoning?

Meditation è diventata passiva, funziona esattamente come focus. Se resti fermo medita più velocemente.
Inscription, Evaluating Intelligence, Poisoning, Anatomy, Forensic Evaluation per adesso danno solo bonus passivi, se le usi non succede nulla.

Nello skillgump del paperdoll:
- Nella categoria Aggressive mancano le skill Fading e Weakening 
- Nella categoria Aggressive c'è la skill Bombing che è stata tolta (va eliminata anche dal gump)

- Nella categoria Defensive manca la skill Ritualism 

- Nella categoria Worker manca la skill Arms Lore (io la sposterei anche nel caps da Utilities a Worker visto che serve solo ai worker)

- Nella categoria Worker mancano le skill Skinning e Harvesting 
- Nella categoria Worker la skill Precision (va spostata in Aggressive)

**Comment by giga487** [comment]
@Ale1991 queste modifiche sono già state fatte, appena arrivo a casa in notte fonda, fixo il client

**Comment by giga487** [comment]
Non è vero, sono ubriaco e niente

**Comment by giga487** [comment]
> > Meditation, Tracking, Evaluating Intellligence, Inscription
> > Arms lore? Poisoning?
> 
> Meditation è diventata passiva, funziona esattamente come focus. Se resti fermo medita più velocemente.
> Inscription, Evaluating Intelligence, Poisoning, Anatomy, Forensic Evaluation e Animal Lore per adesso danno solo bonus passivi, se le usi non succede nulla.
> 
> Nello skillgump del paperdoll:
> 
> * Nella categoria Aggressive mancano le skill Fading e Weakening
> * Nella categoria Aggressive c'è la skill Bombing che è stata tolta (va eliminata anche dal gump)
> * Nella categoria Defensive manca la skill Ritualism
> * Nella categoria Worker manca la skill Arms Lore (io la sposterei anche nel caps da Utilities a Worker visto che serve solo ai worker)
> * Nella categoria Worker mancano le skill Skinning e Harvesting
> * Nella categoria Worker la skill Precision (va spostata in Aggressive)

Cartography? non c'è nel .caps, è stata tolta?

**Comment by giga487** [comment]
![image](https://user-images.githubusercontent.com/19823607/132133792-eb74e51e-c217-4c38-a078-323469b8e070.png)

Questo è lo skill gump che uscirà quando rilascio il client

**Comment by Ale1991** [comment]
> > > Meditation, Tracking, Evaluating Intellligence, Inscription
> > > Arms lore? Poisoning?
> > 
> > 
> > Meditation è diventata passiva, funziona esattamente come focus. Se resti fermo medita più velocemente.
> > Inscription, Evaluating Intelligence, Poisoning, Anatomy, Forensic Evaluation e Animal Lore per adesso danno solo bonus passivi, se le usi non succede nulla.
> > Nello skillgump del paperdoll:
> > 
> > * Nella categoria Aggressive mancano le skill Fading e Weakening
> > * Nella categoria Aggressive c'è la skill Bombing che è stata tolta (va eliminata anche dal gump)
> > * Nella categoria Defensive manca la skill Ritualism
> > * Nella categoria Worker manca la skill Arms Lore (io la sposterei anche nel caps da Utilities a Worker visto che serve solo ai worker)
> > * Nella categoria Worker mancano le skill Skinning e Harvesting
> > * Nella categoria Worker la skill Precision (va spostata in Aggressive)
> 
> Cartography? non c'è nel .caps, è stata tolta?
> Cooking?
> Item Id?

sono state tolte tutte e 3

**Comment by Ale1991** [comment]
> ![image](https://user-images.githubusercontent.com/19823607/132133792-eb74e51e-c217-4c38-a078-323469b8e070.png)
> 
> Questo è lo skill gump che uscirà quando rilascio il client.
> 
> @morpheus8888 @Ale1991 @gmocciaro

è come quello di adesso... servono le modifiche scritte nel testo di questa issue

**Comment by giga487** [comment]
> > ![image](https://user-images.githubusercontent.com/19823607/132133792-eb74e51e-c217-4c38-a078-323469b8e070.png)
> > Questo è lo skill gump che uscirà quando rilascio il client.
> > @morpheus8888 @Ale1991 @gmocciaro
> 
> è come quello di adesso... servono le modifiche scritte nel testo di questa issue

assolutamente si, devo aggiungere le skill del gump.

**Comment by Darksuitjer** [comment]
sono in ordine alfabetico.. finalmente è piu ordinato.... 💯 
Manca anche Harvesting e skinning nel worker

**Comment by giga487** [comment]
Lo skill Gump è sempre stato ordinato per ordine alfabetico, una proposta potrebbe essere quella di mettere il caps in ordine alfabetico.

**Comment by morpheus8888** [comment]
@giga487 cosa ti manca da sapere da parte mia?

**Comment by giga487** [comment]
> @giga487 cosa ti manca da sapere da parte mia?

![image](https://user-images.githubusercontent.com/19823607/132142783-f28451b2-b51d-4376-a45e-b81fca89d4ce.png)

Che mi dici che sono bravo

**Comment by gmocciaro** [comment]
> Lo skill Gump è sempre stato ordinato per ordine alfabetico, una proposta potrebbe essere quella di mettere il caps in ordine alfabetico.
> 
> Aggiungo le skill nuove ed ho finito su questo argomento e di riflesso sulle skill attive e sul tasto delle macro UseSkill

ma il caps è in ordine alfabetico, lo hai fatto tu no? in caso lo faccio io

**Comment by giga487** [comment]
Ho fatto il caps in ordine alfabetico e lo skill gump di default in ordine alfabetico.

@Ale1991  ho anche messo Arms Lore tra le skill worker di entrambi i gump, sia client che server.

**Comment by Darksuitjer** [comment]
che bravo!!!
