### ISSUE TITLE
Caps gump: Aggiungere filtri e tasti

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#223]
aggiungere al gump del caps una sezione "filtra" che accetta un testo e i due bottoni che mi sono dimenticato che erano presenti nel vecchio gump

**Comment by gmocciaro** [comment]
@morpheus8888 attualmente la lista non è ordinata alfabeticamente, secondo te è meglio ordinarla o la lasciamo così?

![image](https://user-images.githubusercontent.com/12816659/131981259-15f799ab-15e2-471c-9dfd-fcdbab458d16.png)

**Comment by Darksuitjer** [comment]
ordinandola sarebbe piu pulito secondo me

**Comment by gmocciaro** [comment]
dooone
