### ISSUE TITLE
[Fishing] Pesca nell'acqua non fa nulla

### ISSUE THREAD

**Issue by andreadellacorte** [uomars/UOMars#23]
Come non-worker a Cove, non succede nulla quando si usa la canna da pesca sull'acqua

**Comment by kentar91** [comment]
inserire una guida in game su come si raccolgono le risorse.  (kentar)

proposta da valutare: sarebbe carino che quando si doppio clicca uno strumento di raccolta viene mostrato un gump che ti dice che devi cliccare il deposito e non lo strumento @Ale1991 @giga487 @gmocciaro @morph
