### ISSUE TITLE
Mod/Check contributi skill

### ISSUE THREAD

**Issue by Ale1991** [uomars/UOMars#231]
![healing+ritualism](https://user-images.githubusercontent.com/21221719/132109890-e2883832-dded-4ed6-b8f9-f3d523fcf07d.png)
![spell offensive](https://user-images.githubusercontent.com/21221719/132109857-60fa34b7-f6c8-4f44-bcdb-618c7d5e6e14.png)
![inscription](https://user-images.githubusercontent.com/21221719/132109858-229bd282-17ba-4725-9bf7-e491a1e528c6.png)
![spell difensive](https://user-images.githubusercontent.com/21221719/132110663-bc9b4a5d-f173-4fe6-8266-9659f6567b4f.png)

**Comment by Ale1991** [comment]
fixati:
- Clumsy, Feeblemind, Weaken
- Agility, Cunning, Strength
- Curse, Bless
- Evaluating Intelligence damage bonus to 60% (was 40%)
- Protection/ArchProtection duration increased to 8 sec (was 3) DA TESTARE

**Comment by Ale1991** [comment]
restano da ricontrollare:
- Spell Cure e ArchCure
- Tutte le pozze bless/agility/intelligence da ridurre a +30 (da 35)
- Controllare le altre pozze
- Rivedere tutte le steak (non prendono bonus dalle skill)

**Comment by lyon1235** [comment]
> fixati:
> 
> * Clumsy, Feeblemind, Weaken
> * Agility, Cunning, Strength
> * Curse, Bless
> * Evaluating Intelligence damage bonus to 60% (was 40%)
> * Protection/ArchProtection duration increased to 8 sec (was 3) DA TESTARE

testato nel pomeriggio la magia strenght con iscription a 100, da solo stesso bonus del 10 % come se fosse a 0. 
Il curse con 100 iscrip cursa di 25 e non 30 come da tabella. 
il resto confermo tutto anche protection e arch prot

**Comment by Ale1991** [comment]
fixed:
- BaseHealPotion, HealPotion, YellowBoiledFishSteak, YellowBoiledFishSteakLvl0
- BaeRefreshPotion, RefreshPotion, RedBoiledFishSteak, RedBoiledFishSteakLvl0
- BaseManaPotion, ManaPotion, BlueBoiledFishSteak, BlueBoiledFishSteakLvl0
- BaseStrengthPotion, StrengthPotion, WhiteBoiledFishSteak, WhiteBoiledFishSteakLvl0
- BaseAgilityPotion, AgilityPotion, non esistono le fish steak equivalenti alle agility
- BaseIntelligencePotion, IntelligencePotion, non esistono le fish steak equivalenti alle intelligence
- BaseCurePotion, CurePotion, OrangeBoiledFishSteak, OrangeBoiledFishSteakLvl0
- BaseCarrotPotion, CarrotPotion
- 
- Rimosse le superclassi Base delle FishSteak e derivate le FishSteak direttamente dalle corrispondenti BaseNamePotion
- in progress...

**Comment by Ale1991** [comment]
> > fixati:
> > 
> > * Clumsy, Feeblemind, Weaken
> > * Agility, Cunning, Strength
> > * Curse, Bless
> > * Evaluating Intelligence damage bonus to 60% (was 40%)
> > * Protection/ArchProtection duration increased to 8 sec (was 3) DA TESTARE
> 
> testato nel pomeriggio la magia strenght con iscription a 100, da lo stesso bonus del 10 % come se fosse a 0.
> Il curse con 100 iscrip cursa di 25 e non 30 come da tabella.
> il resto confermo tutto anche protection e arch prot

il curse devi sempre tenere in considerazione che viene scalato esattamente della percentuale di energy resist che hai

per il resto la magia strength, agility e cunning avevano un errore, fixato

**Comment by Ale1991** [comment]
chiudo, dovrebbe essere tutto fixato e testato. Riaprite se necessario
