### ISSUE TITLE
War/Peace

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#233]
War si toglie ancora dopo 30 secondi

**Comment by Ale1991** [comment]
fixato. 
Nuovo funzionamento: War non si disattiva piu' automaticamente ma per mantenere lo stato di HeatOfCombat (che servira' per non far recallare o far hiddare le persone) sara' necessario colpirlo o averlo come target e in schermata.
Anche perdendo l'Heat Of Combat (che si aggiorna ogni 30 secondi, condizioni sopra descritte permettendo) sara' sempre possibile colpire la persona che avete attaccato
