### ISSUE TITLE
Tipi di creature

### ISSUE THREAD

**Issue by Ket4mina** [uomars/UOMars#234]
Oggi ho provato al volo le armi da fencer in elementium. Sono andato al dungeon degli scheletri sopra Pryma ed do potenziato al 100% l'arma contro gli undead ma il danno è rimato sempre lo stesso. Allora ho provato a fare inspect per capire se facevano parte di un'altra razza ma non dice nulla a riguardo. C'è qualcosa da sistemare?

**Comment by Darksuitjer** [comment]
> Oggi ho provato al volo le armi da fencer in elementium. Sono andato al dungeon degli scheletri sopra Pryma ed do potenziato al 100% l'arma contro gli undead ma il danno è rimato sempre lo stesso. Allora ho provato a fare inspect per capire se facevano parte di un'altra razza ma non dice nulla a riguardo. C'è qualcosa da sistemare?

Si per il momento molti mostri non hanno ancora lo slayer

**Comment by Ket4mina** [comment]
> 
> 
> > Oggi ho provato al volo le armi da fencer in elementium. Sono andato al dungeon degli scheletri sopra Pryma ed do potenziato al 100% l'arma contro gli undead ma il danno è rimato sempre lo stesso. Allora ho provato a fare inspect per capire se facevano parte di un'altra razza ma non dice nulla a riguardo. C'è qualcosa da sistemare?
> 
> Si per il momento molti mostri non hanno ancora lo slayer

Ok perchè sarebbe utile tramite inspect capire il tipo di creatura per poter usare l'arma giusta

**Comment by morpheus8888** [comment]
l'obiettivo di inspect è proprio quello, sarà attivato man mano
