### ISSUE TITLE
Pvm - problema altezze

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#235]
Si puo' attaccare da sopra a sotto
Se sono al 1° piano di un edificio posso attaccare mob sotto di me senza che loro mi facciano danno

**Comment by gmocciaro** [comment]
credo che fino a 20 di z è possibile attaccarsi, andare a modificare la logica può creare più problemi che altro, inoltre noi questo lo sfruttiamo per poter attaccare i caster sulle mura (tipo pyrma o la città pk), dovreste provare a fare un tetto a z 21 e vedere se vi fa attaccare ancora

**Comment by Ale1991** [comment]
Ho provato a riprodurre il bug ma senza successo.
Draker/Lollo era riuscito a trovarlo. Vedete se riesce/riuscite a riprodurlo e come,

**Comment by kentar91** [comment]
chiudo
