### ISSUE TITLE
Gump bounty hunter

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#241]
gump per il bounty hunter, per dubbi chiedi a @Ale1991

**Comment by gmocciaro** [comment]
3/4 della mia vita è fare gump

**Comment by Darksuitjer** [comment]
> 3/4 della mia vita è fare gump

House of Pain // Gump Gump Gump Around
e cambierei il soprannome in Gumpà

**Comment by gmocciaro** [comment]
Aggiunto un check che un player non può comprare case e vendor mentre è bounty haunter

**Comment by gmocciaro** [comment]
fatto!
