### ISSUE TITLE
Sistema di traduzioni

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#242]
creare un sistema per cercare di tradurre la maggior parte delle stringhe presenti nel codice, dall'inglese a varie lingue. Le lingua sarà poi impostata da un player tramite un comando (o dal client).

**Comment by Darksuitjer** [comment]
Bravo! cosi mi piaci!

**Comment by giga487** [comment]
Questa feature lato client esiste gia, bisogna reworkare tutte le stringhe e creare un dizionario che switcha in base all'impostazione del personaggio.

Per fare una bella cosa, è necessario verificare il check della lingua da client e far si che il server legga.

**Comment by gmocciaro** [comment]
> Questa feature lato client esiste gia, bisogna reworkare tutte le stringhe e creare un dizionario che switcha in base all'impostazione del personaggio.
> 
> Per fare una bella cosa, è necessario verificare il check della lingua da client e far si che il server legga.
> 
> E secondo me la cosa migliore sarebbe creare dei file esterni in cui sono salvati i testi dei gump, lato server in bi lingua.

nativamente, esistono i cliloc che sono dei file traducibili, ma sono estremamente limitati, quindi l'idea mia (già realizzata, sto testando) è la seguente:

I metodi che trattano stringhe, quali .SendMessage e .AddHtml .AddTooltip (gump) chiameranno una mia classe, questa classe controlla se all'interno di un file XML esiste la traduzione nella lingua scelta dall'utente, se esiste torna la stringa tradotta.
Se non esiste, fa una chiamata API a google translate e salva il valore dentro quel file xml, così man mano si crea questo mega file xml con tutte le traduzioni

**Comment by giga487** [comment]
Vanno cmq reworkati tutti i Gump e dobbiamo decidere come salvare i dati.

**Comment by gmocciaro** [comment]
che intendi?

**Comment by giga487** [comment]
Bisogna analizzare tutte le stringhe e mettere dei filtraggi.

I nuovi Gump io li sto generando con degli string Array bidimensionali che hanno un enum eng/ita.

E poi carico direttamente quella stringa.

**Comment by gmocciaro** [comment]
> Bisogna analizzare tutte le stringhe e mettere dei filtraggi.
> 
> I nuovi Gump io li sto generando con degli string Array bidimensionali che hanno un enum eng/ita.
> 
> E poi carico direttamente quella stringa.

In realtà lato server è abbastanza diverso, però comunque la maggior parte delle stringe sono lato server quindi lato client possiamo tenerlo più semplice.

Attualmente lato server ho fatto una classe `Translations` che ha un metodo pubblico `GetTranslation` 
Questo metodo accetta una stringa in inglese e una lingua (tramite enum). 

Dentro il metodo controllo in una variabile statica se esiste la traduzione per la stringa passata, se non esiste chiamo una API fatta da me che sfrutta un servizio di traduzioni che offre Amazon AWS (https://aws.amazon.com/it/translate/) e una volta tornata la stringa tradotta, la salva sia in un file XML e la aggiunge alla variabile statica.

Quindi alla lunga si avrà un file XML che contiene il messaggio originale, le traduzioni nelle varie lingue (per ora solo IT ma funziona già con tutte le lingue che vuoi) e la data di ultima modifica.

All'avvio del server, c'è un metodo che legge tutto il file XML e lo carica dentro la famosa variabile statica, in modo che per le traduzioni già esistenti, interrogo direttamente la variabile, per quelli non esistenti mi prendo la traduzione in tempo reale e l'aggiungo automaticamente, in modo che al prossimo riavvio è già precaricata.

AWS Translations mi da gratuitamente traduzioni per 2Milioni di lettere al mese e mi fa creare API gratuitamente fino a 1 milione di richieste al mese (dovremmo farcela più che tranquillamente)

**Comment by gmocciaro** [comment]
Cosa da tradurre:

- .purchases
- .sales
- .events
- Vendor system
- Cities
- Static houses
- Vendor search
- AUC
- Premium

**Comment by giga487** [comment]
Le frasi dei mob
Le frasi del sistema PVM plus (pussy)

**Comment by gmocciaro** [comment]
Al momento abbondono l'idea perchè traducendo i testi, si distruggono i gump (il testo tradotto avrà ovviamente una lunghezza diversa e i gump sono tarati sulla lunghezza delle stringhe in inglese, putroppo funziona male il sistema di gump di base), rifare tutti i gump praticamente vuoldire rifare 2 anni di lavori e non è proprio un idea perseguibile
