### ISSUE TITLE
possibile bug hitching post case

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#249]
controllare cosa succede se in una casa l'hitching post sta dentro invece che fuori? perché quando deve buttare il cavallo fuori mi sa che esplode tutto, facendomi un giro siccome ho visto diversi hitching post dentro dobbiamo metterci una pezza lato codice

**Comment by gmocciaro** [comment]
Allora, il problema è legato al sign e non al post, nel senso che se un cavallo si stama, viene buttato fuori casa nella posizione del sign

![image](https://user-images.githubusercontent.com/12816659/132314876-3741e3d0-37b9-4027-82b1-6d7dc5803838.png)

quindi l'hitching può stare dentro la region, è il cartello che non può.

Supponendo che per qualche motivo il cartello è dentro casa, dovrebbe succedere che prova a ri-buttarlo dentro casa, ma non può perchè gli animali stamati non possono entrare (non possono entrare, ma se sono dentro posso starci) dentro la region della casa, quindi vengono ributtati nel punto precedente che è sempre dentro casa, creando un loop (non testato)

ricapitolando:

- Hiching dentro casa con pet tamato: OK
- Il cavallo si stama, visto che è dentro la region della casa, viene buttato fuori all'altezza del cartello
- Se il cartello è dentro la region della casa, viene triggerato l'OnMoveInto della region, che torna false se il pet è stamato
- l'OnMoveInto rimette il cavallo nel punto precedente che è sempre dentro la casa
- va in loop

però tutto ciò non è mai stato testato
