### ISSUE TITLE
modifica plague spawn-beast

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#258]
come accennato l'altro giorno mi servirebbe questa correzione per il dungeon plague:

il plague spawn sono una serie di mob livellabili senza "expiretime"
la plague beast, appena perde metà vita evoca i plague spawn slave con expire time di 1 ora
i plague spawn slave sono settati livello0

attualmente i plague spawn e i plague spawn slave sono invertiti come concetto di expire time
![image](https://user-images.githubusercontent.com/83588629/132921305-eef40f4d-1bc8-47e9-b491-da233e9297a3.png)

non so se alla fine l'hai fatto, nel dubbio te lo segno :*

**Comment by morpheus8888** [comment]
i plague spawn slave si deletano dopo 1 ora lato codice, non compare nel props, i plague spawn (nn slave) ho lasciato la logica dell'expire time perché in futuro potrebbe fare comodo. Il nome significa che qualcosa può spownarli, quindi se vogliamo fare che un mostro più forte ne spowna qualcuno di livello 3 ad esempio abbiamo già la logica dell'expire time. Che scompaiono dopo un'ora è indifferente, tanto respawnono e se sono in fight non scompaiono.
