### ISSUE TITLE
modificare il silenzio sui player

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#261]
attualmente c'è lo squelch in game, quello va bene. Servirebbero altre due condizioni da gestire separatamente,:
- mutarlo sulla chat general;
- inserire un filtro antispam su quello che scrive, ad esempio può mandare un mex ogni 10 secondi o ogni minuto.

In sintesi mutarlo sulla chat general deve essere un'impostazione a parte selezionabile e in più si può scegliere se mutarlo in game o mettergli un filtro che lo costringe a parlare una volta ogni x secondi.

**Comment by gmocciaro** [comment]
@morpheus8888 il mute deve essere a livello di quel player o a livello di account?

**Comment by morpheus8888** [comment]
@gmocciaro player, se non è difficile metti anche opzionale account intero

**Comment by gmocciaro** [comment]
rimuovere la chat custom che non useremo e impostare da file di conf la slow chat

**Comment by gmocciaro** [comment]
done
