### ISSUE TITLE
Tutorial [errori e consigli]

### ISSUE THREAD

**Issue by DarkanSheZhar** [uomars/UOMars#262]
la terza stone di inizio, quella di discord, non da descrizione, sembra non funzionare quindi un cliccatore seriale come me ci clicca sopra 10 volte... dopo 1 minuto hai 200 pagine aperte di discord :) mettete un info più chiara

la quarta stone è in inglese

----TUTORIAL----

spiegare come fare macro.scocca

il sacco di reags resta nel backpack

abbassare vita scheletro hiddato

nel gump di pacemaking trovi scritto 2 volte pacemaking invcece di musican
![image](https://user-images.githubusercontent.com/90500807/132953345-2b675216-d0e9-4316-828f-ca1e763a3395.png)

pacemaking non funziona 

per passare oltre chiede sia di resettare le skill che di avere 3 skill a 100
![image](https://user-images.githubusercontent.com/90500807/132953359-e00e816c-f692-411f-87fa-deae74399e0c.png)

bug grafico stanza dopo pacemaking
![image](https://user-images.githubusercontent.com/90500807/132953315-8c72c6bc-c2a1-4116-9192-41050b5efd3e.png)

Ultima stanza da già segnato il reset delle skill, sono uscito full skill.

----------------TUTORIAL WORKER-------------

il gump chiede di usare la pozza shrink ma non è presente, avete messo l'item per shrinkare

il gump chiede di uscire avendo una shrink potion in bpack ma non si può prendere

![image](https://user-images.githubusercontent.com/90500807/132953589-b0630cf3-297d-42f2-a9b6-c9ecd4ff5b07.png)

![image](https://user-images.githubusercontent.com/90500807/132953705-b7150437-3b3a-4063-aaa0-e537299a3552.png)

nella stanza di mining viene data una picca base che prende 1 iron, farne prendere 50 forse è troppo, essendo un tutorial basterebbe prenderne 10
![image](https://user-images.githubusercontent.com/90500807/132953955-8574b6bc-396e-4fd4-a604-e674fc86eace.png)

mentre stai minando si rompe la picca e si bugga la skill [APERTO ISSUES APPOSITO]
![image](https://user-images.githubusercontent.com/90500807/132954082-bb346e0c-431b-46d7-92b8-f54c374614c6.png)

Tutorial lumber, anche qui prendere 50 log è eccessivo 
*bella l idea di mettere in fila di rarità le risorse, lo farei anche con gli altri*

nel tutorial delle erbe prenderne 100 per tipo è veramente troppo, abbasserei a 20
![image](https://user-images.githubusercontent.com/90500807/132954570-ab9235a6-5d66-46c7-8023-09dd359d0049.png)
ho perso più di 10 minuti a guardare lo schermo per raccogliere 300 piantine... la gente lefta il tutorial al 100% :)

al refine delle erbe manca la portra
![image](https://user-images.githubusercontent.com/90500807/132955538-d04d05cc-cb2a-4053-91f4-dfc1d73a0326.png)

nelle skill del bowcraft richiede 20 bow e 1 arms lore, ma hai solo 20 punti per le lavorative
![image](https://user-images.githubusercontent.com/90500807/132955780-f58a7af8-5669-4eb8-a1ac-7b1b34172ae2.png)

stessa cosa nel craft del carpentiere, in più manca la porta
![image](https://user-images.githubusercontent.com/90500807/132955897-6d764fb5-7582-4c0c-9a5f-54c47029e1d5.png)
tikering uguale, manca porta e skill necessarie troppo alte
![image](https://user-images.githubusercontent.com/90500807/132955906-51ea6d9e-c15a-4152-b595-33671765be6c.png)
anche alchemist, arms lore e alchemi richieste troppo alte e manca la porta
![image](https://user-images.githubusercontent.com/90500807/132955936-df14c555-39fb-4321-af1b-248023f76c9f.png)
anche tailoring 
![image](https://user-images.githubusercontent.com/90500807/132955951-4b271a41-be6c-4f6d-9858-7604ec0ffadc.png)

alla fine del tutorial, come per quello non worker, mi da la spunta sul reset anche se non ho resettato, posso uscire con le skill messe, anche se qui poco conta visto che ho cmq max 20 punti, mentre in quello di prima potevo usare l exp prese sul tavolo ed uscire full skill
![image](https://user-images.githubusercontent.com/90500807/132955994-63c05bd1-7e1f-4761-9e5c-9f07c66a7b29.png)

in entrambi i tutorial non ho avuto l'exp come premio

----------------------------------------CONSIDERAZIONI PERSONALI---------------------------------------

il tutorial è bellissimo! ed il premio in skill fantastico

detto questo:

- il tutorial va accorciato, andrebbero messe nella stessa stanza raccolta, rifinitura e craft di ogni materiale, dimezzando i .reset e i 
.caps oltre al tempo necessario per finire il percorso

- bisogna assolutamente cambiare i tool base e mettere quelli che raccolgono più velocemente abbassando anche il numero richiesto per raccogliere

- mettere un tutorial sulle macro e sul cast

cmq ottimo lavoro per tutti i nuovi cambiamenti :)

**Comment by morpheus8888** [comment]
@kentar91  quelli dove manca la roba da spawnare pensaci tu

**Comment by kentar91** [comment]
shrink potion risolta. aggiunta sacca sul tavolo con bloodmoss e pozze vuote

per gli strumenti di raccolta c'erano ancora i "base", sostituiti con quelli normali. ora con 10 di skill raccogli minimo 11 alla volta.
quindi vanno bene le quantità

per la sickle ho trovato questo bug:
![image](https://user-images.githubusercontent.com/83588629/132959029-0b38eb9c-9be6-48a7-84bf-56507a10248f.png)
![image](https://user-images.githubusercontent.com/83588629/132959033-a2da57bb-4b49-43b9-b0e1-bdd4800fbd9f.png)
la sickle normale sul .add e sul tavolo da lavoro è stata chiamata bone harvester, ma quando la crei si chiama sickle.
esiste però la basesickle.
rimettete come prima tutto a sickle. grazie

per quanto riguarda i buchi nei muri gli arredatori devono ancora lavorare a quelle stanze. quelle porte sono li come riferimento di costruzione.

**Comment by morpheus8888** [comment]
@DarkanSheZhar 
- i reset non si possono dimezzare, è il gioco putroppo, anche perché un player capisce che ogni cambio purtroppo è un reset
- dove si raccolgono risorse ora sfoltisco, ne faccio raccogliere un paio e basta
- il tutorial per le macro non sono riuscito a trovare un modo di farlo, poi ci ragiono meglio con @Ale1991 @gmocciaro e @giga487  e vediamo se ci si riesce

Quando sarà tutto sistemato bisogna cronometrare con gente realmente niubba, comunque non devono metterci meno di un'ora a percorso altrimenti il pg full skill è praticamente regalato

**Comment by DarkanSheZhar** [comment]
@morpheus8888 
mettendo raccolta, refine e craft nella stessa stanza dimezzi i .reset e anche i passaggi da fare, secondo me renderesti il tutorial più chiaro e veloce

**Comment by giga487** [comment]
> @DarkanSheZhar 
> - i reset non si possono dimezzare, è il gioco putroppo, anche perché un player capisce che ogni cambio purtroppo è un reset
> - dove si raccolgono risorse ora sfoltisco, ne faccio raccogliere un paio e basta
> - il tutorial per le macro non sono riuscito a trovare un modo di farlo, poi ci ragiono meglio con @Ale1991 @gmocciaro e @giga487  e vediamo se ci si riesce
> 
> Quando sarà tutto sistemato bisogna cronometrare con gente realmente niubba, comunque non devono metterci meno di un'ora a percorso altrimenti il pg full skill è praticamente regalato

Si potrebbe fare un Gump tutorial lato client. un po' complicato da fare, in effetti, ho altre priorità al momento però.

**Comment by morpheus8888** [comment]
Capisco quello che dici, me lo tengo a mente quando prenderemo i tempi, se
dobbiamo accorciare di più usiamo questa strategia

Il Dom 12 Set 2021, 10:27 DarkanSheZhar ***@***.***> ha
scritto:

**Comment by Darksuitjer** [comment]
beh se la durata deve essere relativamente lunga, dimezzando i tempi per alcune stanzine, si potrebbere aggiungere qualcosa in piu...
non so se a livello di tutorial si possano fare, ma cmq faccio qualche esempio stupido
- fare un page
- sloggare col doppioclick su un letto
- morire e usare il ghosttravel
(mi piace pensare alle cose più complicate!!! 👯 )
se invece già cosi risulta troppo lungo, allora meglio accorciare

**Comment by DarkanSheZhar** [comment]
> beh se la durata deve essere relativamente lunga, dimezzando i tempi per alcune stanzine, si potrebbere aggiungere qualcosa in piu...
> non so se a livello di tutorial si possano fare, ma cmq faccio qualche esempio stupido
> - fare un page
> - sloggare col doppioclick su un letto
> - morire e usare il

Più che lungo é ripetitivo, risulta noioso ma forse era anche dovuto al gatering da 1 la volta...
Parlo di quello da worker, quello da war é abbastanza veloce

**Comment by morpheus8888** [comment]
il problema è che come hai capito la logica è nel gate, ci sono dinamiche che è molto difficile far entrare in un teletrasporto. Comunque tu annota tutto, quello che si può fare si fa.
