### ISSUE TITLE
Fix a cove

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#263]
Nella region cove sul .caps ogni volta che abbassano una skill gli restituisce gli exp point, mettilo sullo stesso controllo dello young, la differenza che qui vale sempre.

L'obiettivo è che non possono trashare l'exp, qualsiasi cosa fanno la total exp fra spesa e non spesa deve rimanere sempre uguale, qualsiasi trasformazione fanno, per evitare abusi e rimangono più tempo li.

**Comment by gmocciaro** [comment]
done
