### ISSUE TITLE
Bug Raccolta Mining

### ISSUE THREAD

**Issue by DarkanSheZhar** [uomars/UOMars#264]
Mentre facevo il tutorial del mining si è rotta la picca
non posso più raccogliere nulla, dice che sto già raccogliendo da quella miniera
non posso raccogliere neanche la sabbia
anche dopo aver sloggato resta il bug
anche dopo essere morto resta il bug

**Comment by morpheus8888** [comment]
aggiungo che mentre minava si è rotto la picca, qualche condizione della rottura non ha interrotto l'azione

**Comment by gmocciaro** [comment]
non riesco a replicarli, se riuscite a spiegarmi passo passo o magari mandate un video vedo che succede

**Comment by morpheus8888** [comment]
@gmocciaro il problema è negli strumenti base, manca il controllo li

**Comment by gmocciaro** [comment]
dovrebbe essere fixato, fatemi sapere
