### ISSUE TITLE
Diciamo NO alle pietre che parlano (nuovo NPC HELPER al posto delle stone)

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#266]
Sarebbe bello avere un NPC al posto delle Stone perche' ste pietre che parlano sono una roba oscena ♥

L'NPC HELPER deve essere 1 e standard in modo che le venga riconosciuto subito 

Mi piacerebbe avesse le seguenti caratteristiche:

- Doppia lingua
- dalle Props la possibilità di regolare il tempo di speech
- Tipo Vecchie STONE (doppioclick sull'npc e aggiungi il testo)
- Parla solo alla persona interessata (entro 5 tile) oppure a 10 piccola frase per attivare l'interesse e se si avvicina testo completo
        Esempio: 
        10 tile - Hey Tu! Vieni Qui!
        5 tile - Testo completo

**Comment by gmocciaro** [comment]
deve fare pure una capriola?

In ogni caso, riporto il problema di base: I testi inseribili da props e/o comando sono estremamente piccoli, per inserire del testo di una lunghezza utile bisogna utilizzare i file (come ho fatto con https://github.com/uomars/UOMars/issues/142).

Se a voi sta bene avere un testo piccolo al doppioclick (tipo 100 caratteri) posso farlo senza problemi, se dovete mettere testi più lunghi allora si deve fare il metodo su file.

per il testo che "dice" non ci sono problemi, anche sul fatto dei tile e del fatto che lo dice ad una sola persona (da testare)

**Comment by daffy55** [comment]
> deve fare pure una capriola?
> 
> In ogni caso, riporto il problema di base: I testi inseribili da props e/o comando sono estremamente piccoli, per inserire del testo di una lunghezza utile bisogna utilizzare i file (come ho fatto con #142).
> 
> Se a voi sta bene avere un testo piccolo al doppioclick (tipo 100 caratteri) posso farlo senza problemi, se dovete mettere testi più lunghi allora si deve fare il metodo su file.
> 
> per il testo che "dice" non ci sono problemi, anche sul fatto dei tile e del fatto che lo dice ad una sola persona (da testare)

Per quell'NPC bastano testi piccoli, semplici TIP per indirizzare i pg o per spiegare dove si trovano

**Comment by gmocciaro** [comment]
quindi la frase che esce al doppio click è la stessa che ti dice quando sei a 5 tiles?

**Comment by daffy55** [comment]
Non so se si puo' fare:

TITOLO: frase a 10 tile
TESTO: frase a 5 tile

Come la vedi? E' fattibile?

**Comment by gmocciaro** [comment]
![image](https://user-images.githubusercontent.com/12816659/133149510-fb69053a-dc6e-4f87-ae96-55bdf8acb50e.png)

Alloraaaa:

- **Delay**: ogni quando deve inviare il messaggio (il messaggio lo invia SOLO al player interessato e non a tutti, di base 10 secondi)
- ****:
- - ****:
- - ****:

**Comment by gmocciaro** [comment]
@daffy55 poi mi dici come devo vestirlo

**Comment by gmocciaro** [comment]
il pupino spawna random tra maschio e femmina con un nome random, tutto cambiabile se vuoi

**Comment by gmocciaro** [comment]
ah ovviamente `.add UoMarsMessenger`

**Comment by kentar91** [comment]
ottimo!

**Comment by kentar91** [comment]
> @daffy55 poi mi dici come devo vestirlo

se volete lo vesto io da spawn

**Comment by Darksuitjer** [comment]
@gmocciaro sei un mostro! :D

**Comment by gmocciaro** [comment]
> @gmocciaro sei un mostro! :D

no dai non sono così brutto

> > @daffy55 poi mi dici come devo vestirlo
> 
> se volete lo vesto io da spawn

per me è uguale, o faccio io o fate voi (il problema è che se dobbiamo usarlo una tantum esce nudo come un verme)

**Comment by daffy55** [comment]
Gugliè, sei stato un grande, oggi lo provo.
Almeno togliamo le stone!

**Comment by kentar91** [comment]
> per me è uguale, o faccio io o fate voi (il problema è che se dobbiamo usarlo una tantum esce nudo come un verme)
magari se donna  facciamo qualche soldo in real... XD

**Comment by gmocciaro** [comment]
chiudo per ora, se avete necessità riaprite

**Comment by daffy55** [comment]
uomarsmessenger2 ti permette di scrivere 3 frasi e quindi ti parla, perché prima dice uno, poi l'altro, etc...

**Comment by daffy55** [comment]
verificare il perché quando 2 persone si avvicinano al mob esso parli solo alla prima che arriva in range
