### ISSUE TITLE
aggiungere cavalli 6 livello (premium)

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#268]
aggiunti i seguenti cavalli
ForestDragon
Stallion
GiantLion
ArmoredHorse
Gryphon
HellMustang
Rexaurus
FlyingWyvern
ArmoredWolf
Phoenix

troverete tutte le info sul file solito

**Comment by gmocciaro** [comment]
ma se ci bruciamo tutte le grafiche con il premium che rimane nel gioco? cmq ok

**Comment by kentar91** [comment]
come suggeriva @Ale1991 qualche tempo fa, potremmo fare che ogni mese escono 5 cavalcature diverse del premium e ogni mese non sono mai le stesse...

**Comment by Ale1991** [comment]
> come suggeriva @Ale1991 qualche tempo fa, potremmo fare che ogni mese escono 5 cavalcature diverse del premium e ogni mese non sono mai le stesse...

io in realta' dicevo altro.... ovvero: suddividere le cavalcature del premium (che sono tantissime!) in fasce di anzianita' (ad esempio 6 mesi ogni fascia) e determinate cavalcature saranno accessibili solo a chi avra' raggiunto quella fascia, permettendogli cosi di ampliare la scelta e al tempo stesso non dare tutto a tutti.

Inoltre l'ambizione di avere qualcosa e' determinata dalla rarita'. Io non darei tutto a tutti e alcune grafiche me le terrei per cose piu' uniche che rare

**Comment by gmocciaro** [comment]
cmq secondo me alla fine tutti sceglieranno la stessa (la più figa) o solo un paio e avremo 60 grafiche bruciate e basta

**Comment by Ale1991** [comment]
> cmq secondo me alla fine tutti sceglieranno la stessa (la più figa) o solo un paio e avremo 60 grafiche bruciate e basta

Concordo. Per me al premium ce ne andrebbero massimo 10 sfruttando i colori eterei sulle mount normali e a scalare una ogni x mesi di anzianità. Tutto il resto nel gioco. 
Piuttosto con il premium andrei ad aiutare quei player che hanno poco tempo per giocare e vorrebbero il minimo indispensabile per fraggare come mi hanno già chiesto in tanti

**Comment by lyon1235** [comment]
> > cmq secondo me alla fine tutti sceglieranno la stessa (la più figa) o solo un paio e avremo 60 grafiche bruciate e basta
> 
> Concordo. Per me al premium ce ne andrebbero massimo 10 sfruttando i colori eterei sulle mount normali e a scalare una ogni x mesi di anzianità. Tutto il resto nel gioco.
> Piuttosto con il premium andrei ad aiutare quei player che hanno poco tempo per giocare e vorrebbero il minimo indispensabile per fraggare come mi hanno già chiesto in tanti

Concordo

**Comment by kentar91** [comment]
> > come suggeriva @Ale1991 qualche tempo fa, potremmo fare che ogni mese escono 5 cavalcature diverse del premium e ogni mese non sono mai le stesse...
> 
> io in realta' dicevo altro.... ovvero: suddividere le cavalcature del premium (che sono tantissime!) in fasce di anzianita' (ad esempio 6 mesi ogni fascia) e determinate cavalcature saranno accessibili solo a chi avra' raggiunto quella fascia, permettendogli cosi di ampliare la scelta e al tempo stesso non dare tutto a tutti.
> 
> Inoltre l'ambizione di avere qualcosa e' determinata dalla rarita'. Io non darei tutto a tutti e alcune grafiche me le terrei per cose piu' uniche che rare
> 
> ps: per ogni nome che ho letto ho collegato subito alla grafica. Ottima scelta

mi piace molto così

**Comment by kentar91** [comment]
> > cmq secondo me alla fine tutti sceglieranno la stessa (la più figa) o solo un paio e avremo 60 grafiche bruciate e basta
> 
> Concordo. Per me al premium ce ne andrebbero massimo 10 sfruttando i colori eterei sulle mount normali e a scalare una ogni x mesi di anzianità. Tutto il resto nel gioco.
> Piuttosto con il premium andrei ad aiutare quei player che hanno poco tempo per giocare e vorrebbero il minimo indispensabile per fraggare come mi hanno già chiesto in tanti

avremo + di 30 nuove mount!
bisognerà capire livelli e rifare tutta la logica dei livelli...
sempre "ipotizzando" potremo fare che queste mount sono spawnate a mano, completamente a caso o per eventi/quest
ovviamente al momento non è fondamentale, però parliamone così troviamo la soluzione più fica 💋

**Comment by morpheus8888** [comment]
per me il premium potete reworkarlo come meglio volete, spiego brevemente quale era la mia visione originaria.
Le cavalcature che ho messo nel premium sono tutte quelle strambe, cioè qualsiasi cosa non rientrava nella dinamica classica di cavallo, ostard, llama etc.. l'ho messo nel premium.
Con le nuove aggiunte ora sono più quelli strambi che quelli normali, quindi l'idea originaria se ne è andata un po' a puttane.
Dato che queste grafiche sono molto belle io li farei tutti come cavallo di quinto, rendendoli unici in tutto lo shard. Quelli meno belli li possiamo aggiungere alla lista di quarto o terzo. 
Per il resto concordo con il premium che aiuta chi ha poco tempo, al momento in parte è già così con la casa gratis, si deve pensare a qualcosa che va in quella direzione.

**Comment by gmocciaro** [comment]
se li fai come cavalli di quinto non li usa nessuno e non si vedranno mai nello shard

**Comment by morpheus8888** [comment]
io parto dal presupposto che questa è roba che non si vedrà mai in giro, ma che va ai collezionisti. Quindi che vive come pixel che qualcuno usa in zona safe o ai matrimoni, se invece volete che vengano usati per me non ci sono problemi, ma mi sembrano grafiche troppo invadenti.

**Comment by Ale1991** [comment]
> io parto dal presupposto che questa è roba che non si vedrà mai in giro, ma che va ai collezionisti. Quindi che vive come pixel che qualcuno usa in zona safe o ai matrimoni, se invece volete che vengano usati per me non ci sono problemi, ma mi sembrano grafiche troppo invadenti.

Concordo. Comunque alcune cavalcature possono essere assegnate come drop unico (rarissimo) di un boss di fine dungeon. Ho gia' provato questa meccanica ed e mi era piaciuta. Ci conviene, appena siamo tutti, farci degli schemi per capire  quanti e quali tipi di premi fare con dinamiche diverse. Tanto dobbiamo discutere sul loot system e credo possano esserne considerate un sottoinsieme

**Comment by gmocciaro** [comment]
quindi che si fa? chiudo?
