### ISSUE TITLE
bug skill cap

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#270]
non so se te l hanno detto

se fai .reset e poi compri il deed dell'exp hai 800 punti spendibili 
![image](https://user-images.githubusercontent.com/83588629/133154446-3d578b1e-7c87-4aa4-a615-524554bd6648.png)

però sul cap  sono 700 skill assegnabili (sx) mentre avaible (dx) 800
![image](https://user-images.githubusercontent.com/83588629/133154471-98b8df9e-f816-4a0e-9297-105116532feb.png)

**Comment by kentar91** [comment]
guardando ancora meglio non penso sia un problema del nuovo caps, ma proprio del sistema acquisizione punti che mette 100 di base al reset e ne aggiunge subito quella cifra anomala.
non so se è da considerare un bug o meno.
![image](https://user-images.githubusercontent.com/83588629/133154832-456d9b50-af0c-4d00-a6aa-91196a2c4d10.png)

![image](https://user-images.githubusercontent.com/83588629/133154781-c0fa1262-ee6c-4b38-8a8e-1e9695526525.png)

**Comment by gmocciaro** [comment]
ma il fatto che li hai assegnabili non vuol dire che devi spenderli, puoi anche scambiarli con oggetti (.rewards). anche se hai 800/800 skill e 230/230 stats comunque guadagni punti e li accumuli

ps: non so se è normale il reset ti lasci 100 punti, credo di si perchè è il valore di punti che hai all'inizio come pg "niubbo", il fatto che arrivi ad 800 è perchè i deed sono da 700, magari si può abbassare a 600?

**Comment by kentar91** [comment]
nono, tanto sono deed per test.
il fatto che "sfori" tramite ticket va bene in questa fase, forse da valutare per l'apertura, anche perchè di base si blocca a 700.... boh... vediamo

**Comment by morpheus8888** [comment]
il reset per forza ti deve fare 100 punti skill (come alla nascita) altrimenti non puoi ripartire, il fatto che noi diamo 700 punti, è più una reward psicologica, realmente per fare un full skill te ne servono 600
