### ISSUE TITLE
equip "base" orchi cove a meridian

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#272]
assegnare equip dell'ex dungeon di cove (base?) anche a meridian e campo orchi cove

da valutare:
volendo sarebbe fico se l'equip alla fine della zona di "ricongiungimento" sparisse, in modo da dover usare dell'equip normale
esattamente da qui 
![image](https://user-images.githubusercontent.com/83588629/133161412-5a82745a-fa54-4256-8964-d4207d1957b0.png)
così si potrebbe creare un "cancello" per questo mini spot finale dove chiunque può venirlo a fare

tanto il corridoio che arriva al "cancello" è la zona 550-700

@daffy55 @Giboud @morpheus8888

**Comment by daffy55** [comment]
Favorevole, per il cancello te lo creo in statico, ti faccio una sorta di ingresso, senza le porte, poi se vogliamo le mettiamo se no lasciamo aperto.

**Comment by morpheus8888** [comment]
cove e meridian ora forniscono l'equipaggiamento ad ogni cambio di skill
