### ISSUE TITLE
Golden Scrap con tinkering (bug)

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#277]
Che sia 1 punto tinkering, 10, 90,95 o 100, ho provato a convertire 18911 scrap perché volevo vedere quanti soldi dava con 100 tinkering, ma da solo 1 gp

**Comment by kentar91** [comment]
Avevi anche il talismano o ti sei settato worker da GM?

**Comment by Darksuitjer** [comment]
Niente talismano ho provato sia col gm che è settato worker che con il Fencer settato worker, ma nessuno dei 2 aveva il talismano

**Comment by morpheus8888** [comment]
senza talismano si bugga tutto, segui la procedura standard, ovvero fai .reset, poi diventa worker ad una stone e poi prova (senza gm). Se bugga ancora scrivilo

**Comment by kentar91** [comment]
ho fatto delle prove con lily.
come diceva morph il "bug" è causato dal talismano.
passo e chiudo
