### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#278]
E' un paio di giorni che impiega un ora e mezza nell'aprirlo e altrettanto tempo ci vuole dal momento in cui si preme play perché apra il client.
Che succede??? @Ale1991

**Comment by morpheus8888** [comment]
andando a intuito, se il launcher non riesce a collegarsi con il server ci mette tempo ad aprirsi

**Comment by Ale1991** [comment]
chiudo erano problemi di connessione con il server
