### ISSUE TITLE
Non sale piu a cavallo (bug)

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#279]
ho provato a prendere una pickaxe per vedere se mi faceva minare col fencer e non essendo worker...
Mi dice che non posso minare perche non sono un lavoratore, ma allo stesso tempo se provo a salire sul cavallo mi dice:
You are already performing an action and cannot mount!

**Comment by Darksuitjer** [comment]
mentre facevo delle prove hanno riavviato per patchare, e ora non lo fa piu... 
non posso minare perche non sono un worker, ma sale normalmente a cavallo

**Comment by gmocciaro** [comment]
probabilmente è stato risolto con un altro bug:
https://github.com/uomars/UOMars/issues/264

questo lo chiudo
