### ISSUE TITLE
Creare gump preferenza lingua

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#280]
creare un gump che chiede quale lingua preferisce un player, il gump rimarrà aperto fino a quando l'utente non sceglie una lingua

**Comment by morpheus8888** [comment]
si può fare sia che rimanere aperto se non sceglie la lingua o che ad ogni login gli ricompare se l'ha chiuso senza scegliere, indifferente, scegli tu come rompere le palle

**Comment by gmocciaro** [comment]
![image](https://user-images.githubusercontent.com/12816659/133890382-883e96ee-bedb-415e-9c0c-7bc96dbf0235.png)

fatto

**Comment by morpheus8888** [comment]
grande
