### ISSUE TITLE
creare comando per l'elenco dei balance dei vari player

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#281]
creare un comando per genrerare una lista, ordinata per balance decrscente, con l'elenco delle "persone più ricche" per controllare la situazione dello shard

**Comment by lyon1235** [comment]
Si potrebbe fare lo stesso per le kill, silver Coin ecc

**Comment by kentar91** [comment]
lato GM o lato player?

**Comment by lyon1235** [comment]
Lato player … sarebbe bello mettere tutto in mostra così da creare anche un po’ di sana competitività

**Comment by gmocciaro** [comment]
no ovviamente lato gm

**Comment by kentar91** [comment]
> Lato player … sarebbe bello mettere tutto in mostra così da creare anche un po’ di sana competitività 

Se vuoi per 10 euro al mese ti mando l estratto

**Comment by gmocciaro** [comment]
> > Lato player … sarebbe bello mettere tutto in mostra così da creare anche un po’ di sana competitività
> 
> Se vuoi per 10 euro al mese ti mando l estratto

vediamo se ti banno prima che andiamo online

**Comment by kentar91** [comment]
> > > Lato player … sarebbe bello mettere tutto in mostra così da creare anche un po’ di sana competitività
> > 
> > Se vuoi per 10 euro al mese ti mando l estratto
> 
> vediamo se ti banno prima che andiamo online

Hai ragione, dovevo chiedere di più

**Comment by gmocciaro** [comment]
done
