### ISSUE TITLE
Colore pozioni crafting system

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#282]
ti scrivo i bug mano a mano che le provo
inizio dal crafting
graficamente sono tutte sbagliate.

![image](https://user-images.githubusercontent.com/83588629/133657064-cb4d0ed9-bedb-4852-90a7-57793bd12685.png)
![image](https://user-images.githubusercontent.com/83588629/133657102-974dbf6e-92bc-4cb4-867f-f0300a82cd44.png)
devono essere
HealPotion : itemid: 3852 colore: 0
RefreshPotion itemid: 3851 colore: 0
ManaPotion itemid: 3846 colore: 0
CurePotion itemid: 3847 colore: 0
StrengthPotion itemid: 3849 colore: 0
AgilityPotion itemid: 3848 colore: 0
IntelligencePotion itemid: 3846 colore: 1757
ExplosionPotion itemid: 3853 colore: 0
CarrotPotion itemid: 3849 colore: 0
ConflagrationPotion itemid: 3846 colore: 0
GasPotion itemid: 3846 colore: 2818
ParalyzePotion itemid: 3850 colore: 2819
SonicBoomPotion itemid: 3846 colore: 1161
AttunementPotion itemid: 3846 colore: 1763
SmokePotion itemid: 3850 colore: 2835

quando inserisci una pozza AttunementPotion all'interno del keg questo non si colora e non specifica il nome della pozza all'interno
![image](https://user-images.githubusercontent.com/83588629/133659006-2c35b2a9-6459-4350-b6d2-eb4f760bb8a5.png)

_Originally posted by @kentar91 in https://github.com/uomars/UOMars/discussions/248#discussioncomment-1343517_

**Comment by morpheus8888** [comment]
attunement lo fixo subito io

**Comment by gmocciaro** [comment]
io posso solo cambiare i colori delle pozze, gli itemID il gump le prende dalla prop ItemID della classe dell'oggetto

**Comment by gmocciaro** [comment]
fixed
