### ISSUE TITLE
bug stats nel caps

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#287]
quando aumento la stat di intelligence aumenta anche alchemy senza contare ne i punti stat disponibili ne quelli skill

**Comment by kentar91** [comment]
https://user-images.githubusercontent.com/83588629/134572726-330917c6-914e-41e2-b315-f00cf19d301b.mp4

**Comment by kentar91** [comment]
stessa cosa vale anche con le altre stat

**Comment by gmocciaro** [comment]
quindi qualsiasi stat alzi, alza dello stesso valore alchemy?

**Comment by kentar91** [comment]
> quindi qualsiasi stat alzi, alza dello stesso valore alchemy?

Si

**Comment by gmocciaro** [comment]
fixed
