### ISSUE TITLE
bug condition teleporter

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#296]
![image](https://user-images.githubusercontent.com/83588629/135352190-f9f3d78b-7ae9-4003-a7d2-30bf8f95c9cd.png)
quando sei pk e provi ad entrare in  un gate dove c'è la condizione "deny pk" ti dà questo messaggio

dovrebbe dire, così come per order e chaos con condizione deny, 
![image](https://user-images.githubusercontent.com/83588629/135352304-2e798860-2a94-4fe8-96b8-fe9bcebd1865.png)

**Comment by morpheus8888** [comment]
nel condition teleporter non esiste quella frase, quindi non so come fixarlo

**Comment by Ale1991** [comment]
Quello e' un controllo della region che fa entrare i pk solo se una porta e' stata distrutta non e' il teleporter che evita l'ingresso e funziona anche per order e chaos se sono stati bannati (se il sindaco neutral ha deciso di non farli entrare)

**Comment by kentar91** [comment]
ah ok, ora lo so
grazie
