### ISSUE TITLE
ridurre range comando bank -lato player

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#298]
attualmente se scrivi bank con un player, nei pressi di un banchiere, questa si aprirà a 12 tile di distanza.

se invece fai doppio click sul banchiere la banca si aprirà a 4 tile di distanza.

uniformare tutto a 4 tile

**Comment by Darksuitjer** [comment]
beh se urli è normale che il banchiere ti senta da piu lontano...
solo perché non esiste il telefonino.. altrimenti con una chiamata al banchiere, e si potrebbe aprire anche in mezzo al mare!!! :D

**Comment by lyon1235** [comment]
A che pro questa cosa ?

**Comment by kentar91** [comment]
Esempio pratico.
Se scrivi bank al di fuori della banca questa si apre. Quindi la banca è inutile xD

**Comment by morpheus8888** [comment]
fatto
