### ISSUE TITLE
runebook sul .vs

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#299]
i runebook  hanno una variable chiamata islocked, quando è true non si devono mettere sul .vs

**Comment by gmocciaro** [comment]
quindi sono vendibili dal vendor ma non dai .vs?

**Comment by Ale1991** [comment]
> quindi sono vendibili dal vendor ma non dai .vs?

no va bene anche non farli caricare proprio nel vendor se sono lockati. 
Praticamente i runebook essendo lootabili, alla morte si locka (quindi non puo' essere letto se non dal proprietario che lo ha lockato con la morte). 
Un runebook lootabile implica i seguenti problemi che hanno come conseguenza il non utilizzo (nel senso di portarselo dietro): 
1) Per rifarlo devi rimarcare le rune una alla volta
2) Se te lo lootano sapevano tutti i punti in cui ti recalli e possono aspettarti direttamente li

Il punto 1) lo abbiamo risolto con la Pen of Wisdom (un oggetto facilmente reperibile che permette di duplicare i runebook)
Il punto 2) lo risolviamo con il meccanismo di lock.

La soluzione 2) porta ad un ulteriore problema. Scenario:
Mi faccio 10 runebok, mi locko facendomi uccidere da un amico (i runebook si lockano), e li faccio mettere (anche da lui) sul suo vendor per porterli comprare nel vendorsearch. Questo permetterebbe di avere sul vs dei runebook apribili solo da colui che li ha lockati quindi alla fine li comprera' solo lui. Ma quelli che sfrutteranno questo meccanismo sara' come se avranno sempre un runebook dietro, che e' il motivo per cui abbiamo deciso di non fare piu' i runebook blessed.

Quindi ricapitolando: un runebook locked non deve poter essere caricato sul vendorsearch (e' sufficiente il vendorsearch ma se non lo fai caricare proprio sul vendor e' uguale, anche perche' non avrebbe senso)

**Comment by morpheus8888** [comment]
per estensione meglio toglierli dal vendor, si.

**Comment by gmocciaro** [comment]
fatto, tolto anche dal .auc se ho fatto male riaprite

**Comment by morpheus8888** [comment]
sul .auc lascialo se chi lo mette in vendita non ha modo di fare il trucchetto che si può fare sul .vs

**Comment by gmocciaro** [comment]
> sul .auc lascialo se chi lo mette in vendita non ha modo di fare il trucchetto che si può fare sul .vs

la stessa logica spiegata da alessio è replicabile nel .auc (con l'instant win ti arriva subito), però se vuoi lo faccio caricare li

**Comment by gmocciaro** [comment]
ri-attivato sul .auc
