### ISSUE TITLE
rischio sul crafting

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#300]
quando un player ha workerinvulnerable false, si trova fuori da un avamposto o una città, la ricetta gli costa meno di X in base al rischio, cosa che gli compare scritta nel gump di crafting. La formula penso si possa riusare la vecchia riadattandola.

**Comment by gmocciaro** [comment]
da discutere meglio

**Comment by morpheus8888** [comment]
@gmocciaro quando vuoi

**Comment by Darksuitjer** [comment]
> quando un player ha workerinvulnerable false, si trova fuori da un avamposto o una città, la ricetta gli costa meno di X in base al rischio, cosa che gli compare scritta nel gump di crafting. La formula penso si possa riusare la vecchia riadattandola.

Non ricordo se l invul si possa settare ovunque... 
se si dovesse fare una cosa a livello di rischio, se non è già così, bisogna mettere che non ci si possa settare invul se con qualcosa di recently looted o crafted
