### ISSUE TITLE
context menu su ogni item

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#301]
context menu su ogni item per il bible, fare in modo che il single click su un oggetto permetta la ricerca nel bible immediata. Fare in modo che noi admin abbiamo un allert quando tale ricerca non ha dato esiti (quindi dobbiamo aggiungere) e avere una sorta di statistica per capire quali sono i più cercati così da investire maggiormente per migliorare tali articoli.

**Comment by gmocciaro** [comment]
> noi admin abbiamo un allert quando tale ricerca non ha dato esiti (quindi dobbiamo aggiungere) e avere una sorta di statistica per capire quali sono i più cercati così da investire maggiormente per migliorare tali articoli.

seh

**Comment by gmocciaro** [comment]
> noi admin abbiamo un allert quando tale ricerca non ha dato esiti (quindi dobbiamo aggiungere) e avere una sorta di statistica per capire quali sono i più cercati così da investire maggiormente per migliorare tali articoli.

seh
