### ISSUE TITLE
verificare il client al primo log

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#307]
Buongiorno
capita, non sempre, che quando logghi un pg con il nuovo client, questo la prima volta crasha
come posso aiutarti ad estrarre eventuali log?

**Comment by Darksuitjer** [comment]
è quello che dicevo a @giga487 .. se lo insulti su whatzup, il client lo sente, e per ripicca non ti fa loggare! :D

**Comment by giga487** [comment]
Provo a capire di cosa parli, cerco di immedesimarmi in un client.
