### ISSUE TITLE
grafica dungeon moongate

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#313]
![image](https://user-images.githubusercontent.com/83588629/136699634-8b71c61a-3af4-46ff-b6df-10e447dfb224.png)
ti propongo di modificare la grafica di questo tipo di gate @gmocciaro

**Comment by gmocciaro** [comment]
![image](https://user-images.githubusercontent.com/12816659/137619226-c71a23ad-fbf4-4292-807a-281789f2570a.png)

**Comment by morpheus8888** [comment]
@daffy55 sa   @kentar91

**Comment by daffy55** [comment]
> @daffy55 sa @kentar91

@morpheus8888  sei utile come il 2 di coppe con briscola a bastoni!

**Comment by daffy55** [comment]
@gmocciaro riscrivilo mantenendo anche l'ordine (fixa i nomi)

Shade [1P] [Very Easy] - 2948 1054 0
Egypt [1P] [Easy] - 2886 3154 0
Lizard [1P] [Easy] - 3940 2990 0
Elemental [1P] [Medium] - 2815 1148 0
The Farm [1P] [Hard] - 2155 1544 0
Cemetery [2P] [Easy] - 2987 822 0
Orc's Camp [2P] Medium] - 4030 1606 0
Centaury [2P] [Hard] - 2121 3003 0
Phantom Castle [3P] [Medium] - 3713 2014 0
Nigmar Cove [3P] [Hard] - 3021 2099 0
Hytlot [4P] [Hard] - 3544 1632 0

**Comment by gmocciaro** [comment]
questi immagino siano di felucca, ce ne stavano alcuni anche di ilshenar?

**Comment by kentar91** [comment]
Si sono felucca
Ilshenar c'è solo la star room

**Comment by gmocciaro** [comment]
![image](https://user-images.githubusercontent.com/12816659/140608573-05fc981e-0375-42a6-ab74-0f48483f1d5b.png)

spero sia la versione definitiva

**Comment by daffy55** [comment]
> ![image](https://user-images.githubusercontent.com/12816659/140608573-05fc981e-0375-42a6-ab74-0f48483f1d5b.png)
> 
> spero sia la versione definitiva

dubito, conoscendo Guido

**Comment by kentar91** [comment]
Non sarà mai la versione definitiva hahahah

**Comment by kentar91** [comment]
Non sarà mai la versione definitiva hahahah
