### ISSUE TITLE
rework avamposti

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#325]
blocco porte per 24 ore costo 10k di silver
il blocco porte non impedisce la conquista della sedia (disgiuntare protezione delle porte dalla protezione della sedia)
durante l'evento di conquista il blocco delle porte svanisce, o meglio viene disabilitato momentaneamente e poi riprende se c'è ancora tempo residuo.
c'è la possibilità di bloccare la conquista della sedia per 50k  (questo deve essere dichiarato sul gump in modo distinto)

Tutti gli avamposti scattano ogni settimana allo stesso orario allo stesso giorno (martedì), questo se non sbaglio lo regoliamo poi noi dal game.

Gli avamposti sono 5

(mensilmente chi vince la war di fazione prende 50k silver)

**Comment by morpheus8888** [comment]
@gmocciaro questo si capisce o ne dobbiamo parla a voce?

**Comment by Ale1991** [comment]
teleport anche per gli alleati

**Comment by gmocciaro** [comment]
Finito, sarebbe da testare tutto il nuovo sistema
