### ISSUE TITLE
Evento Volcano

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#332]
https://github.com/uomars/UOMars/discussions/323

**Comment by gmocciaro** [comment]
Se crasha il server come mi devo comportare con le bandiere in mano? Non viene triggerato exit region o logout

**Comment by morpheus8888** [comment]
ti riferisci al fatto se chi rilogga rilogga ad evento finito con la bandiera in mano?

**Comment by gmocciaro** [comment]
si

**Comment by gmocciaro** [comment]
possibile fix:

in caso di crash del server, al re-log, se ha la bandiera in mano:
- se l'evento è in running e il player è dentro la region, non faccio azioni
- se una di quelle due condizioni è falsa, cancello l'item

**Comment by morpheus8888** [comment]
tu hai il riferimento per l'oggetto giusto? al login se l'evento è running la bandiera viene tolta dalla mano del player e fatta cadere esattamente nello stesso punto dove era il player al momento del crash, se il server restarta a fine evento si cancella e i soldi vengono rimessi per il prossimo evento

**Comment by gmocciaro** [comment]
fatto tutto tranne i premi, sarebbe bello testarto

**Comment by Darksuitjer** [comment]
devo capire se 50% hp e' troppo poco o no.. dopo 2 cast droppi gia la bandiera, sto pensando all'evento di massa, ma sarebbe da vedere se meglio 50% o tipo 80% di danno prima di dropparla.. ci penso...
cmq oltre le offensive, disabiliterei anche le magie ad area tipo quake per i pk li dentro
ultima cosa, visto che dovrebbe essere evento safe, e quindi da quello che ho visto ieri non si possono lootare nemici (maledetto kentar t'è andata bene!) anche le cavalcature durante l'evento e all'interno di quell'area dovrebbero essere invulnerabili o cmq non attaccabili

**Comment by gmocciaro** [comment]
stiamo dando i danni alla bandiera al posto di levare le magie offensive. Abbiamo tolto i danni ai pet (tutti, non solo le mount) dei player. Per le soglie di danno pensaci e fammi sapere

**Comment by Ale1991** [comment]
> devo capire se 50% hp e' troppo poco o no.. dopo 2 cast droppi gia la bandiera, sto pensando all'evento di massa, ma sarebbe da vedere se meglio 50% o tipo 80% di danno prima di dropparla.. ci penso... cmq oltre le offensive, disabiliterei anche le magie ad area tipo quake per i pk li dentro ultima cosa, visto che dovrebbe essere evento safe, e quindi da quello che ho visto ieri non si possono lootare nemici (maledetto kentar t'è andata bene!) anche le cavalcature durante l'evento e all'interno di quell'area dovrebbero essere invulnerabili o cmq non attaccabili

disabilitate le spell ad area meteor swarm e chain lightning durante l'evento. L'earthquake è castabile da tutti ma non fa danno (utile per dispellare muri aoe)
