### ISSUE TITLE
bug server

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#333]
ciao
@gmocciaro ho due problemi
![image](https://user-images.githubusercontent.com/83588629/139540090-4c757293-6537-4b1f-8287-5eb1fd05db1b.png)
tftd e vol1 sono comandi di tipo player

1. tftd fa quella cosa che sai tu, che non posso dire perchè è un GIT pubblico.
spostalo su un access level più alto...
2. vol1 fa crashare lo shard

**Comment by gmocciaro** [comment]
vol1 è un comando mio che uso per testare, poi sarà tolto
tftd onestamente manco so che sia, però spostarlo ad un livello più alto non ci sono problemi

**Comment by kentar91** [comment]
> vol1 è un comando mio che uso per testare, poi sarà tolto tftd onestamente manco so che sia, però spostarlo ad un livello più alto non ci sono problemi

tftd serve per summonare gli oggetti della tua quest

**Comment by Ale1991** [comment]
fixato io:
- vol1 spostato a Owner
- tftd spostato a GameMaster
