### ISSUE TITLE
bug recallrune

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#336]
i recall e i gate non consumano reagenti.
se usi un recallbook non consuma cariche sia per recall che gate

**Comment by kentar91** [comment]
mi spiego meglio riguardo il recallbook

da qui fa il check delle cariche
![image](https://user-images.githubusercontent.com/83588629/139580646-4c171069-4951-4714-92b4-5563de832dbc.png)


da qui no
![image](https://user-images.githubusercontent.com/83588629/139580663-f38590e5-0370-4078-9ad8-2fa371fd768a.png)

**Comment by morpheus8888** [comment]
se sei young è giusto, se no è un bug

**Comment by morpheus8888** [comment]
i runebook non consumano mai reagenti e arcanegem? non ho capito. @kentar91 

sul travelbook invece funziona tutto bene?

**Comment by morpheus8888** [comment]
ti spiego il comportamento del runebook:
- se clicchi da fuori usa le cariche
- se clicchi da dentro usi reagenti e arcanegem

QUal è il problema? da codice non vedo niente di strano o mi stai dicendo che non consuma i reagenti quando dovrebbe farlo?

**Comment by morpheus8888** [comment]
ok trovato il problema, recall e gate non consumavano reagenti a prescindere, ora è fixato

**Comment by morpheus8888** [comment]
@Ale1991  riapro perché non riesco a risolvere, serve aLESSIO

**Comment by morpheus8888** [comment]
@kentar91 in teoria alessio ha risolto, appena lo testi lo puoi chiudere

**Comment by Ale1991** [comment]
- fixato recall e gate (adesso consumano reagenti)
- il recall e il gate tramite spell (cliccando i pallini a sinistra delle parole Recall e Gate Travel) faranno gli opportuni check su skill e armor
- fixato il recall tramite runebook che utilizza le cariche (e' possibile farlo anche in plate e senza skill)

Reminder: 
- controllare (eventualmente fixare) il recall da runebook con cariche tramite il pallino presente nella pagina della runa (a sinistra del NomeRuna)
- da fixare il controllo di recal e gate da dungeon verso fuori (attualmente non lo fa fare)

**Comment by morpheus8888** [comment]
da controllare anche se quella variabile che hai settato a true, dopo torna da sola a false, mi è venuto il dubbio leggendo

**Comment by Ale1991** [comment]
è una variabile di istanza (dell'oggetto, non statica)

**Comment by Ale1991** [comment]
> da controllare anche se quella variabile che hai settato a true, dopo torna da sola a false, mi è venuto il dubbio leggendo

è una variabile di istanza (dell'oggetto, non statica)

**Comment by Ale1991** [comment]
fixed.
Riaprite se ci sono nuovi problemi
