### ISSUE TITLE
cosa non trovo nei tavoli da lavoro

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#337]
mancano nei tavoli da lavoro le rune normali e i runebook

**Comment by gmocciaro** [comment]
se mancano cose da craftare, ditemi chi le crafta, in quale categorie e con quali risorse

**Comment by kentar91** [comment]
@daffy55 @Giboud help us!

**Comment by gmocciaro** [comment]
![image](https://user-images.githubusercontent.com/12816659/140608614-2e1e05d6-9864-4090-b89e-44a453a5e3f5.png)

**Comment by kentar91** [comment]
tinker recall rune
tailor runebook, come gli spellbook

**Comment by gmocciaro** [comment]
si ma la ricetta dovete darmi

**Comment by Ale1991** [comment]
fatto
