### ISSUE TITLE
bug cove region-attacco

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#339]
anche da young player se attacco a cove i mob vengo teletrasportato nella zona centrale.

**Comment by morpheus8888** [comment]
ti caccia fuori in base alle skill, non allo young

**Comment by kentar91** [comment]
Sì perfetto ma un nuovo giocatore che vuole uccidere i nostri nel campo occhietti di cove come deve fare ?

**Comment by kentar91** [comment]
> meridian

quindi cancello il campetto fuori cove? :S

**Comment by morpheus8888** [comment]
lo scrivo così anche eventuali altre persone capiscono, meridian è il posto safe dove le persone devono andare a imparare a giocare, il campetto di cove serve come qualcosa di provvisorio, del tipo se lo fanno mezz'ora o un'ora, salgono di skill e vanno via, bisogna impedire che loggano 20 persone e si mettono li a macrare all'infinito con mob stupidi, meridian invece è studiato per far imparare. Questo ci permette di farlo molto abbondante di exp, si imparano qualcosa e poi vanno via.

**Comment by kentar91** [comment]
Ok quindi devo bloccare l accesso del campetto orchetti altrimenti la gente continua a recallarsi per Attack al centro di cove
In ogni caso ero rimasto che il campetto orchetto doveva essere usato solo da pg con meno di 300 punti skill.. ma forse ho perso qualche discussione ... Non puoi fare che quando hai + di 300 punti skill ti fa uscire da quall'area ??

**Comment by daffy55** [comment]
> Ok quindi devo bloccare l accesso del campetto orchetti altrimenti la gente continua a recallarsi per Attack al centro di cove In ogni caso ero rimasto che il campetto orchetto doveva essere usato solo da pg con meno di 300 punti skill.. ma forse ho perso qualche discussione ... Non puoi fare che quando hai + di 300 punti skill ti fa uscire da quall'area ??

ero rimasto anche io a questo

**Comment by morpheus8888** [comment]
è già così
