### ISSUE TITLE
bug .caps

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#341]
@gmocciaro quando provo ad alzarmi una skill usando il filtro va a selezionare la prima skill della sezione

esempio: voglio alzare focus
scrivo nel filtro focus, premo la gemma, esce che voglio alzare anatomy

![image](https://user-images.githubusercontent.com/83588629/140403251-a462a3dd-d93e-4a51-84b9-3c1ab6970145.png)
![image](https://user-images.githubusercontent.com/83588629/140403230-b42edd21-83d0-43db-868d-40db27a51722.png)

**Comment by gmocciaro** [comment]
aggiungo: arms lore va come utility e non come worker, si alza con gli skill points e non i craft points

**Comment by gmocciaro** [comment]
fixed
