### ISSUE TITLE
riscrivere messaggeri ingresso cove

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#346]
sto riscrivendo le stone all'ingresso di cove (dove nasce il pg) e le sto convertendo in messaggeri
ovviamente sto usando del testo in inglese
al momento ancora non viene tradotto però, non sò per qual motivo (@giga487 @gmocciaro )

**Comment by kentar91** [comment]
ovviamente @daffy55 controlla se ho sbagliato qualche frase XD

**Comment by giga487** [comment]
Ehhhh, a rigor di logica il sistema traduce i Gump. Quello non è un Gump. Non ho molta praticità col sistema di gumma per ora ma suppongo che si possa fare qualcosa e sia possibile fare vedere se ognuno il messaggio in lingua diversa in base alla lingua. Però penso lato client.

**Comment by kentar91** [comment]
Ah. Leggendo la discussione pensavo fosse lato server, avevo capito male allora lol

**Comment by daffy55** [comment]
Con Guido abbiamo deciso di RIFARE il sistema iniziale, verrà struttuato su 4 passaggi, ognuno dei quali dara' informazioni CHIAVE per poter muoversi all'interno di UOMARS, per passare da uno step all'altro ci sara' un PORTALE stile TUTORIAL, quindi NIENTE STONE e NIENTE NPC

All'interno del corridoio ci saranno i portali per il TUTORIAL, in modo tale che le persone non dovranno piu' impazzire a cercali per COVE. (rimarranno cmq i portali all'interno di COVE)
 
L'uscita da quel corridoio non sara' piu' nella casetta a NORD bensì tra la miniera ed il portale per Pryma.

**Comment by morpheus8888** [comment]
creato item startgate per le prime fasi di cove
