### ISSUE TITLE
evento miniera oro

### ISSUE THREAD

**Issue by Ale1991** [uomars/UOMars#348]
- scriptare un boss abbastanza forte da essere fatto in 10 persone che mentre fighta ogni tanto lancia massi (vedere usher) che fanno danno e lasciano il deposito a terra e che alla sua morte fa spawnare x depositi d'oro
- quando il boss spawna bcasta la sua presenza

**Comment by kentar91** [comment]
Vi chiedo di fare così il boss
- chiamare il boss Smaug
- che sia un drago 🐲🐉 (il più grande che esiste-crimson dragon?)
-che sia dello stesso colore del gold
-oltre a lanciare le rocce deve avere una fase che fa spawnare degli Hellcat, color oro (clevel1)
-un altra fase dove escono elementali di Gold (clevel2) con drop random da 3 a 7 Gold ores + un deposito da 10 a terra
- una fase dove recupera vita mangiando dei depositi che si sono attivati alla morte dei Gold elemental (perché prima hanno droppato il deposito)
- alla sua porte deve droppare 5 depositi da 50 di oro

**Comment by kentar91** [comment]
Ironbelly
https://www.youtube.com/watch?v=O0HQ6u3vias&ab_channel=TheMagicOfHogwarts

**Comment by morpheus8888** [comment]
idee al di fuori dell'evento:
- un'armatura in oro ti rende immune agli attacchi fisici dei mostri che sono su quell'isola (quelli stupidi che rompono il cazzo, non quelli dell'eventuale evento grosso)
- i mostri sono stupidi, devono solo rompere i coglioni, ma niente di complicato, niente ai magiche
- l'oro esce in quantità enormi, per evitare che farmino oro, moltiplichiamo di x il peso degli ores, in modo che un viaggio con packhorse comunque non produca più di tot golden, però comunque ti fomenta il fatto che sia sempre disponibile in abbondanza, spingendoti a fare la grossa traversata, fra lost lands, barca, equipment, etc...
- l'oro non spawna se non ci sono almeno 3 possibili uccisori nello shard. Per dare comunque modo di farmare un po' d'oro, facciamo che l'uccisione di un mostro ha una percentuale x di droppare un deposito d'oro. Per giustificare il fatto che sono andati lì e non hanno accesso alla grossa quantità d'oro.
- golden elemental sarà il mostro che rompe i coglioni lì dentro

@gmocciaro  work in progress

**Comment by morpheus8888** [comment]
fatto
