### ISSUE TITLE
[Script] Personaggio chaos non puo' distruggere la porta di Pryma

### ISSUE THREAD

**Issue by andreadellacorte** [uomars/UOMars#35]
![image](https://user-images.githubusercontent.com/295683/117223492-b59d8180-ae05-11eb-899d-c786db9b00f2.png)

**Comment by gmocciaro** [comment]
secondo me è da ridiscutere meglio con i ragazzi tutto sto meccanismo

**Comment by morpheus8888** [comment]
https://github.com/uomars/UOMars/discussions/181

spostiamoci qui
