### ISSUE TITLE
HELPINFO

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#351]
E' un po' come la corazzata potemkin, quindi proporrei di fare un "book" che compare automaticamente nella sacca del pg quando viene creato, dove all'interno si trovano scritti i comandi principali e le relative spiegazioni.

@morpheus8888

**Comment by morpheus8888** [comment]
@daffy55 ti posso fare un book che al doppio click apre il gump di helpinfo

**Comment by daffy55** [comment]
> @daffy55 ti posso fare un book che al doppio click apre il gump di helpinfo

No è la cosa piu inutile del mondo quel Gump, lo scopo è farlo sparire dalla faccia della terra

**Comment by kentar91** [comment]
Buongiorno
non sono assolutamente d'accordo a questa rimozione. Bisognerebbe reworkarlo reinserendo nuovamente una spiegazione del comando con qualche esempio.
se clicco il comando use, ad esempio, dovrebbe uscire la spiegazione con esempi, in modo da essere più chiaro.
il book nel backpack che richiama il comando potrebbe essere interessante.
inoltre ti ricordo che il .helpinfo è una versione del .help più dettagliata.
se proprio vuoi togliere questo comando bisognerebbe farlo solo per i player, non per i GM

**Comment by morpheus8888** [comment]
ho già incaricato @gmocciaro di rifarlo
