### ISSUE TITLE
Porti Felucca

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#353]
@daffy55 ti chiedo di mettere in tutti i porti almeno un barile, un chest di legno e un tronco nell'acqua in modo tale che da spawn metto i sestanti
![image](https://user-images.githubusercontent.com/83588629/142497701-f5704e56-748a-441f-8309-c0ee45bd7cbb.png)

**Comment by daffy55** [comment]
Sono stati messi apposta per vedere se piaceva l'idea, standardizzare i porti con item in modo da far capire se il porto è utilizzabile, su trammel tutti i porti hanno cassa e barile sul bordo
