### ISSUE TITLE
help info su barra in alto

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#356]
e' fattibile metterla come tasto sopra dove c'e' quello della mappa?

**Comment by giga487** [comment]
Si, ma spiegami cosa vuoi vedere.

**Comment by Darksuitjer** [comment]
un tasto che oltre world map, paperdol, inventory, journal, vendor search, chat, uo blible ecc sopra ci sia anche helpinfo (che cliccando ti apra le varie stringhe che puo aprire il comando .helpinfo)

e magari un gump piu decente, visto che gli altri sono stati cambiati e sono piu carini

**Comment by morpheus8888** [comment]
si, mi piace come idea, l'unica cosa che dobbiamo rinominarlo in commands o una cosa del genere, @gmocciaro sta anche rifacendo quel gump

**Comment by giga487** [comment]
Già fatto,
Mi manca solo da inserire alla chiamata del gump il controllo lato server in caso di più Gump aperti del solito tipo.
