### ISSUE TITLE
Tasto invio su vs @gmocciaro

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#357]
mi faceva notare sempre il buon vecchio bongeR_ se fosse possibile associare nel vs il tasto apply filter all'invio
o meglio quando scrivi, e premi invio ti carica gia quello che stai cercando, anziché schiacciare col mouse su apply filter.
è complicata come cosa o fattibile?

**Comment by morpheus8888** [comment]
non penso, credo sia relativamente facile

**Comment by daffy55** [comment]
> non penso, credo sia relativamente facile

eh, son tutti froci col culo degli altri

**Comment by gmocciaro** [comment]
ad oggi non si può fare, purtroppo (limiti tecnologici di un gioco di 90 anni fa). Sui gump non abbiamo eventi di quando un player scrive o quando un player preme "invio", quindi dovrei riscrivere mezzo client
