### ISSUE TITLE
PHANTOM CASTLE  - (bug POZZE) 

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#360]
Lollo — Ieri alle 19:31
cè un bug sul phatom castel. 
Se tiri le pozze sul piano della principessa cascano sul piano di sotto

**Comment by Ale1991** [comment]
> @Ale1991 ti ricordi la proposta che feci di tagliare a meta' il dung? e farlo a livelli? come tutti gli altri dung, quando si sale al piano di sopra in realtà si finisce a fianco (taglio e incollo il piano) almeno si evitano questi bug e futuri bug, alla fine su OSI son tutti divisi per livelli, non si sale mai ad un piano di sopra
> Che ne pensi?
> 
> EDIT: l'ho duplicato, in modo tale da vedere se e' una soluzione che piace, male che vada lo wippo
>  @kentar91 riesci a spostare la principessa?

è la soluzione migliore in assoluto anche perché si ha meno carico per i client, soprattutto per chi gioca con pc vecchiotti.

**Comment by kentar91** [comment]
Si deve scriptare la stanza da capo perché i musicisti spawnano da codice e le fiamme idem @morpheus8888

**Comment by morpheus8888** [comment]
@Ale1991 il bug è più grave e profondo, c'è un metodo che dovrebbe prendere la z della superficie dove lanci la pozza ma bugga, dobbiamo approfondire

**Comment by morpheus8888** [comment]
dovrebbe essere stato fixato, provatelo in game
