### ISSUE TITLE
Pescare

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#362]
Non e' piu' possibile pescare, dice sempre "you are too far away"

**Comment by daffy55** [comment]
@morpheus8888 che ne dici di rimuovere il recentrly looted dalla roba "Base" ? tanto raccolgono 1

**Comment by kentar91** [comment]
aggiungo che quando viene craftata si chiama fishingpolecustom, ma comunque non funziona

**Comment by gmocciaro** [comment]
fixed, aumentato il range ad 8 (era ad 1)
