### ISSUE TITLE
Recently Crafted

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#363]
Se le crafto in città non me le fa posare in banca

**Comment by morpheus8888** [comment]
top ahahah giusto @gmocciaro gugliè puoi mettere nel craft system che all'atto di creazione se è in una city gli toglie subito la flag? perché io ovviamente gestisco l'onenter nella region ma è già dentro non triggera

**Comment by daffy55** [comment]
se entro in città con il materiale all'interno del packhorse, non rimuove il recently crafted

**Comment by daffy55** [comment]
se metto un materiale recently crafted in un backpack all'interno della banka me lo fa cmq posare

**Comment by morpheus8888** [comment]
ho cancellato i commenti con la roba già fixata

**Comment by gmocciaro** [comment]
fixed

**Comment by gmocciaro** [comment]
fixato un po ovunque, ho creato un metodo per controllare se crearlo come recentlyCrafted o meno

`CommonVariables.IsRecentlyCrafted(from)`
