### ISSUE TITLE
ARCANE GEM

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#366]
Con 100 Arms Lore e 100 Alchemy impiego 1 secondo per craftare una singola arcane gem.
PROBLEMA: a differenza delle pozze, un alchimista solitamente crafta dai 3k ai 5k di arcane gem alla volta (in quanto si utilizzano, in alternativa ai reagenti, in grossa quantità) quindi 5000 secondi per un craftare 5000 arcane gem mi sembra un  tantino eccessivo.
SOLUZIONE: Craftare 10 arcane gem alla volta (Sempre, a prescindere dalle skill) in modo tale che con 100 alchemy e 100 arms lore impieghero' 500 secondi per craftare 5000 arcane gem 
@gmocciaro a te l'arduo compito

EDIT: partiamo con 10 alla volta (8 minuti per farne 5000) poi se vediamo che è troppo passiamo a 20 alla volta

**Comment by lyon1235** [comment]
Come mai avete inserito questa cosa del tempo nel craft ? Era così bello che era immediato… la trovo una cosa un po’ no sense… crea solo frustrazione questa attesa

**Comment by gmocciaro** [comment]
ma c'è il modo di crearne a "pacchetti", quindi tipo 100 al secondo, bastava chiedere
