### ISSUE TITLE
Bug Lingotti Energite

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#371]
Non trova i lingotti energite che siano ne recently crafted ne senza quella tag

**Comment by gmocciaro** [comment]
di che cazzo parli

**Comment by gmocciaro** [comment]
Ho minato un po’ di depositi l altra sera e ho visto che provando a creare armi non trovava lingotti di energite

**Comment by gmocciaro** [comment]
![image](https://user-images.githubusercontent.com/12816659/143497118-60e2dac6-db66-475b-852a-2f9700ee0afb.png)

ma tu sei sicuro che hai creato i lingotti e non stavi usando gli ores direttamente?

**Comment by gmocciaro** [comment]
oppure è possibile che volevi craftare qualcosa che non si può craftare in Energite? Guarda il Maul sotto

![image](https://user-images.githubusercontent.com/12816659/143497316-9ff62430-1ca0-4ec4-9746-9988c82085cf.png)
