### ISSUE TITLE
PHANTOM CASTLE - PER GUIDO

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#374]
Siccome @morpheus8888 è il mio padrone assoluto e io invece di aprire issue faccio tag a caso, mi pento e mi dolgo per il mio peccato e gli ho fatto un issue dedicato

**Fixa l'ultimo Boss**

Cordiali saluti
Un Pirla

**Comment by morpheus8888** [comment]
fixato

**Comment by daffy55** [comment]
@Ale1991 @gmocciaro  STO SUBENDO DEL MOBBING, PREGO INTERVENIRE!
