### ISSUE TITLE
Sistemare le pozze pagane su superfici come quella del phantomcastle

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#375]

**Comment by Darksuitjer** [comment]
ho visto che anche a vulcano non le tira perfettamente.. o meglio ne ho lanciate ieri qualcuna in generale tra gas e conflagration, e sembrava come se non leggesse alcuni tile, 
esempio tipo la conflagration anziche far un quadrato di fuoco, ha fatto qualche pezzo di fire wall per intenderci.
Non mi sembra ci fossero variazioni di altezze di terreno, ma non sono sicuro perchè alcune le ho lanciate mentre correvo.

**Comment by morpheus8888** [comment]
fixate tutte, provate, fixato anche il bug segnalato da lily, ora dovrebbe uscire bene e non a chiazze
