### ISSUE TITLE
grafiche armor

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#382]
trovare nuove grafiche alle armor "contenitore", come ad esempio:
![image](https://user-images.githubusercontent.com/83588629/143952394-6f6acdcc-9e0c-484e-9a8f-8edcb3dd2cf4.png)

**Comment by kentar91** [comment]
@SampinoInfernal

**Comment by SampinoInfernal** [comment]
Quando ci sei guardiamo qualcosa

**Comment by morpheus8888** [comment]
sono anni che la andiamo cercando

**Comment by SampinoInfernal** [comment]
Mi e' venuto in mente i cavalieri dello zodiaco, dove i cavalieri portavano le loro armature in container del genere.
Potrebbe essere un'idea, il container del colore dell'armor ovviamente
![image](https://user-images.githubusercontent.com/91663610/144495265-e410bad6-d59b-43e4-93bd-d14286418e66.png)

**Comment by morpheus8888** [comment]
quello è il baule degli assalti alle città, l'item va creato con un grafico purtroppo

**Comment by kentar91** [comment]
Come idea mi piace molto, ma pensandoci meglio una cassa creerebbe molta confusione ...
Su KR quali sono le grafiche delle armature ?

**Comment by SampinoInfernal** [comment]
Allora KR non me lo apre più non so perchè, farò controllare a hurro
Ho trovato delle grafiche di armor di diablo, ma non so se possano piacere, 
![image](https://user-images.githubusercontent.com/91663610/144592754-b04c51a3-2654-4c6e-bd73-08c82fb4025a.png)
![image](https://user-images.githubusercontent.com/91663610/144592773-ed798261-548e-4d98-83ec-038d38d1ff0e.png)
![image](https://user-images.githubusercontent.com/91663610/144592827-44cd87dd-67e1-4f68-b3c5-2e778dabaff2.png)
![image](https://user-images.githubusercontent.com/91663610/144592848-0d0435c7-c5cb-418f-90a0-4151dd8db6ee.png)
![image](https://user-images.githubusercontent.com/91663610/144592864-152560b6-d2f5-4ef9-bd1e-dfd002b5edec.png)

**Comment by SampinoInfernal** [comment]
![image](https://user-images.githubusercontent.com/91663610/145382422-bc9e6139-f454-4698-94cd-4f36665980a7.png)

idea, ho trovato questi chest .. sik possono colorare del colore dell'armor. che ne dite?

**Comment by kentar91** [comment]
Potrebbe essere un idea @morpheus8888

**Comment by morpheus8888** [comment]
possiamo provare
