### ISSUE TITLE
FLASK bankiere

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#385]
Cambiare la grafica, quella attuale non da l'anteprima e non si evidenzia al passaggio del mouse

**Comment by morpheus8888** [comment]
qual è l'id da mettere?

**Comment by morpheus8888** [comment]
@daffy55

**Comment by daffy55** [comment]
@kentar91

**Comment by kentar91** [comment]
me lo sono immaginato così
![Item 0x1854](https://user-images.githubusercontent.com/83588629/144709057-368805b9-4653-496b-80b9-80ad736cd607.jpg)

un demone che esce dal teschio con la candela (itemid 0x1854)
quindi bisognerebbe modificare anche il banchiere che esce con bodyvalue 666

**Comment by kentar91** [comment]
fatto, a voi la sorpresa :D
