### ISSUE TITLE
region smacchianti ladro

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#388]
I due altari dove i ladri sbiancano
Area no hiding, no mark
per smacchiare gli items deve stare sopra 5 secondi, tipo la barra di caricamento della conquista avamposto
L'unica cosa che non riesco ancora a capire come fare è creare un modo di andata rapida lì per fraggarli, ma non mi viene in mente niente che non sia op, ci andranno con le rune

**Comment by morpheus8888** [comment]
aggiunta quella order, manca quella palude chaos

**Comment by daffy55** [comment]
fatta palude chaos
