### ISSUE TITLE
errore chain?

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#392]
@morpheus8888 le chain dei dungeon lockpicker aumentano di 25 punti stealing e snooping, quindi posso arrivare a 125 di skill
puoi verificare se è voluto?
![image](https://user-images.githubusercontent.com/83588629/144520909-573604df-9d8f-42a3-b6bf-933be37cd642.png)

**Comment by Darksuitjer** [comment]
non ricordo quanto si era deciso come valori... ma credo di si! 
di per se da un bonus al ladro, e visto che prima si voleva mettere hiding (e creare possibili problemi per altre combinazioni)
era stato deciso di mettere un bonus su quelle 2 abilita

**Comment by morpheus8888** [comment]
si, è voluto, ma non è voluto quel recently crafted
