### ISSUE TITLE
Mini champ

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#399]
ho provato a farne spawnare uno cosi a caso, poi va beh gia che ero col gm ho ucciso tutti i mostri e arrivato in fondo, non mi da il tesoro..
mi dice vuoi il tesoro, SI
e poi non succede nulla, aumenta il livello dell'altare senza spawnare mostri e senza darmi il tesoro... ho provato a cliccare si fino ad arrivare al lvl 31.. :\

ah altra cosa, ho visto che ci sono ancora nel loot L'essence of Precision

**Comment by morpheus8888** [comment]
fixato
