### ISSUE TITLE
Mini champion Chicca!

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#400]
Gli altari hanno un tempo entro il quale va finito altrimenti i mostri scompaiono!!!
Una volta startato, il gump dove segna i mostri da uccidere, dice in quanto tempo si possa fare quell'altare.
Sarebbe bello se si vedesse il tempo effettivo rimanente prima che sparisca tutto

**Comment by morpheus8888** [comment]
fatto
