### ISSUE TITLE
Macro client 

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#401]
Ciao a tutti
Al momento non è possibile inserire macro da client sul tasto centrale, tasti laterali e tasti e rotellina mouse su e giù

**Comment by kentar91** [comment]
@giga487

**Comment by giga487** [comment]
Controllo se la libreria prende i tasti del mouse, ma penso di no e quindi niente. Stasera controllo

**Comment by giga487** [comment]
Non è molto agile come modifica, ci vuole troppo tempo, attualmente chiudo, successivamente possiamo analizzarla
