### ISSUE TITLE
Mini champ Feedback by Draker

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#405]
Lollo — Ieri alle 10:43
cmq è carinissimo ma non so quante persone servono per farlo (parecchie) e l'unica cosa è che secondo me passato un livello i mostri del livello precedente dovrebbero sparire tutti ma non è successo
però nel caso in cui i mostri scompaiono, il mostro finale che è il fire elemental deve esse piu sgravo

--------------------------------------------------------
@morpheus8888 
non ho idea di come sia strutturato attualmente, se dovrebbero sparire o meno... se non ricordo male dopo un po quelli del 1 livello non li vedevo piu, ma puo essere che mi stia sbagliando...
l'idea cmq che spariscano, non è male però c'è da vedere se i mostri successivi aumentano di hp o danno o entrambe le cose progressivamente.

**Comment by morpheus8888** [comment]
quindi gli è piaciuto? ok fortifico il fire elemental

**Comment by morpheus8888** [comment]
fai una discussione sul minichamp o se è già aperta scrivi la
