### ISSUE TITLE
travelbook point in città

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#408]
in ogni città serve il punto dove si arriva con il travelbook (struttura ricettiva) e poi scriptati

**Comment by daffy55** [comment]
in che zona la vuoi?

**Comment by morpheus8888** [comment]
@daffy55 dove ti pare

**Comment by morpheus8888** [comment]
é uno sciogli lingua?

**Comment by daffy55** [comment]
*** ****

**Comment by kentar91** [comment]
> in che zona la vuoi?

potresti usare delle strutture simili a quelle che hai usato per i dungeonmoongate

**Comment by daffy55** [comment]
Neutral: 3007 3594 0
Order: 2012 1970 0
Pk: 3659 806 10 
Chaos; 4175 2181 0

**Comment by morpheus8888** [comment]
fatto
