### ISSUE TITLE
bug corpi dei mostri

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#410]
![image](https://user-images.githubusercontent.com/83588629/145233423-89649c87-4d11-49a4-87f5-a9e287a166c6.png)

i corpi dei mostri risultano recently looted

**Comment by kentar91** [comment]
![image](https://user-images.githubusercontent.com/83588629/145234365-7a9cc39b-b130-4230-8406-3a1169fa46a2.png)

questo vale anche per i player

**Comment by morpheus8888** [comment]
fixed
