### ISSUE TITLE
AI MAGE (spell utili)

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#414]
**1° Circolo**
Weaken (Melee)
Clumsy (Archer/Ranged)
FeebleMind (Spell)
Reactive Armor

**2° Circolo**
Protection
Cure (se poisonati)
Cunning
Harm

**3° Circolo**
Bless 
Fireball
Poison
Teleport

**4° Circolo**
Curse 
Lightning

**5° Circolo**
Reflect
Mind Blast

**6° Circolo**
Energy Bolt
Explosion

**7° Circolo**
Flame Strike
Meteor Swarm
Chain Lightning
Flame Strike
Mana Vampire

**8° Circolo**
Earthquake

**Comment by lyon1235** [comment]
Earthquake

**Comment by giga487** [comment]
Tutto sommato se facessimo la spell hearthquake un sacco di coppie scoppierebbero

**Comment by lyon1235** [comment]
Potresti creare l’animazione con i cuoricini che si rompono in aria

**Comment by giga487** [comment]
Prima o dopo la spell che fa sloggare ad aria tutti? SlogQuake

**Comment by daffy55** [comment]
> Earthquake

ho corretto

**Comment by daffy55** [comment]
> Potresti creare l’animazione con i cuoricini che si rompono in aria

esiste gia
