### ISSUE TITLE
grafica goblin dungeonspot Orc Camp

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#415]
i goblin quelli piccolini ,quando muoiono stanno in piedi come se fossero vivi

**Comment by Ale1991** [comment]
non è fixabile...è un errore dei file originali.
Decidete voi se sostituirli o se lasciarli cosi

**Comment by daffy55** [comment]
sostituiamo, sono orribili da morti

**Comment by daffy55** [comment]
@kentar91

**Comment by Ale1991** [comment]
mi confermate se è stato fixato? era un errore sui file in teoria. In tal caso chi controlla chiudesse anche l'issue @daffy55 @kentar91

**Comment by daffy55** [comment]
È qncora buggayo, @kentar91 ce da cambiare grafica ai mob

**Comment by kentar91** [comment]
ci mettiamo la faccia di sampino?
