### ISSUE TITLE
Minichamp upgrade + bug

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#419]
Prima cosa se possibile mettere il conto alla rovescia non in secondi ma H M S 
ovvero: se impostato a 30 minuti appena parte, deve calcolare 29 minuti e x secondi al termine e cosi via anziché 17xx secondi

Bug:
faccio esempio pratico cosi si capisce meglio:
Ho creato il minichamp, e fatto partore il cronometro, settato 10 tile di range, e 5 minuti di tempo e fatto startare a 34 secondi
sono spawnati i mostri, che ho ucciso col gm, i 5 minuti si sono resettati per il livello successivo, e cosi via fino all'ultimo livello..
ho aspettato del tempo tra un livello e l'altro, ma ho finito il minichamp tipo a 3 minuti. è uscito il tesoro, e ho fatto ripartire il minichamp quindi sono spawnati ancora i mostri del primo livello, non li ho uccisi ma il conto alla rovescia e' ripartito dai 5 minuti
quando è il cronometro è arrivato a 5m e 37 secondi sono spariti tutti i mostri del primo livello della seconda volta che ho fatto partire il minichampion anche se nel conto alla rovescia mancava ancora un bel po di tempo

in poche parole, la seconda volta che l'ho startato, ha cancellato tutti i mostri tenendo conto del tempo settato all'inizio del primo minichamp

se non avete capito sticazzi, loggate che vi faccio vedere!

**Comment by Darksuitjer** [comment]
Secondo test: cosi è piu chiaro da cercare di debuggare
Ho fatto spawnare, ho ucciso tutti i mostri del primo livello a 60 secondi dalla fine circa, è partito il secondo livello, con il timer da 300 secondi...
dopo 1 minuti e 7 secondi è sparito tutto
quindi tecnicamente macnavano ancora 233 secondi, ma puff tutto sparito

**Comment by morpheus8888** [comment]
fatto tutte e due
