### ISSUE TITLE
bug? mount droppabili

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#420]
si parlava tempo fa di dare una certa probabilità di drop della mount cavalcata da un mob.
in questo caso il HumanoidSlayerMageLvl3 monta un orn e con un altissima percentuale ne droppa uno.
premesso che non sò se è voluto, ho constatato che questa cavalcatura non è tamabile.
![image](https://user-images.githubusercontent.com/83588629/145495374-46b682d3-98fc-405f-9f77-6a9b03461d47.png)

ho visto che alla riga 38 dello script vi è ==> Mount.Tamable = false;

non l'ho toccato, verificalo quando puoi.

**Comment by Ale1991** [comment]
@gmocciaro li ha fatti lui credo

**Comment by morpheus8888** [comment]
fixato
