### ISSUE TITLE
tp point città

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#428]
aggiornare i tp point pryma
![image](https://user-images.githubusercontent.com/83588629/145599842-e4cb460f-b6c6-42c2-b663-ef1791180347.png)

**Comment by kentar91** [comment]
rivedere anche quelli delle altre città

**Comment by morpheus8888** [comment]
@kentar91 @daffy55 scrivetemi qui quelli che mancano con relative coordinate e li aggiungo

**Comment by daffy55** [comment]
Li trovi su .go

**Comment by morpheus8888** [comment]
aggiunti
