### ISSUE TITLE
fare cove come estensione di neutral city per il .city

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#431]
@gmocciaro @Ale1991 che ne pensate? 
utilizzabile solo dai blu non fazionati ovviamente, potrebbe far comodo al niubbetto

**Comment by gmocciaro** [comment]
che potrebbe rompere alcune dinamiche come i teleport points, i teleport agli output, i punti di interesse (la freccia ti porta a fanculo) e cose così, secondo me non serve a nulla a prescidnere

**Comment by Ale1991** [comment]
concordo con guglielmo....il valore aggiunto è praticamente un risparmio di tempo di 10 secondi per andare, mediamente, al gate Cove-Pryma. Il contro è indefinito a priori e andremmo a creare un secondo point of failure. Costo/benefici io dico di no, sempre che non ho ignorato altri benefici ben più rilevanti
