### ISSUE TITLE
recent loot/crafter GM

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#432]
impostare che se un oggetto viene messo dentro la borsa di un GM viene tolta la flag recently looted / crafted

**Comment by morpheus8888** [comment]
da un gm può generare abusi in game? sicuro di darlo ad un accesselevel così?

**Comment by daffy55** [comment]
hai ragione, non togliere la flagg, ma fai si che se si recalla non droppa la roba

**Comment by morpheus8888** [comment]
fatto
