### ISSUE TITLE
Suono Royal Guardd Phantom Castle

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#436]
![image](https://user-images.githubusercontent.com/91663610/145946941-9e1ac69e-4453-49f0-9add-d37afc7bc8e7.png)

Non fa nessun suono quando colpisce, toccherebbe mettere dei colpi di spada

ps: ne approfitto per dire ma come mai tutte le mount sfondano i vari boss in giro per il mondo? ahaha

**Comment by kentar91** [comment]
quando combatte:
![image](https://user-images.githubusercontent.com/83588629/150777447-7c27959e-70e3-418f-bab3-091258df30a0.png)
quando muore:
![image](https://user-images.githubusercontent.com/83588629/150777506-3bbfe84b-47b1-41e6-8605-599e4db86c53.png)

me lo fai tu?? @giga487

**Comment by giga487** [comment]
> ![image](https://user-images.githubusercontent.com/91663610/145946941-9e1ac69e-4453-49f0-9add-d37afc7bc8e7.png)
> 
> Non fa nessun suono quando colpisce, toccherebbe mettere dei colpi di spada
> 
> ps: ne approfitto per dire ma come mai tutte le mount sfondano i vari boss in giro per il mondo? ahaha

Cosa vuol dire sfondano?
