### ISSUE TITLE
release creature

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#439]
![image](https://user-images.githubusercontent.com/83860614/146055449-2525a174-e5be-417a-8105-247e520b343f.png)

il messaggio e' errato

**Comment by morpheus8888** [comment]
come hai fatto? all release?

**Comment by daffy55** [comment]
No, col gump

**Comment by morpheus8888** [comment]
gump petlist?

**Comment by daffy55** [comment]
no, clicchi sull'animale, ti esce un menu a tendina e rilasci
io uso solo il menu a tendina, come molti pg, e' troppo comodo

**Comment by morpheus8888** [comment]
![image](https://user-images.githubusercontent.com/49568239/146833679-dc465a38-f52a-4f86-9c03-8e596a232bea.png)
 a me premendo qui funziona, cosa hai stamato?

**Comment by daffy55** [comment]
qualsiasi creatura a parte i cavalli

**Comment by daffy55** [comment]
![image](https://user-images.githubusercontent.com/83860614/146911910-542cae4c-db4f-45b4-bab1-323ed72ab9e3.png)

**Comment by morpheus8888** [comment]
mi spieghi qual è l'errore nella scritta? C'è scritto che le creature summonate spariranno ed è corretto, è un messaggio di informazione, non sta dicendo che l'animale in questione è una summon

**Comment by daffy55** [comment]
Che crea confusione, non è un pet summonato, non vedo perché me lo debba dire.
