### ISSUE TITLE
animal taming

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#440]
la maggior parte degli animali non sono piu' tamabili, i pochi tamabili non danno exp

messaggio di quelli che non danno exp:
![image](https://user-images.githubusercontent.com/83860614/146057401-e4b948ef-4847-4676-877f-a72e2f22321d.png)
era un cavallo

**Comment by morpheus8888** [comment]
è ancora attivo questo bug?

**Comment by daffy55** [comment]
Penso sia stato fixato da @Ale1991 , confermi?

**Comment by kentar91** [comment]
risolto

**Comment by daffy55** [comment]
> risolto

lo riapro perche' non e' ancora stato risolto

**Comment by daffy55** [comment]
![image](https://user-images.githubusercontent.com/83860614/147239023-b618954c-11eb-481b-8c59-6d5701dd9522.png)

**Comment by daffy55** [comment]
fixato da @morpheus8888
