### ISSUE TITLE
verificare resurrection potion quando il pg è vivo

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#443]

**Comment by gmocciaro** [comment]
veriricare cosa di preciso?

**Comment by kentar91** [comment]
Era un appunto per Guido... Però vabbè

Quando muori con .vs puoi comprare la pozione per ressarti.

Se apri il .vs da morto e poi ti resuscitano puoi comprare la.pozione da vivo.

**Comment by gmocciaro** [comment]
ma vi siete fissati con sta storia...
andiamoci al contrario, non esiste e **non è mai esistita una logica che vieta di comprare le res potion da vivo**. l'unico "controllo" implementatlo è che normalmente tu non puoi comprare da morto, ma la resurrection potion puoi comprarla anche da morto.

Ora, se volete implementata la logica, lo faccio senza problemi, ma quello che dite non è mai esistito

**Comment by kentar91** [comment]
chiuso per sempre
