### ISSUE TITLE
verificare altezze per la skill hiding

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#444]

**Comment by daffy55** [comment]
io sono alto 1 metro e 70 e posso hiddarmi

**Comment by lyon1235** [comment]
Sei un nano ghiacciato

**Comment by Ale1991** [comment]
fatto, è da testare @daffy55

**Comment by daffy55** [comment]
Ma hiding fa il check sulla Z?
Non ho capito che devo testare, a me ha sempre funzionato a qualsiasi altezza

**Comment by kentar91** [comment]
@daffy55 attualmente non fa il check sulla Z, è proprio quello il problema.
se sei 3 piani sopra al targhet non puoi hiddarti perchè dice che devi essere x tile distanti, ma non z.

**Comment by kentar91** [comment]
fixed

**Comment by giga487** [comment]
Avete usato la distanza 3d? La Norma 2 delle distanze di ogni dimensione?
@Ale1991

**Comment by Ale1991** [comment]
> Avete usato la distanza 3d? La Norma 2 delle distanze di ogni dimensione? @Ale1991
no, semplicemente vado a prendere, tra tutti i mobile entro X tile di range 2D, solo quelli che hanno una z tale che il modulo della differenza delle z è minore di 10
