### ISSUE TITLE
Ressroom ghost travel

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#445]
Buongiorno a tutti
Quando si utilizza il ghost travel c’è un healer che ti ressa al costo di 5k. Direi che è una cifra piuttosto alta per chi non ha una casa.

**Comment by kentar91** [comment]
Buongiorno 
Esisto tre healer nello shard
Healer normale per i blu e i grigi
Evil healer per i rossi 
Priced healer che ti chiede soldi in cambio del res. Il calcolo dei soldi è la media del valore delle res potion sul vs. Se non sono presenti tali pozioni il Max che ti chiederà sarà 5k
Questo verrà posizionato solo e soltanto in alcuni dungeon

**Comment by morpheus8888** [comment]
il priced healer l'hai trovato al ghost travel esterno?

**Comment by kentar91** [comment]
Ho segnato le coordinate, appena rimettiamo il Save giusto vado a toglierlo

**Comment by kentar91** [comment]
risolto
