### ISSUE TITLE
loot del party

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#452]
attualmente gli scrap del mob vengono suddivisi in mazzette in base al danno che ogni player fa al mob stesso.
ti propongo che se sei in party le mazzette non devono essere suddivise.

**Comment by morpheus8888** [comment]
che problema c'è se rimangono divise?

**Comment by kentar91** [comment]
Che se il party è di 5 persone hai 5 stack di scrap ad esempio... Un po' scomodo
