### ISSUE TITLE
Bug drop zone PK

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#455]
Per fare funzionare il deposito della flag, la z del player e del tile deve combaciare, funziona in tutti i punti tranne ad uno PK, perchè il tile sta a -34, ma se ci salgo sopra il pg lo mette a -35

![image](https://user-images.githubusercontent.com/12816659/146616148-8446341d-e5d2-4feb-a50f-72093e8c33dc.png)

altro "bug" quel punto pk è troppo facile da difendere, vedi screen:

![image](https://user-images.githubusercontent.com/12816659/146616234-c0266290-c11c-49a4-8a89-f774c28fd313.png)

così è troppo facile da coprire e basta un solo muro per bloccare l'accesso a tutti

**Comment by daffy55** [comment]
Va bene allora te ne sei perso un altro che devo cambiare 
Li cambio entrambi

**Comment by Darksuitjer** [comment]
anche in un quadrato order se pvovavo a metterla nell'angolo in basso a destra, non me la faceva mettere, ma dovevo andare nell'angolo in alto a sinistra del riquadro per depositarla.. è normale? non mi sembra di aver visto il problema su altre deposit zone
