### ISSUE TITLE
Arco Venom Bug

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#456]
Non avvelena

**Comment by Ale1991** [comment]
Dovrei aver fixato. Ho anche sistemato alcune cose a livello di codice. 
Mi testi per favore le seguenti cose: 
- [ ] bleeding di spade e asce (non armi da sword lunghe: bardica e alabarda)
- [ ] poisoning di armi da fencer in viperite e emerald
- [ ] poisoning di archi in heartwood e venomwood
- [ ] fading di archi in frostwood e ivorywood
quando mi confermi tutto chiudo l'issue @Darksuitjer

**Comment by lyon1235** [comment]
Funzionano tutti bisogna vedere l’ultima che non l’ho provata

**Comment by Darksuitjer** [comment]
c'è da cambiare l'hit sound della war fork attualmente è: 566 (0x236) ma è sbagliata... bisogna mettere: 572 (0x23C)
