### ISSUE TITLE
bug quando i mostri scappano

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#458]
quando i mostri scappano perchè in fin di vita tendono a incastrarsi negli angoli dei dungeon

su mars1 non lo facevano..

inoltre sembra che "saltano" quando scappano, puoi modificare questa velocità che non sono riuscito a capire dove devo andare a sbattere la testa?

**Comment by morpheus8888** [comment]
dimmi un nome di un mostro che salta quando scappa e controllo, per quanto riguarda

**Comment by morpheus8888** [comment]
@kentar91 attendo

**Comment by kentar91** [comment]
Pier mi ha spiegato come ottimizzare i movimenti dei mob
Penso si può chiudere, al massimo apro di nuovo
