### ISSUE TITLE
BARDO

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#459]
@morpheus8888 
sampino l'ha provato chiedi la lui

**Comment by SampinoInfernal** [comment]
Ho provato alcune mappe a parte il bug risolto gia da guido della pala ecc, per me è infattibile cosi
Mostri troppo difficili da provocare, su 10 tentativi 1 riuscito, pacificazione troppo CORTA ad area e singola niente di eccezionale. Cosi imho è infattibile un bardo
fatemi sapere

**Comment by lyon1235** [comment]
Ho provato il bardo all’inizio con Guido e poi sono state fatte quelle modifiche.. l’idea era rendere il bardo un buon pg di supporto ma non totalmente devastante in solo… per quello è venuta fuori l’idea delle resistenze dei mostri.

chiaramente si può valutare l’idea di poter lavorare sui tempi e resistenze dei mob in maniera diversa. Io direi di ampliare l’utilizzo di quelle skills anche in altre dinamiche che non siano solo quelle delle mappe ( troppo limitante)

**Comment by SampinoInfernal** [comment]
> Ho provato il bardo all’inizio con Guido e poi sono state fatte quelle modifiche.. l’idea era rendere il bardo un buon pg di supporto ma non totalmente devastante in solo… per quello è venuta fuori l’idea delle resistenze dei mostri.
> 
> chiaramente si può valutare l’idea di poter lavorare sui tempi e resistenze dei mob in maniera diversa. Io direi di ampliare l’utilizzo di quelle skills anche in altre dinamiche che non siano solo quelle delle mappe ( troppo limitante)

ma ci sta che non sia devastante ma 1 su 10 provocazioni è anche tanto ahaha

**Comment by lyon1235** [comment]
Sisi infatti si potrebbe ridurre quel gap … sono d’accordo

**Comment by morpheus8888** [comment]
che mostri avete provato? purtroppo se non scrivete feedback più dettagliati è difficile intervenire, tecnicamente non è mai stato nemmeno fatto un mostro ad hoc, solo buttati valori a caso.

**Comment by morpheus8888** [comment]
chiudo qui perché c'è l'altro git
