### ISSUE TITLE
Hytloth

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#460]
C'e' da Fixare Hytloth, a quanto pare c'erano dei muri messi in game che chiudevano delle strade, io non ne sapevo nulla se no li avrei messi statici. Col Wipe si sono cancellati, vanno rimessi perché se no si possono saltare i boss (li metterei io ma non conosco la strada)

**Comment by morpheus8888** [comment]
muri di osi o messi da noi?

**Comment by daffy55** [comment]
Da chi ha fatto il dungeon
