### ISSUE TITLE
Evento Natale?

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#461]
scrivo qui qualche idea su un evento che potremo fare per natale. @gmocciaro @morpheus8888 @giga487 @daffy55 vi chiedo di integrarlo/correggerlo se vi va

Evento Natale 2021
Nella mappa ci saranno spawnati dei pacchi regalo
I pacchi regalo sono di 3 livelli, così da differenziare il regalo, con rarità crescente:

•	Pacco livello 1: statuetta regalo Natale 2021
•	Pacco livello2: statuetta regalo Natale 2021 + cappellino di natale 2021
•	Pacco livello3: statuetta regalo Natale 2021 + cappellino di natale 2021 + Scarpe di Natale 2021
I pacchi non si rigenerano.
Questo è un modo per far girare tutta la mappa ai player.

----------------------------------------------------------------------------
In un giorno in particolare ci sarà l’evento/quest Natale (befana?):
Nello shard ci saranno dei minion in gruppi da 3/6 (cLevel 1/3 – cClass Random)
 
![image](https://user-images.githubusercontent.com/83588629/147072852-d85b67ff-b310-427e-b265-229f8e75adcf.png)

Alla morte di questi mob spawna il Krampus
Il Krampus ha rubato tutti i regali di Natale di questi giorni e sta seminando il panico nello shard, soprattutto nelle città (non può essere attaccato dalle guardie)
Mob Krampus (cLevel 5 – cClass Random)
 
![image](https://user-images.githubusercontent.com/83588629/147072869-55c53761-b778-4475-b6bd-175942d67f6c.png)

Quando perde più della metà degli HP fa spawnare i suoi minion (3 minion cLevel 3 – cClass Random)

Alla morte dei minion(cLevel 1/3 – cClass Random) escono random soldi oppure (minore probabilità) pacco natale livello 1

**Comment by SampinoInfernal** [comment]
I minion che danno exp raddoppiata che ne pensi? tanto è un evento, la gente ne approfitta ed expa

**Comment by kentar91** [comment]
> I minion che danno exp raddoppiata che ne pensi? tanto è un evento, la gente ne approfitta ed expa

può essere un idea, conta che l'exp è basata sul livello del mob, però nulla ci vieta di raddoppiarla

**Comment by giga487** [comment]
lo implemento domani che sono libero. Stanotte o al massimo domani.

**Comment by kentar91** [comment]
@legil magari si potrebbe pensare di creare delle area adhoc.

**Comment by daffy55** [comment]
> @legil magari si potrebbe pensare di creare delle area adhoc.

Descrivimela

**Comment by giga487** [comment]
Ambientazione natalizia, case di marzapane e alberi, direi. Il 22 dic 2021 11:18, Legil ***@***.***> ha scritto:

@legil magari si potrebbe pensare di creare delle area adhoc.

Descrivimela

**Comment by kentar91** [comment]
@daffy55 @giga487 si posso creare in game dei preset e spawnare direttamente quelli se volete... senza creare qualcosa da centred, così quando il mob spawna crea quell'area.
altrimenti pier fai tu da script

**Comment by daffy55** [comment]
> Ambientazione natalizia, case di marzapane e alberi, direi. Il 22 dic 2021 11:18, Legil ***@***.***> ha scritto: @legil magari si potrebbe pensare di creare delle area adhoc. Descrivimela —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
![photo_2021-12-22_19-21-07](https://user-images.githubusercontent.com/83860614/147138057-1da0c52d-5e60-48fe-a793-032699285b8b.jpg)
