### ISSUE TITLE
Museo

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#462]
@daffy55 che ne pensi se facciamo da qualche parte su felucca un museo dove esponiamo ai player le armi e le armature indossate dai manichini?

**Comment by daffy55** [comment]
Create i manichini, in base a quelli faccio il museo

**Comment by kentar91** [comment]
https://github.com/uomars/UOMars/discussions/429
inizia basandoti su questa discussione

**Comment by kentar91** [comment]
alle coordinate 6862 3959 0 ti ho fatto i manichini, si devono solo rinominare ♥

**Comment by Fred1990007** [comment]
ok preso io questo una cosa che tipo di museo è? cosa ci va? ho letto di manichi

**Comment by kentar91** [comment]
Ci vanno i manichini con le armi e le armature  al momento

**Comment by daffy55** [comment]
![image](https://user-images.githubusercontent.com/83860614/147360943-69a245e0-5a04-4db3-a3a0-1410c73bd2d8.png)
