### ISSUE TITLE
Bloccare passaggio meridian

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#463]
@daffy55 visto che due rami di meridian non sono usati al momento (pensavo di usarli per prossime espansioni), puoi "far cadere delle rocce" all'inizio dei percorsi?

**Comment by daffy55** [comment]
mi pare una cagata, perche' e' pensato per far livellare i pg al posto del dungeon di cove, ogni via ha un livello di exp differente, cosi' come era cove, io te la chiudo, ma poi i pg come diventano fullskill?

**Comment by kentar91** [comment]
attualmente il percorso fa si che quando arrivi alla fine dovresti essere skillato, anche perchè il respawn di quei mob è molto alto.
sennò invece di chiuderlo da centred lo possiamo chiudere in game... così da aprirlo se serve

**Comment by daffy55** [comment]
allora e' stato sbagliato in game, modifichiamolo, non ha senso che un dung per livellare venga aperto in piu' momenti
