### ISSUE TITLE
Problema tutorial/stanza bardo

### ISSUE THREAD

**Issue by Lollo336** [uomars/UOMars#464]
Ciao a tutti, ho provato a fare il tutorial stamattina e nella stanza dedicata al bardo non sono riuscito a proseguire. 

Ho avuto problemi con il reset skill in quanto senza averle resettate mi dava la sputa al gate per passare e dopo averle effettivamente resettate mi levava la spunta.

Stesso processo similare per la neutralità del pg in quanto si arriva in stanza grigi

@morpheus8888

**Comment by morpheus8888** [comment]
fixato
