### ISSUE TITLE
il messaggero deve parlare in inglese

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#465]
tutti i messaggeri (uomarsmessenger2 da codice) devono parlare in inglese, va bene anche la traduzione di google copiata e incollata, ma mettetelo in inglese, poi lui automaticamente parlerà in italiano o inglese a seconda di chi ha di fronte.

**Comment by morpheus8888** [comment]
ah un'altra cosa, fa cagare come è vestito, se potete sistematelo

**Comment by SampinoInfernal** [comment]
lo dico da settimane chge fa cagare
non mi fa taggare lily per correggere, chi può?

**Comment by daffy55** [comment]
> tutti i messaggeri (uomarsmessenger2 da codice) devono parlare in inglese, va bene anche la traduzione di google copiata e incollata, ma mettetelo in inglese, poi lui automaticamente parlerà in italiano o inglese a seconda di chi ha di fronte.

deletali, se cambiamo il testo si bugga lo spawn ed e' da rifare da 0 (preferisco tagliarmi il cazzo)

**Comment by morpheus8888** [comment]
teniamoci questo git aperto, così a tempo perso quando si potrà si cambieranno, meglio lasciarli in italiano che non lasciare nulla, almeno l'estetica sistemiamola

**Comment by kentar91** [comment]
@morpheus8888 quello che viene detto dal messaggero non viene tradotto automaticamente dal client, già ne parlammo.
a tempo perso vado a tradurre tutto in inglese. al momento ho fatto alcuni a jhelom

**Comment by kentar91** [comment]
@morpheus8888 a tempo perso vado a tradurre tutto in inglese. al momento ho fatto quelli del tutorial
