### ISSUE TITLE
bug ENORME exp point tutorial

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#468]
@Lollo336 mi segnala che se nel tutorial accumuli exp point, sopratutto con il ticket nella zona bardo, se fai .ghosttravel puoi tornare a pryma.
stesso problema lo abbiamo con travelbook e con le recallrune.
in zona tutorial bisogna disabilitare anche il .vs, il rewards e il .auc ( @gmocciaro ?)

ho fatto un test e sono riuscito a portare a pryma un pg con 1kk di exp XD

**Comment by morpheus8888** [comment]
si devono togliere i deed, non vedo altra soluzione, generano troppi bug, laddove ci sono problemi cerchiamo di trovare un'altra soluzione

**Comment by Darksuitjer** [comment]
Ne approfitto per dire che la sacca dei reagenti non scompare una volta passato lo step della magia.
Altra cosa, allo step della banca ho preso il pezzo di cibo e per errore l'ho mangiato... non c'era piu modo di proseguire.. :\ era meglio un qualcosa di non commestibile.
Idem l'arma rimane quando finisce lo step del bardo.

**Comment by morpheus8888** [comment]
gli tolgo che è mangiabile allora

**Comment by morpheus8888** [comment]
gli oggetti che restano non è un problema perché l'ultima stanza ti obbliga a morire, il problema è che tutto ciò che raccogli te lo puoi portare via con il travelbook. Quindi si deve disabilitare il travelbook e si devono togliere i deed dell'esperienza.

**Comment by morpheus8888** [comment]
recap:
- travelbook, recall e gate disabilitato
- si può andare via solo con ghosttravel
- è tutto fixato in teoria, si devono togliere gli exp deed @kentar91 al tutorial e poi va fatto ritestare

**Comment by kentar91** [comment]
@Lollo336 appena puoi fai un giro

**Comment by morpheus8888** [comment]
chiudo, dovrebbe essere tutto ok
