### ISSUE TITLE
disabilitare .premium a nuovo pg o depotenziarlo

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#469]
@gmocciaro ti chiedo di disattivare al momento il .premium o depotenziarlo in questa fase di open beta
anche perchè non abbiamo ancora trovato un modo per gestirlo anche economicamente

**Comment by gmocciaro** [comment]
il premium e il reward system sono due cose totalmente diverse

**Comment by gmocciaro** [comment]
essendo che queste cose le decide @morpheus8888 parlane con lui

**Comment by kentar91** [comment]
rettifico quanto detto prima: parlo solo del .premium

**Comment by morpheus8888** [comment]
discutiamone qui https://github.com/uomars/UOMars/discussions/157
