### ISSUE TITLE
Chaun the jailer

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#470]
Ho guardato draker farsi questo boss, quello che dovrebbe mandare in jail, se sei da solo non fa le fasi è corretto^?
in più quando crepa cambia nome e si chiama cosi
![image](https://user-images.githubusercontent.com/91663610/147358888-614ae4d5-28c4-4026-9b42-c7386a526445.png)

**Comment by kentar91** [comment]
fixati i nomi dei corpi sia del cyclope che del titano

**Comment by morpheus8888** [comment]
il resto è corretto
