### ISSUE TITLE
Lootare a terra

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#476]
@Ale1991 ti riporto il messaggio di Filo

ho trovato un bug
praticamente se droppo per terra qualsiasi item
poi lo prendo e senza metterlo in borsa me lo porto in giro tenendolo in mano
se poi mi allontano quanto mi pare e lo metto in un posto dove l'item non può cadere a terra torna nel punto dove l'ho raccolto al posto che andarmi nell'inventario
ti faccio un esempio stupido
se mi inseguono 10 nemici, butto a terra un cavallo raro che ho nello zaino
lo prendo in mano e corro con il cavallo in mano
mi allontano quanto mi pare e lo droppo dentro un albero o in mare che chiaramente non potendo cadere torna a terra dove l'avevo buttato la prima volta
probabilmente pure se muoio tenendolo in mano torna lì
così poi resso e vado lì a riprendermelo

**Comment by giga487** [comment]
È un bug grafico, non del server. In pratica l oggetto rimane dove era prima e tu pensi di essere più furbo del server. Basta spiegargli che è normale. Non si possono trasportare oggetti così, spero ci sia un limite sui tile massimi per cui si può spostare un oggetto senza metterlo in borsa.

**Comment by lyon1235** [comment]
Non mi sembra un bug … credo sia normale

**Comment by morpheus8888** [comment]
l'ho fixato io
