### ISSUE TITLE
bug grafico

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#477]
![image](https://user-images.githubusercontent.com/91663610/147388599-3419d1e9-c3a4-4e67-b2cc-7794c0453f00.png)
una volta entrati qui non si puà piu uscire 
3318 3603

**Comment by daffy55** [comment]
come ci sei entrato?

**Comment by SampinoInfernal** [comment]
> come ci sei entrato?

prima si poteva entrare( ma nn uscire), kentar ha messo dei pali invisibili

**Comment by daffy55** [comment]
ok, ho tolto i pali
