### ISSUE TITLE
fat travel forbidden - sugli spawn?

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#478]
![image](https://user-images.githubusercontent.com/83588629/147394680-b19bbe1a-2480-4f44-abeb-51466e0b62c8.png)
tutti gli spawn hanno questa tag... che è sta novità?

**Comment by morpheus8888** [comment]
fat travel :D

**Comment by Ale1991** [comment]
è la nuova flag recentlylooted/crafted/tamed [L], [C], [T]. È cambiata solo la scritta. Entro stasera finisco la sezione Fast Travel che spiega tutto

**Comment by kentar91** [comment]
mi sembrava strano che ci fosse una tag del genere su uno spawn nuovo XD

**Comment by Ale1991** [comment]
> mi sembrava strano che ci fosse una tag del genere su uno spawn creato mesi fa... mentre su quelli nuovi questa tag non c'è... 
settagli isrecentlylooted a false. Quella flag viene settata su qualsiasi item che viene creato. Poi puntualmente gestiamo i casi in cui non deve comparire. Oggi te lo correggo, nel frattempo puoi settarli a mano i nuovi

**Comment by Ale1991** [comment]
> mi sembrava strano che ci fosse una tag del genere su uno spawn creato mesi fa... mentre su quelli nuovi questa tag non c'è... 

molto strano. Sicuro fosse un vecchio spawn? o magari è uno spawn creato dopo aver messo quella flag a tutti gli item e ti era sfuggita, adesso con la scritta cambiata ti è saltato all'occhio

**Comment by kentar91** [comment]
> > mi sembrava strano che ci fosse una tag del genere su uno spawn creato mesi fa... mentre su quelli nuovi questa tag non c'è...
> 
> molto strano. Sicuro fosse un vecchio spawn? o magari è uno spawn creato dopo aver messo quella flag a tutti gli item e ti era sfuggita, adesso con la scritta cambiata ti è saltato all'occhio

booooooohhhhhhhhh fatto sta che se creo un nuovo spawn non ha quella flag, gli altri "vecchi" li han tutti

**Comment by kentar91** [comment]
stesso discorso vale anche con il backpack dei nuovi player lol
![image](https://user-images.githubusercontent.com/83588629/147413279-26f22003-7b50-41e7-b2e6-bee74af00196.png)

**Comment by morpheus8888** [comment]
@kentar91 quel layer fortunatamente non viene controllato, comunque ho fixato, i prossimi nuovi giocatori non avranno quella scritta
