### ISSUE TITLE
meridian - noob dungeon

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#481]
completato il percorso per i noob a meridian, va a vedere @daffy55

**Comment by daffy55** [comment]
dobbiamo segnare quale e' 300-400
quale 400-500
e quale 500-600
poi per 600-700 c'e' l'ultimo percorso fino al Castello


(100-200 c'e' il campo orchi oppure la parte neve di meridian dove ci sono solo Headless)

**Comment by kentar91** [comment]
buongiorno
il path è unico.
ogni curva è un livello aggiuntivo
i 3 percorsi sono uguali

**Comment by daffy55** [comment]
eh, buongiorno un cazzo

**Comment by kentar91** [comment]
a grandi linee 
![image](https://user-images.githubusercontent.com/83588629/147457435-8cfe1ec8-44a6-4124-8802-d28b740ecfa3.png)
rosso 300-500
verde 500-700
viola 700-1000

**Comment by kentar91** [comment]
sto mettendo gli NPC che parlano 
![image](https://user-images.githubusercontent.com/83588629/147459419-3ce6fe9a-8184-4f81-bc7f-e716d1be3dae.png)

**Comment by daffy55** [comment]
> a grandi linee 
> ![image](https://user-images.githubusercontent.com/83588629/147457763-6d82bbe4-18e4-480c-aed7-17ee651b3a68.png)rosso 300-500
> verde 500-700
> viola 700-1000
> 
> arancione mini dungeon livello 1

Numeri a caso?

**Comment by kentar91** [comment]
riflettendoci il discorso numeri è forviante .
premettendo che il livello di difficoltà di meridian è rivolto per i new player abbiamo che:
zona rosso - rivolto a tutti, anche single player, difficoltà bassa.
zona verde - difficoltà media per i new player, puoi procedere da solo con skill medie ma viene consigliato in ogni caso un team
zona viola - difficoltà alta per i new player, necessaria buon livello di skill, consigliato team

zona arancione - Merdian Fort.
è paragonabile a uno spotted dungeon di felucca di livello 1.
serve ad insegnare ai nuovi giocatori le meccaniche dei dungeon (sistema aperture porte, etc)

inoltre ricordo che cove la difficoltà rivolta ai new player è bassissima, i mob quasi non fanno danno

**Comment by kentar91** [comment]
Questa parte del percorso è di difficoltà bassa per i nuovi giocatori, puoi anche proseguire da solo

Questa parte del percorso è di difficoltà media per i nuovi giocatori, puoi anche proseguire da solo ma stai molto attento. Ti consiglio di aumentare le tue skill. Con un gruppo magari è più semplce proseguire!

Questa parte del percorso è di difficoltà alta per i nuovi giocatori! Ti consiglio di aumentare le tue skill. Con un party magari è più semplce proseguire!


This part of the route is of low difficulty for new players, you can also continue on your own

This part of the route is of medium difficulty for new players, you can also continue alone but be very careful. I advise you to increase your skills. With a party maybe it is easier to continue!

This part of the course is of high difficulty for new players! I advise you to increase your skills. With a group maybe it is easier to continue!

**Comment by kentar91** [comment]
Descrizione Meridian Fort

1. Benvenuto al Meridian Fort. Qui troverai dei mob livello base, ma le meccaniche sono quelle di un dungeon normale. Buon game!
-------

1. Welcome to Meridian Fort. Here you will find some basic level mobs, but the mechanics are those of a normal dungeon. Have a good game!

**Comment by daffy55** [comment]
Top

**Comment by daffy55** [comment]
Dobbiamo capire quanta exp si fa a Cove (campp orchi) perché se un fazionato entra di in vas por è un disastro

**Comment by daffy55** [comment]
si fa troppa exp @kentar91 
dalle 400 a mob alle 600, con mob che non fanno danno e si uccidono in 3 colpi
fai un max di 200 al mob più' forte ed il resto a scalare

**Comment by kentar91** [comment]
Fixed
