### ISSUE TITLE
NASCONDERE GLI ALBERI

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#485]
Rimuovere l'opzione da Client 
Trees to stumps

perche' non mi sono fatto un culo per rimuovere tutti gli alberi per poi lasciare quest'opzione che da il seguente effetto
![image](https://user-images.githubusercontent.com/83860614/147456142-c9d7a9ec-7732-46ed-8d0c-c8a12551205f.png)

che fa anche cagare

@Ale1991 @gmocciaro @morpheus8888 @giga487 
Grazie

**Comment by morpheus8888** [comment]
io propendo per rimuoverle tutte quelle opzioni, non solo quella dell'albero

**Comment by lyon1235** [comment]
No vi prego ! È una cosa comodissima non aver gli alberelli …

**Comment by daffy55** [comment]
> No vi prego ! È una cosa comodissima non aver gli alberelli …

ti abituerai
