### ISSUE TITLE
marker alle lostlands

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#488]
servirebbero urgentemente solo i marker di uscita alle lostlands, poi con il tempo aggiungere quelli mancanti come fatto per i markers a felucca.

**Comment by kentar91** [comment]
![image](https://user-images.githubusercontent.com/83588629/147477866-e63e9bbb-8d1c-4c65-b759-388815a7db6b.png)
[INTEREST.txt](https://github.com/uomars/UOMars/files/7780428/INTEREST.txt)
[MOONGATE.txt](https://github.com/uomars/UOMars/files/7780431/MOONGATE.txt)


@Ale1991 puoi caricarli?

**Comment by kentar91** [comment]
[icon_map_229122021.zip](https://github.com/uomars/UOMars/files/7789854/icon_map_229122021.zip)

@Ale1991 ho aggiornato le icone

**Comment by kentar91** [comment]
Ottimizzato il processo
