### ISSUE TITLE
correzione travelbook

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#489]
bisogna rinominare la zona "Magical" in Fire ? o è voluto?
![image](https://user-images.githubusercontent.com/83588629/147477628-906a13ca-8064-4067-8263-a9a1a7fdedba.png)

**Comment by morpheus8888** [comment]
sinceramente non ricordo, i nomi li decidemmo tempo fa

**Comment by kentar91** [comment]
Allora è stato cambiato quando è stata fatta la modifica Fire resistance --> magic resistance
Puoi sistemare?

**Comment by morpheus8888** [comment]
fatto
