### ISSUE TITLE
bug creazione account / lingua

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#497]
![image](https://user-images.githubusercontent.com/83588629/147514567-654798f6-fc1a-4101-8a75-52b9854689a0.png)

quando crei un nuovo pg e scegli lingua italiana comunque resta inglese.
per poterlo fixare devi andare nelle option del paperdoll e mettere manualemente ita, perchè resta flaggato eng

**Comment by giga487** [comment]
![image](https://user-images.githubusercontent.com/19823607/147559227-ff41df20-3b29-4f4e-ac1b-c3a8f644bfd9.png)

per come è il testo, non avevo idea che dovesse cambiare la lingua del gioco. implemento
