### ISSUE TITLE
problema pack mule - tutorial

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#500]
se ho un pack mule a felucca e poi faccio il tutorial worker si buggano i numeri di follower perchè giustamente il pack mule ne ha 4
ti propongo di uccidere il pack mule se entri nella zona tutorial
se non sono stato chiaro insultami pure

**Comment by morpheus8888** [comment]
devono fare .petlist e fare il release

**Comment by daffy55** [comment]
> devono fare .petlist e fare il release

non hanno modo di saperlo, se stanno facendo il tutorial e' perche' non conoscono il gioco

**Comment by morpheus8888** [comment]
ditemi la stanza dove hanno questo problema che lo scrivo nelle istruzioni

**Comment by daffy55** [comment]
> ditemi la stanza dove hanno questo problema che lo scrivo nelle istruzioni

A memoria ti direi che è una delle prime perché ti spiega il packhorse (che poi ti porti fino alla fine)

**Comment by morpheus8888** [comment]
fixato con degli avvisi per far capire al player
