### ISSUE TITLE
[L] Bug? pryma by Saro

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#501]
Saro mi diceva: avevo gli ores, sono tornato in citta a pryma, mi sono usciti i lingotti (con la [L]) (e gia qui secondo me è gia un problema perche essendo in citta non dovrebbe aver le tag)
cmq lui poi ha preso 2 lingotti con la L li ha divisi, 1 è rimasto con la L l'altro no è sparita la flag

altra cosa che mi diceva: il talismano avendo solo 1 crafter nell'account dice:
As young player you have 100% bonus for the first 7 days. 
il bonus non è permanente avendo solo 1 crafter? è una dicitura inutile ed errata?

rimborsato 50gp

**Comment by morpheus8888** [comment]
lo young player comanda, da young hai tutti i worker al 100% sempre, finito lo young entra la seconda logica, ovvero 1 worker 100%, altrimenti scade

l'altro bug è grosso, va risolto, se separi i materiali crea i recently looted

**Comment by Ale1991** [comment]
risolto il bug della separazione delle stack che genera stack con la flag fast travel forbidden
