### ISSUE TITLE
bug tutorial mago con 2 pg

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#509]
visto che il secondo pg non ha lo spell, se fai il tuorial alla stanza NON WORKER 20 non puoi castare sui maiali
![image](https://user-images.githubusercontent.com/83588629/147576545-68ab5368-40c1-401e-ac27-9ae2549632b8.png)

**Comment by morpheus8888** [comment]
eh in teoria uno  ci dovrebbe andare con il primo pg, penso ad una soluzione

**Comment by kentar91** [comment]
potresti fare che nella region di jhelom quando metti magery ti dà lo spell.
più o meno come cove con le armature...

**Comment by morpheus8888** [comment]
fai comparire sul tavolo un libro pieno non blessed e sta apposto

**Comment by morpheus8888** [comment]
@kentar91 quando lo fai chiudi direttamente tu l'issue

**Comment by kentar91** [comment]
fatto
