### ISSUE TITLE
recently looted in citta, non perde la tag e si puo' mettere in banca

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#515]
![image](https://user-images.githubusercontent.com/83860614/147595489-522eca9d-6b81-4cc2-b414-34a3c36cd193.png)

**Comment by morpheus8888** [comment]
il recently looted è fatto per essere messo in banca, il fatto che non perde la tag che significa? che non si toglie quando entri in città?

**Comment by lyon1235** [comment]
Successo anche a me con i reagenti, non perdono la tag quando entri dentro pryma

**Comment by daffy55** [comment]
> il recently looted è fatto per essere messo in banca, il fatto che non perde la tag che significa? che non si toglie quando entri in città?

Pensavo di no, pensavo che il recently looted non potesse essere messo in banca

**Comment by morpheus8888** [comment]
@Ale1991 ci pensi tu a fare che quando separano gli stacked controlla la region e setta la flag?
