### ISSUE TITLE
mob pulisci pack horse tutorial

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#516]
nell'ultima stanza del tutorial worker i player lasciano il pack horse tamati e abbiamo difficoltà... c'erano questa sera 25 packhorse li dentro... 
possiamo creare un mob che uccide solo i pack horse ?
o metto sampino a deletare cavalli?

**Comment by morpheus8888** [comment]
se fanno release si cancella, se non lo fanno putroppo rimane lì

**Comment by Ale1991** [comment]
chiudo perche' prima o poi faranno release per necessita' . Ho aggiunto che in quella region se releasi qualcosa si cancella
