### ISSUE TITLE
Crafting time

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#519]
Ciao ragazzi che dice se si rivede il discorso del tempo del craft in base ad arms lore ? La vedo una cosa assurda… ora sto facendo dele arcane gem 7 min deve stare fermo l’omino alla craft machine

**Comment by morpheus8888** [comment]
la domanda è perché non alzi armslore?

**Comment by morpheus8888** [comment]
non è una lavorativa, quindi ti consuma gli exp point

**Comment by lyon1235** [comment]
Ho 60 arms lore, domani provo con 100 ma mi sembra sempre tanto tempo

**Comment by morpheus8888** [comment]
fammi sapere qui appena testi, però si effettavamente 7 minuti con 60 armslore forse è tanto,
