### ISSUE TITLE
Risorse craft

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#520]
Stasera ho provato a craftare le arcane gem per vedere quante ne uscivano (19 alchemy)

avevo 1700 reag per tipo sono venute fuori 220 arcane gem non è un po’ troppo poco ?

**Comment by morpheus8888** [comment]
la prossima volta prendi il tempo dal momento in cui parti per andarle a prendere fino alla lavorazione, così abbiamo un indicatore migliore.

**Comment by lyon1235** [comment]
Che significa in cui parti per andarle a prendere ?

**Comment by kentar91** [comment]
forse intende: quanto tempo impieghi per andare a raccogliere le risorse dalla città al punto di lavorazione, in modo da avere un riferimento temporale

**Comment by daffy55** [comment]
Intende tutta la lavorazione, da quando parti, ravvogli ritorni in città e lavori

**Comment by lyon1235** [comment]
Up al post ieri diversi si sono lamentati delle quantità enormi che ci vogliono per fare pozze armature ecc… cercate un attimo di rivedere le quantità. 
Ieri comunque ho provato a fare giro reag ci ho messo più o meno 40 minuti per 1600 per tipo.
Poi ci vogliono 5 minuti circa per farle in città. Mi sembrano troppo poche 220 arcane gem. Stessa cosa per le pelli (li penso sia peggio)

**Comment by SampinoInfernal** [comment]
Lyon io ieri ci ho messo pochissimo a fare una plate in obsidian, fuori città alle worker ho sprecato tipo 400 linghi

**Comment by lyon1235** [comment]
Allora le proporzioni non vanno bene … se con 400 lingotti fai una plate non mi torna il dato di jpi che diceva che con 1000 pelli non fai una studded

**Comment by SampinoInfernal** [comment]
> 

440 per la precisione
Alle worker, 100 arms lore, 19 blacksmith

**Comment by Ale1991** [comment]
> Allora le proporzioni non vanno bene … se con 400 lingotti fai una plate non mi torna il dato di jpi che diceva che con 1000 pelli non fai una studded

le studded sono armor livello 2 (leather livello 1)
le plate sono invece livello 1 (dragon plate sono livello 2).
Le armor livello 2 danno 6 physical res in piu e oltre a costare il dobbio in materiale di base, consumano anche un materiale addizionale craftato da un altro crafter. Le livello 2 sono il massimo che si puo' ottenere...e volerlo fare il secondo giorno...e' dura ma comunque fattibile

**Comment by morpheus8888** [comment]
chiudo, nel caso apriamo una discussion
