### ISSUE TITLE
Spawn punti di raccolta risorse

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#521]
Ciao a tutti
Ieri con il mio tagliaerba di fiducia mi sono fatto un giro per le piantine di felucca e ho notato che respawnano troppo velocemente come nelle lost land. Quasi conviene rimanere a felucca e non andare alle lost per fare risorse. 
rivedrei un attimo il timer di Spawn

**Comment by morpheus8888** [comment]
è voluto, la roba di base come i reagenti non può essere scarsa, un reagente è come un'arma in ferro per un warrior, se guardi le miniere di ferro vanno a razzo pure quelle
