### ISSUE TITLE
Grigio a pryma

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#525]
![image](https://user-images.githubusercontent.com/91663610/147665044-79a9119e-93b6-470b-bb18-1c2bd831b501.png)
grigio dentro pryma non attaccato dalle guardie, è perche è young?

**Comment by morpheus8888** [comment]
no non è lo young è un problema più grave che io non sono riuscito a risolvere @Ale1991 mi serve il tuo aiuto

**Comment by morpheus8888** [comment]
forse ho fixato
