### ISSUE TITLE
Durability armature e armi

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#535]
Ciao ragazzi 
Anche se ci sono gli engraver per la durability delle armi, consiglio di aumentare le resistenze delle armi e armature.
È antipatico andare a fare un dung e rompere dopo 10 mob l’arma ora che siamo all’inizio soprattutto e non tutti i pg conosco le dinamiche di gioco…

**Comment by SampinoInfernal** [comment]
potrei essere d'accordo
la leather gargoyle mi si è rotto il gorget dopo tipop duie mostri al campo lizard.
