### ISSUE TITLE
bug recentely cratfed check

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#538]
se indossi qualcosa recentely crafted non fà il check del recall

**Comment by morpheus8888** [comment]
il recall o anche il travelbook?

**Comment by kentar91** [comment]
Travelbook

**Comment by morpheus8888** [comment]
non sono riuscito a replicarlo, per il momento chiudo, nel caso riscontri ancora il problema specifica esattamente qual è l'item che bugga (per fare le prove mi raccomando non usare il gm)
