### ISSUE TITLE
special dye tube e dye tube

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#539]
non si tolgono dallo stack
inoltre quando viene creato lo special non crea i colori per colorarlo

**Comment by morpheus8888** [comment]
@daffy55 spiega bene il problema ad alessio, lui sa come risolverlo penso, io no

**Comment by daffy55** [comment]
Quando si forma uno stack con più dye tube non è piu possibile separarli

**Comment by morpheus8888** [comment]
@Ale1991 @daffy55 è stato risolto per caso?

**Comment by morpheus8888** [comment]
spiegalo meglio per favore, così poi @Ale1991 può intervenire

**Comment by daffy55** [comment]
Quando li raggruppi in uno stack non si possono piu separare
