### ISSUE TITLE
LOOT MOSTRI

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#541]
![image](https://user-images.githubusercontent.com/91663610/147824073-be8318d0-7a87-4424-9291-86112d8f9221.png)

Hanno sprecato un opra per fare la mappa con le ancient wyrm che davano 10 scrap L'UNO e poi sto mostro ti da 300 recall scroll e piu soldi.

**Comment by morpheus8888** [comment]
nelle mappe del tesoro non c'è solo recall scroll e soldi, se c'era solo quello è un bug, ma mi servono più dettagli

**Comment by morpheus8888** [comment]
monentaneamente chiudo perché ho troppi git aperti, nel caso riaprine un altro quando hai più dettagli @SampinoInfernal
