### ISSUE TITLE
é voluto che i cavalli siano attaccati per non farli scappare mentre li tamano?

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#542]

**Comment by thepatriot87** [comment]
![screenshot_2021-12-31_01-57-36](https://user-images.githubusercontent.com/17385984/147824722-1997fd98-e89f-43d8-8f8e-27e61022b1eb.png)

**Comment by Ale1991** [comment]
no pier...fixo

**Comment by Ale1991** [comment]
@morpheus8888 vedi se riesci a fixare tu, non riesco a capire come hai fatto la logica che iniziano a correre

**Comment by morpheus8888** [comment]
fixato
