### ISSUE TITLE
bug arpia tutorial 

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#545]
se provochi prima e poi fai pace non puoi più pacificare l'arpia ... in nessun modo...
da verificare con tutti gli altri mob usabili con il bardo

**Comment by morpheus8888** [comment]
ma c'è un messaggio di errore? o non funziona e basta?

**Comment by kentar91** [comment]
> 

non funziona e basta

**Comment by morpheus8888** [comment]
@kentar91 riesci a farmelo vedere in diretta?

**Comment by morpheus8888** [comment]
nel frattempo chiudo, sembra fixato
