### ISSUE TITLE
**tutorial la criminal stone ti costringe a toglierti young

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#546]
l'abbiamo temporaneamente bypassato

**Comment by thepatriot87** [comment]
![screenshot_2021-12-31_03-06-40](https://user-images.githubusercontent.com/17385984/147827348-43def25f-e057-42f8-9963-069a49d8697a.png)
ricordare di riabilitare il teleport e spostare la pietra dopo il fix

**Comment by morpheus8888** [comment]
fixato, quando superi quel gate ti rimette automaticamente lo young se rispetti i criteri nell'account
