### ISSUE TITLE
pesci arancioni alle lost

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#549]
promemoria per me: sono messi scomodi, verificare

**Comment by kentar91** [comment]
perchè sono scomodi? 
![image](https://user-images.githubusercontent.com/83588629/147893637-14889c1a-9613-42bd-b415-550e3202c802.png)

**Comment by daffy55** [comment]
per lo screen che hai messo, rispetto agli altri pesci delle altre risorse, non c'e' una strada dal portale a te

**Comment by daffy55** [comment]
la apro su centred

**Comment by kentar91** [comment]
Ah ho capito...
