### ISSUE TITLE
Fire elemental mappe 

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#550]
![image](https://user-images.githubusercontent.com/91663610/147845172-a04043d0-af2a-4f17-941d-f52537b605fe.png)

cdt, anche se reporta sti danni, instankilla al tocco.. mappa di terzo

**Comment by lyon1235** [comment]
Si provato L’altro giorno con draker, va un attimo rivisto

**Comment by morpheus8888** [comment]
potete far dei test in locale per dirmi esattamente cosa istant killa? quando ti fa danno o all'improvviso come se facesse una magia?

**Comment by morpheus8888** [comment]
fixato, erano i guardiani
