### ISSUE TITLE
Allineare crafting armi

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#557]
Craftare armi da arciere costa in termini di materiali più del doppio rispetto a quelle da Warrior 
Potresti allineare le quantità ?

**Comment by Ale1991** [comment]
fixato...
- 14 risorse base armi liv 1 1hand
- 28 risorse base armi liv 1 2hand
- 28 risorse base archi liv 1 2hand

- 28 risorse base armi liv 2 1hand 
- 56 risorse base armi liv2 2hand
- 56 risorse base archi liv2 2hand
