### ISSUE TITLE
bug deed tutorial

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#559]
lo scrivo perché ancora non é risolto

il tutorial non worker non da' il deed dei 350k

**Comment by morpheus8888** [comment]
ma sei sicuro pie? perché in locale mi funziona, fate qualche test in game

**Comment by thepatriot87** [comment]
abbiamo provato io e kentar due volte
comunque domani riprovo

**Comment by kentar91** [comment]
se fai prima il tutorial worker e poi quello non worker, da quello non worker non ti dà il ticket.
oltre a ricevere diversi page in merito, ho provato anche con il mio pg di test..

**Comment by morpheus8888** [comment]
in locale ho appena creato un account, l'ho fatto passare all'end tutorial worker e poi all'endtutorial non worker (ricordo che sono due gate distinti, non sbagliate a mettere lo stesso alla fine di ogni tutorial) e mi ha dato due deed, quindi non riesco a riproduro @thepatriot87 @kentar91

**Comment by morpheus8888** [comment]
![image](https://user-images.githubusercontent.com/49568239/148109168-8011228a-5382-46e6-a11d-3212d7a623e5.png)
 vi ammazzo, sono appena andato in game per verificare e c'era il gate sbagliato. L'ho appena sostituito e ho cancellato lo spowner sbagliato. MI RACCOMANDO NON SBAGLIATE PIU SUGLI ENDTUTORIAL GATE DA PIAZZARE
