### ISSUE TITLE
Worker tutorial (mini bug)

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#560]
c'e' un bug nelle 2 stanze finali dove dice di mettere alchemy 1 e il gate poi ti chiede alchemy per passare, ma se non la setti a 20 non ti fa andare avanti, e se avevi gia craftato le robe, te le fa perdere!

modificare quando dice di settare alchemy 1 con alchemy 20

idem credo nella stanza dopo dove chiede tailoring 1
non ho provato la stessa cosa, per non perder tempo ma tempo sia uguale!

a parte qualche leggero intoppo tipo questo, tempo impiegato 26 minuti e 18 secondi

**Comment by morpheus8888** [comment]
fixato
