### ISSUE TITLE
Bug CrystalCyclopeBoss (1° liv Nigmar Cove)

### ISSUE THREAD

**Issue by Ale1991** [uomars/UOMars#563]
- il boss intrappola 2 player alla volta
- i player intrappolati non possono uscire se il boss resetta 
La soluzione che ho concordato con Jelia e altri e':
ogni volta che il boss si resetta si tolgono le guardie carceriere e si buttano fuori gli incarcerati tanto anche se resettassero ogni volta che intrappola qualcuno il boss non lo killerebbero mai visto che torna full vita

**Comment by morpheus8888** [comment]
fatto
