### ISSUE TITLE
Bard Issues

### ISSUE THREAD

**Issue by Ale1991** [uomars/UOMars#565]
usiamo questa issue per ricevere feedback sul bardo...cosa sistemare e quali mob delle mappe non sono pacificabili/provocabili

**Comment by BardoMars** [comment]
MAPPA LVL 3 - HAVEN 
dread spider unico usabile. res peace 66% provo 70% discordance 64%
fire elemental tutte le resistenze (discordance, provo, peace) 100%
air elemental uguale al fire
infattibile col bardo
![image](https://user-images.githubusercontent.com/96991607/147884080-16b2e612-423d-4258-9664-f7969656797c.png)

**Comment by BardoMars** [comment]
MAPPA LVL 1, trappola esplosiva no guardiani.
trovati due guardiani non miei
mongbat tutte le resistenze a 100
hell hound tutte le resistenze a 100
impossibili da fare col bardo
![image](https://user-images.githubusercontent.com/96991607/147884384-e53dc46f-4d99-4a3a-929c-0a680e2c835c.png)

**Comment by BardoMars** [comment]
MAPPA LVL 2 HAVEN, gazer e gargoyles
gazer tutte le resistenze 100%
gargoyle tutte le resistenze 100%
impossibile farla col bardo
![image](https://user-images.githubusercontent.com/96991607/147884485-7de3f8c9-379d-4933-86da-66c0e6a06be5.png)

**Comment by BardoMars** [comment]
MAPPA LVL 2 HAVEN, earth elemental/hell hound/ orcish mage
tutti con tutte le resistenze al 100%, infattibile
![image](https://user-images.githubusercontent.com/96991607/147884666-29e4fb72-abbe-4137-a025-9d35cf87e552.png)

**Comment by BardoMars** [comment]
MAPPA LVL 2 HAVEN, gazer/hellhound/gargoyle
tutti esaminati in precedenza, tutti con valori resistenza al 100% alle tre skill
infattibile

**Comment by BardoMars** [comment]
MAPPA LVL 2 HAVEN, stessi mostri delle altre, quindi infattibile col bardo ma questa è da segnalare per la posizione curiosa del chest 
![image](https://user-images.githubusercontent.com/96991607/147884936-2601ff60-0e1f-4867-ab26-1902dee64dbc.png)

**Comment by BardoMars** [comment]
MAPPA 3 HAVEN minotauri
resistenze: peace 72% provo 78% discordance 79%
le trovo comunque molto alte
pacificato al secondo tentativo è rimasto fermo per circa 60 secondi
ripacificato al primo tentativo (peacemaking self) ed è tornato alla carica in un secondo
ripacificato alla prima diverse volte, diciamo una media di 1/2 su 4
stessa cosa per provocation, la prima provocazione è riuscita alla sesta volta poi in media 1 su 3/4
la cosa snervante del bardo è la necessità di avere la shepherd in mano, che ti si leva quando casti e non riequippa con la macro .arm 1 (suggerisco di poter castare con la shepherd in mano o sostituire item distanza)

**Comment by morpheus8888** [comment]
minotauri piu dread spider è di livello 4, la livello 3 ora è sistemata e le nuove shephard crook avranno lo spell channeling

**Comment by BardoMars** [comment]
allora devo essermi confuso smistandola, la livello tre di cosa?
comunque anche il lich (non so di che mappa) tutte resist a 100

**Comment by morpheus8888** [comment]
fixato anche hellhound e mongbat

**Comment by BardoMars** [comment]
ho scordato di menzionare la prima mappa in cui ho capito che ci fosse qualcosa che non andava, era una lvl 1 FELUCCA, headless e scheletri tutti a 100

**Comment by morpheus8888** [comment]
fixato anche gazer e gargoyle

**Comment by BardoMars** [comment]
si puo vedere gia' una tabella coi nuovi valori che stai mettendo? con che criterio li stai fixando? per livello difficolta' mappa?

**Comment by morpheus8888** [comment]
fixato earth e orcish mage, li sto rendendo fattibili, poi il bilanciamento viene dopo, ora sono proprio buggati

**Comment by morpheus8888** [comment]
la posizione dei chest purtroppo è random a volte sarà buggata così, è inevitabile

**Comment by BardoMars** [comment]
> fixato earth e orcish mage, li sto rendendo fattibili, poi il bilanciamento viene dopo, ora sono proprio buggati

stai facendo un lavorone

**Comment by morpheus8888** [comment]
il peace making self è voluto che duri pochissimo è qualcosa di emergenziale ad area, dovrebbe durare roba di pochi secondi, l'unico bug che mi sembra di aver capito ci sia è che il mostro anche se pacificato se ti avvicini ti attacca giusto? lascio così o fixo?

**Comment by morpheus8888** [comment]
> > fixato earth e orcish mage, li sto rendendo fattibili, poi il bilanciamento viene dopo, ora sono proprio buggati
> 
> stai facendo un lavorone

grazie, :D

**Comment by BardoMars** [comment]
> il peace making self è voluto che duri pochissimo è qualcosa di emergenziale ad area, dovrebbe durare roba di pochi secondi, l'unico bug che mi sembra di aver capito ci sia è che il mostro anche se pacificato se ti avvicini ti attacca giusto? lascio così o fixo?

si avevo letto, ma pensavo "qualche secondo" non fossero due o tre ma almeno 10-15, 
mentre per quanto riguarda si, non ho avuto modo di capire se tutti perchè molti li ho solo spectati. PER ME sarebbe opportuno fossero proprio charmati e non menassero

**Comment by morpheus8888** [comment]
lo vuoi aumentato? ma sei full skill?

**Comment by BardoMars** [comment]
music provo e peace a 100 si. 
quanti secondi dovrebbe durare ora il peace-self?

**Comment by morpheus8888** [comment]
da codice leggo 4 secondi per tutte le creature con peace resistence inferiore a 80, superiore a 80 sono immuni

**Comment by BardoMars** [comment]
secondo me è l'ultima modifica a cui pensare ora come ora è vero che ti potrebbe salvare la vita però magari vediamolo quando stiamo affrontando la questione del bilanciamento fra tutti, se riesco stasera vado a fare un po di mappe alle lost, ora vedo se ho qualcosa su felucca

**Comment by BardoMars** [comment]
MAPPA 0 FELUCCA
headless e scheletri, entrambi tutto a 100, infattibile
![image](https://user-images.githubusercontent.com/96991607/147957152-459036ed-9cc1-4bac-ba4c-9a1e5ec73998.png)

**Comment by BardoMars** [comment]
mappa 4 HAVEN
ogre lord pacificato alla prima (69 res), provocato alla 6 (61%res)
gazer:
 pacificato alla prima (la prima volta) [73% res], 
pacificato alla 6a la seconda volta, 
alla 1a la terza volta, 
alla 7a la quarta volta
alla 8a la quinta e ultima volta
PROVOCATION fallita 19 volte su 20 (contro 71% res)

dread spider 1 pacificato alla 1a (res 63%) provocato alla 4a (res 70%)
dread spider 2 pacificato alla 5a provocato alla 5a

**Comment by morpheus8888** [comment]
reso conto soggettivo? ora come va?

**Comment by BardoMars** [comment]
mappa 2 HAVEN
orcish mage pacificato alla 1a (47 res)  provocato alla 4a (43 res) - seconda volta pacificato alla 1a provocato alla 1a
gargoyle pacificato alla 2a (44% res) provocato alla 2a (41% res) - seconda volta pacificato alla 1a
hell hound  pacificato alla 1a, provocato alla 3a (43% res entrambe)

tutto sommato è stata la mappa piu' godibile, l'unica che son riuscito a fare da solo, abbastanza ben bilanciata

**Comment by BardoMars** [comment]
tip sui dread spider (cosa che ieri non facevano) sparano la web a caso, anche quando li ho provocati uno contro l'altro, e il froze della web praticamente è morte certa.

reso conto soggettivo, abbasserei un po le resistenze dei mostri nelle mappe 3, sono veramente molto difficili non voglio immaginare cosa sia una mappa 5

**Comment by BardoMars** [comment]
per come la vedo io, contando che il bardo puo solo fare le mappe:
sarebbe bello se potesse fare i primi 4 livelli di mappa (0-3) in perfetta autonomia e con non troppa difficoltà
il lvl 4 con difficoltà ma fattibile
dal 5 in su in party

**Comment by morpheus8888** [comment]
ok abbasso resistenze del mostri delle mappe di 3 e sistemo le ragnatele

**Comment by BardoMars** [comment]
controlla i gazer, sono riuscito a provocarli una volta su 20

**Comment by morpheus8888** [comment]
ho abbassato il freeze della ragnatela da 10 a 3 secondi e nerfate le resistenze al bardo al livello 3, nerfati anche i gazer

**Comment by BardoMars** [comment]
lavorone!
 ho fatto una mappa 4: facile, con ogre e dread spider, praticamente identica alla lvl 3.
 dopo provo qualche altra lvl 4 per vedere con mostri diversi la difficoltà.

mappa lvl 5 alle lost, Baal, lich lord e due blood elemental
Ba'al peace 78 provo 76 discord 76 pacificato in media alla 5a/6a prova, e con MOLTA fatica essendo veramente forte
provocato in media alla 6/7
il baal deceduto ha dato solo 838 xp
anche gli altri.
lich lord peace 79 provo 77 discord 72, test non riuscito
blood elemental peace 82 provo 81 discord 85, pacificato in media al 5o/6o, provocato in media alla 6/7

tutto sommato la mappa è IMHO troppo difficile per essere lvl 5, se fatta in solo veramente ardua, in due fattibile con tattica

**Comment by BardoMars** [comment]
un paio di note a freddo: 
ho riscontrato non poca difficoltà a fine mappa lvl 3 contro UN solo dread spider. 
Ammazzarlo coi cast è praticamente impossibile  a meno di bersi un keg di pozze mana.
sono andato col macer e qui ho notato una cosa, abbassa la durability degli item in una maniera scandalosa: mi ha rotto gorget e guanti di una plate obsidian nuova prima di morire.
le sue ragnatele continua a spararle a caso sul bardo anche mentre combatte contro il mostro verso cui è stato provocato

ogre lord mossa "charge" teleport su nemico, mi ha mandato in tilt stasera, si teleporta su di te dandoti anche botte da 40, rimuoverei personalmente, o abbasserei notevolmente il danno, visto che già ti si recalla addosso.

RIP a tutti i pack horse perduti in questi test, fategli un monumento funebre ahahah

**Comment by morpheus8888** [comment]
> MAPPA 0 FELUCCA headless e scheletri, entrambi tutto a 100, infattibile ![image](https://user-images.githubusercontent.com/96991607/147957152-459036ed-9cc1-4bac-ba4c-9a1e5ec73998.png)

fixato

**Comment by morpheus8888** [comment]
> lavorone! ho fatto una mappa 4: facile, con ogre e dread spider, praticamente identica alla lvl 3. dopo provo qualche altra lvl 4 per vedere con mostri diversi la difficoltà.
> 
> mappa lvl 5 alle lost, Baal, lich lord e due blood elemental Ba'al peace 78 provo 76 discord 76 pacificato in media alla 5a/6a prova, e con MOLTA fatica essendo veramente forte provocato in media alla 6/7 il baal deceduto ha dato solo 838 xp anche gli altri. lich lord peace 79 provo 77 discord 72, test non riuscito blood elemental peace 82 provo 81 discord 85, pacificato in media al 5o/6o, provocato in media alla 6/7
> 
> tutto sommato la mappa è IMHO troppo difficile per essere lvl 5, se fatta in solo veramente ardua, in due fattibile con tattica
> 
> edit. 32k scraps di premio troppo pochi di sicuro

ho tolto ogre lord dalla mappa di terzo e lasciata solo al quarto, così ora dovrebbero avere più senso

**Comment by BardoMars** [comment]
appena fatto una mappa di 4o full gazers, l'ho trovata equilibrata
si pacificano in circa 6/7 tentativi di media, si provocano in 3/5
(tolti i pkappini a cui devi spiegare che stai facendo i test e ti segano per le leather in pelle di uccello) non è stato difficile

**Comment by BardoMars** [comment]
ho letto i commenti di daffy55 sull'altro 3d (ti ho gia' scritto su discord infatti) ripropongo qua quello che ho scritto a lui

"ho letto i tuoi report ed effettivamente farle in gruppo è una cazzata, (per lo meno le basse) ammesso e non concesso però che si guadagni poco in tanti.

secondo me essendo il bardo creato per fare solo i mostri delle mappe e totalmente inutile nel resto del mondo
bisogna capire come fixare sta cosa
non i mostri di per se, che è giusto siano strutturati IMHO su attacco/difesa delle skill bardo"

**Comment by BardoMars** [comment]
poi ci torneremo, ora devo testare le mappe alle lost. L'esperienza con la mappa 5 è stata catastrofica, ragionandoci a posteriori forse solo per la combinazione di mostri messi insieme

**Comment by morpheus8888** [comment]
le mappe hanno uno spawn casuale di mostri (quindi a volte potrebbero essere tutti gazer, a volte tutti diversi) questa cosa mi sembrava carina per rendere le mappe tutte diverse da fare, altrimenti sarebbero tutte uguali o no?

**Comment by morpheus8888** [comment]
![image](https://user-images.githubusercontent.com/49568239/148586014-f5dc2b1c-c8fa-4f4a-b4c9-281f9d8ef6b6.png)
 non so se ci capisci, era per comunicarti i gruppi che ci sono attualmente

**Comment by BardoMars** [comment]
mappa 6, in compagnia di altri due (incaricati da humilty di testare qualcosa sulle mappe)
MOSTRI:
Collector of Souls (CoS*) peace 89 provo 84 discord 87
pacificato in media al 8/9 tentativo, provocato in media 7/8, non impossibile, forse un po difficile ma ci sta

titan peace 87% provo 88% discord 90%, 
pacificato al 8/9 anche lui, sono riuscito a provocarlo una volta al 1/o non son riuscito a fare una media

cyclopean warrior peace 83% provo 88% discord 80%
hanno dovuto ucciderlo mentre facevo gli altri test non sono riuscito ancora a testarlo

ciliegina sulla torta il mostro invisibile, non ho potuto prenderne i valori.
sono riuscito a pacificarlo forse una volta ma non ricordo poichè era un'orgia di sangue e fughe
un tank e due maghi uno a curare e l'altro a sparare, non siamo riusciti a togliergli neanche 1/5 di vita
gli ho provocato contro il CoS*, il mostro invisibile l'ha fraggato in pochi secondi

**Comment by BardoMars** [comment]
> ![image](https://user-images.githubusercontent.com/49568239/148586014-f5dc2b1c-c8fa-4f4a-b4c9-281f9d8ef6b6.png) non so se ci capisci, era per comunicarti i gruppi che ci sono attualmente

ho visto ora, capisco!

**Comment by morpheus8888** [comment]
il mostro invisibile era un bug, fixato al prossimo riavvio

**Comment by morpheus8888** [comment]
chiudo questa, troppi cambiamenti, ne apro un'altra per chi vuole ritestare
