### ISSUE TITLE
Sacche (Bag e Backpack)

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#566]
Riporto una proposta di Herland fatta su ds
![Screenshot_20220102-195320_Discord.jpg](https://user-images.githubusercontent.com/83860614/147886349-2ccab437-2698-44a2-92f2-c971cac5f510.jpg)

**Comment by morpheus8888** [comment]
per velocizzare che si intende? qual è il problema che rallenta?

**Comment by daffy55** [comment]
Chiedi ad Herland

**Comment by morpheus8888** [comment]
fatte delle modifiche
