### ISSUE TITLE
Sextant non visibile

### ISSUE THREAD

**Issue by Lollo336** [uomars/UOMars#567]
Ciao a tutti, ci sono problemi con l'uscita dalla barca, cioè la passerella ti riporta dentro la barca invece di mandarti sul porto.
Come detto da legil @daffy55 bisognerebbe aumentare il range dei sextant

Spero sia chiaro e in caso scusate la poca chiarezza

Grazie ancora a tutti voi per il lavorone che state facendo

**Comment by morpheus8888** [comment]
la passerella non va doppio cliccata ci devi andare sopra

**Comment by kentar91** [comment]
> Ciao a tutti, ci sono problemi con l'uscita dalla barca, cioè la passerella ti riporta dentro la barca invece di mandarti sul porto. Come detto da legil @daffy55 bisognerebbe aumentare il range dei sextant
> 
> Spero sia chiaro e in caso scusate la poca chiarezza
> 
> Grazie ancora a tutti voi per il lavorone che state facendo

se quello che abbiamo visto prima ho corretto.

**Comment by kentar91** [comment]
@gmocciaro ti ricordi quando avete provato le barche che navigavano sotto i ponti? L'item del molo è rimasto con quella caratteristica e appena qualcuno sbagli ad attaccare attraversa il molo r si porta con sé sestanti e player hahahaha
È un ottima trappola ma puoi rimettere i moli non navigabili 
(Mi ha detto @daffy55 di riferirtelo, quindi prenditela con lui )

**Comment by daffy55** [comment]
Eravamo ad Order e avevamo testato con gli item del porto, se ti serve ti ridò gli id

**Comment by morpheus8888** [comment]
c'è già un git dedicato al bug della barca sul molo
