### ISSUE TITLE
SUMMON SUI CANCELLI - si avete letto bene

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#570]
Se summoni qualcosa sui cancelli crasha il server

la vera domanda e': perche' minchia uno deve summonare un evocazione sui cancelli?

misteri dei player, dal vangelo secondo UoMars

**Comment by gmocciaro** [comment]
summoni intendi tramite .petlist o le spell? il problema è il summon non il cancello

**Comment by daffy55** [comment]
Summon del mago

**Comment by gmocciaro** [comment]
allora passo la palla ad @Ale1991

**Comment by Ale1991** [comment]
fixato
