### ISSUE TITLE
frag da nudi

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#572]
ale mettiamo che ogni pezzo dell'armatura mancante fa fare 10% di danno/cure in meno? la gente fragga nuda e' inguardabile

**Comment by lyon1235** [comment]
Uppo è una cosa che già su mars 1 succedeva

**Comment by Ale1991** [comment]
fatto, si perde il 10% del danno per ogni pezzo di armor mancante (i pezzi totali sono il 6)
