### ISSUE TITLE
bug mob fauna

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#575]
tutti i mob fauna con ctrarity non classificata nascono con 0hits e 1str, ad esempio l'hell cat

**Comment by Ale1991** [comment]
normale... non classificati sono tutti i mob del mondo tranne quelli con ctrarity, pertanto vita e altre proprietà vanno assegnate nel rispettivo costruttore lato codice @kentar91

**Comment by kentar91** [comment]
fatto
@daffy55 verifica appena puoi

**Comment by kentar91** [comment]
Ovviamente devono prima patchare

**Comment by kentar91** [comment]
menomale che è stato risolto perchè ho rischiato di bruciare molti player oggi
