### ISSUE TITLE
tinkergoldentool

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#585]
se si lavorano i powderedgold (golden scraps) si eredita la flag (in teoria looted se c'è), se invece si crea dall'oro anche li si eredita la flag ma in questo caso dovrebbe essere crafted, perché l'oro si mina. 

In generale, il comportamento è di eredità della flag del materiale che si sta lavorando, sia per il prodotto che per l'avanzo.

**Comment by gmocciaro** [comment]
non ho capito cosa mi chiedi di fare, nel subbio ho aggiunto recently crafted ai soldi che vengono generati dal refiner, se non ho capito la richiesta riapri

**Comment by gmocciaro** [comment]
![Uploading image.png…]()
