### ISSUE TITLE
energy vortex

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#586]
Solitamente e' fermo, ma se castato sull'acido corre (dungeon centauri)
![image](https://user-images.githubusercontent.com/83860614/147954367-6e20d7b5-0515-46ce-b4bf-4fce2debdfac.png)

**Comment by morpheus8888** [comment]
lato codice non sono riuscito a trovare nulla che avesse a che fare con le superfici, fai qualche altro test, vedi se c'è qualche altra causa che può spiegare quel fenomeno

**Comment by daffy55** [comment]
non ho idea di come fare, sull'acqua non va e sulla lava neanche, l'acido e' calpestabile, forse per quello

**Comment by Ale1991** [comment]
fixato
