### ISSUE TITLE
problema di descrizione nel gump

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#589]
![image](https://user-images.githubusercontent.com/49568239/147961124-f0e7b612-5e3f-4ecf-b030-7a17f7a58d1d.png)

**Comment by gmocciaro** [comment]
e che posso farci? trovare il messaggio con i puntini e se ci passi sopra con il mouse ti da il messaggio intero

**Comment by morpheus8888** [comment]
a vedere il gump mi sembrava che fosse troppo sottile per la scritta, se è voluto ok
