### ISSUE TITLE
Customizzazione Casa Item e Container

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#592]
* Nella tab Customize si potrebbe togliere "add container for storage" che è già presente su "Storage"
* La funzione di Flip al momento ruota solo le i container, sarebbe utile poter flippare anche gli arredamenti (tavoli, sedie etc..)
* nella Tab Information viene riportato il numero di oggetti lokkati ma non il "massimo" di oggetti lokkabili (si potrebbe aggiungere un /valoreMassimo)

**Comment by gmocciaro** [comment]
il flip non funziona su molti items, poi la gente stressa che non gli funziona e pensa sia buggato, io non posso sapere su quali funziona e quali no

**Comment by gmocciaro** [comment]
rifatto tutto il gump da zero
