### ISSUE TITLE
fare il comando .hide

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#593]
fare il comando .hide che nasconde oggetti e player, come era su venus. 
Il mobile deve rimanere nascosto per X minuti, tipo 5
l'oggetto a terra item, per x minuti
l'oggetto in borsa fino a quando non si chiude e si riapre

**Comment by giga487** [comment]
È un operazione molto interessante. Ma suppongo che sia più semplice fare lato server che client. È una cosa che può servire, non so bene a cosa. Utile quasi quanto l item che fa da discoteca che scripto stanotte

**Comment by daffy55** [comment]
> fare il comando .hide che nasconde oggetti e player, come era su venus. 


Ma così eviti il bodyblock

**Comment by giga487** [comment]
Come funziona hiding? Fa fare body block?

**Comment by daffy55** [comment]
> Come funziona hiding? Fa fare body block?

No

**Comment by giga487** [comment]
E allora...si farà simile

**Comment by daffy55** [comment]
Ma che senso ha?

**Comment by giga487** [comment]
Guido vuole fare un torneo di nascondino

**Comment by morpheus8888** [comment]
il .hide deve essere una cosa esclusivamente grafica, non deve avere nessun impatto sul gameplay, esempio bodyblock @giga487

**Comment by giga487** [comment]
S, lo so, Avevo capito. Tu stavi parlando del ,Hide di injection.

**Comment by daffy55** [comment]
> S, lo so, Avevo capito. Tu stavi parlando del ,Hide di injection.

Il ,hide toglieva il bodyblock. Qui nom lo deve fare

**Comment by giga487** [comment]
Impossibile.

**Comment by thepatriot87** [comment]
se lo fate chiamatelo diversamente che .hide é giá un comando da gm
