### ISSUE TITLE
bug lago lost land

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#597]
![image](https://user-images.githubusercontent.com/83588629/147992302-e25b0fc7-6426-4dcf-b163-d9fb93484b31.png)
riesci a farmi le sponde "piatte"? si incastrano i pack horse

**Comment by daffy55** [comment]
si incastrano ovunque, ma io ci pesco tutti i giorni basta fare un passo indietro, dovrei rifare tutte le coste dove ci sono i pesci, evitamelo, non e' cosi' fastidioso

chiudi quando hai letto
