### ISSUE TITLE
bug disguise kit

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#599]
![image](https://user-images.githubusercontent.com/83588629/147994675-0b9bb3a3-d953-4161-8417-4b10259d540f.png)

ti trasforma in una torcia e ti setta cantwalk true.... l'unico modo per uscire da quello stato e fare nuovamente click su un altro disguise... ovviamente quello di prima scompare

**Comment by morpheus8888** [comment]
potrei farlo a consumi, se no così è finisce troppo subito

**Comment by morpheus8888** [comment]
ho messo il comando
