### ISSUE TITLE
peso ladro e avviso 

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#607]
il ladro puo' rubare troppa roba senza uscire dall'hiding ruba stack da 100 reag a tipo senza mai disiddarsi, mettere almeno una scritta che il ladro ti ha rubato
perche' se no non se ne accorge nessuno

**Comment by morpheus8888** [comment]
https://uomars.it/bible/ladro/

**Comment by morpheus8888** [comment]
proponi il rework

**Comment by daffy55** [comment]
> il ladro puo' rubare troppa roba senza uscire dall'hiding ruba stack da 100 reag a tipo senza mai disiddarsi, mettere almeno una scritta che il ladro ti ha rubato

l'hai testato?

**Comment by morpheus8888** [comment]
si, ulteriori test sono sempre benvenuti

**Comment by daffy55** [comment]
allora non so cosa dirti, a me sembra esagerato, come a tutti

**Comment by morpheus8888** [comment]
io ho testato il funzionamento, non il bilanciamento, proponete il rework e lo applico,

**Comment by morpheus8888** [comment]
per il momento chiudo per le modifiche fatte, in caso di sbilanciamento, riaprite direttamente un altro git
