### ISSUE TITLE
Scudo senza Durability comprato su Vs (ma non sanno da chi)

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#610]
![image](https://user-images.githubusercontent.com/83860614/148093673-2fce0614-0f83-4080-b8fa-48316a49a526.png)

**Comment by daffy55** [comment]
@Ale1991 aggiungo una cosa

quest'armatura la uso da giorni, la tolgo e la metto, non la tengo sempre su, oggi mi e' sparita dal durability dai guanti ma se faccio il nuovo comando la vedo
![image](https://user-images.githubusercontent.com/83860614/148216623-fb7931f3-1c28-48ee-8a80-3de48b67e423.png)

**Comment by Ale1991** [comment]
fixati.... tutti gli oggetti che non hanno piu durability si distruggeranno appena verranno colpite
