### ISSUE TITLE
Campo Orchi Lost Land

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#611]
4 minuti per farlo, chest da ultimo boss di hytloth, come mai? i pk e' tutto il giorno che sono li a farmare
(non parlo degli scrap ma dei 150 item speciali da craft, dei reagenti pagani e degli item che spawnano dentro la bosschest)

l'ho disattivato

**Comment by kentar91** [comment]
Rimossi chest boss e cambiate le dinamiche ... Fammi sapere se ti piace così 

Lo scopo è che 

goblin 1 persona
ophidian 1-2 persone
terathan 2 persone
papua 3 persone 
delucia 3-4 persone

**Comment by daffy55** [comment]
Dopo verifico le casse, perché a differenza delle boss chest le lockpicker chest erano molto povere di contenuto, però devono sempre essere bilanciate in base al tempo che uno ci impiega

**Comment by kentar91** [comment]
più persone ci vuole a fare il mini dungeon e piu' la cassa e' piena

**Comment by daffy55** [comment]
Li hai fatti bardabili? (Non è polemica è solo per sapere cosa dire visto che me lo hanno chiesto)

**Comment by kentar91** [comment]
non ancora

**Comment by kentar91** [comment]
mi apro un issue a riguardo..
