### ISSUE TITLE
Mappe del tesoro

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#612]
C'è qualcosa da cambiare, non riesco da solo a testare tutto, ma c'è da fermarle un attimo e ragionare su cosa vogliamo fare.
Nessuno le fa col bardo, si mettono in gruppi per farle, cosa che a me non dispiace (mi diverto anche io)
Ma quelle di 3, 4 e 5 devono essere più difficili da fare col pg e non devono poter essere fatte in solo. Buffate i mostri. Abbiamo uno shard di milionari xD

**Comment by daffy55** [comment]
buffa

> la mappa di 3, mi hanno chiesta di lasciarla relativamente semplice, ovvero un bardo deve potersela fare da sola, mentre 4 e 5 devono essere toste, se così non lo sono buffo ulteriormente

il problema e' che non ho ancora visto 1 bardo farla
le fanno tutte coi pg in solo o in 2
buffa

**Comment by giga487** [comment]
Io temporeggerei, ma i bardi esistono?

**Comment by morpheus8888** [comment]
usiamo il gitunico
https://github.com/uomars/UOMars/issues/565
