### ISSUE TITLE
bug barche

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#614]
![image](https://user-images.githubusercontent.com/49568239/148130940-e6f02a24-b23f-4288-805c-c81c3aa72d9a.png)

si può spiegare con quel codice che facemmo per far passare la barca sotto i ponti? forse l'abbiamo lasciato per sbaglio?

**Comment by gmocciaro** [comment]
@daffy55 hai usato i famosi tile vietati dal congresso di ginevra?

**Comment by morpheus8888** [comment]
credo che quando hanno deciso di non usare più i ponti implicitamente hanno riusato tutto, secondo me dobbiamo togliere noi i tiles da codice @gmocciaro

**Comment by daffy55** [comment]
> credo che quando hanno deciso di non usare più i ponti implicitamente hanno riusato tutto, secondo me dobbiamo togliere noi i tiles da codice @gmocciaro 

Anche questo è falso, per non patchare voi due avete VOLUTO che vi dessi gli id dei porti così testavamo veloci
ASSUMETEVI LE VOSTRO RESPONSABILITÀ
@morpheus8888 @gmocciaro
