### ISSUE TITLE
zona calpestabile centauri

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#618]
![image](https://user-images.githubusercontent.com/83588629/148142694-c1425a48-c34d-4ea1-99ce-d65a37ea98df.png)

dato che alcuni si teletrasportano in questa montagnola che non è accessibile a piedi, ti chiedo di renderla accessibile da chiunque..
ho visto alcuno entrare li con la magia e da fuori castare al kraken...

**Comment by daffy55** [comment]
dovrebbe gia essere accessibile dalla patch grafica di ieri sera

**Comment by daffy55** [comment]
come non detto, c'erano tile invisibili, ora e' accessibile a tutti, dalla prossima patch
