### ISSUE TITLE
Gate Museo Pryma

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#621]
Onde evitare che la gente scappi dentro se vede pk, (perche' io posso evitare che si entri sotto attacco, ma se li vedo prima che mi targhettino posso fuggirci dentro) si potrebbe fare che se la città e' sotto attacco il gate si disabilita.
anche perche' il gate per cove e' vicino all'ingresso e per entrare io devo cmq correre verso gli attaccanti, ma il gate per il museo e' dalla direzione opposta, quindi piu' indicato per la fuga 

a voi l'ardua sentenza

**Comment by gmocciaro** [comment]
non so onestamente, ma il gate non si può fare che non è attraversabile i combat dal gioco? io ricordo di si

**Comment by daffy55** [comment]
sisi c'e' e funziona, ma funziona, ovviamente, solo in combat. 
![image](https://user-images.githubusercontent.com/83860614/149096672-c88c99ee-a15b-4ccc-a51e-08447300dded.png)

Quello che intendevo io e' che se un niubbo vede i pk, cercherà di scappare verso il museo, freccia **verde**, ed evitare quindi di essere targhettato (no combat ed entra nel gate) , piuttosto che correre verso cove, la freccia **gialla** dove ha un rischio piu' alto di essere targhettato, entrare in combat e non poter entrare a Cove.

Io lascerei la fuga verso Cove (gialla), perche' il rischio di entrare in combat e' alto, ma vorrei evitare di fuggire verso il museo (verde) dove il rischio di essere targhettato (e quindi di entrare in combat) e' praticamente nullo


![image](https://user-images.githubusercontent.com/83860614/149095294-04cf2b55-0584-40c3-9b61-33d80598678a.png)



la mia richiesta e' solo per evitare che i pg siano 1000% safe, puoi scappare a cove, ma stai correndo in bocca ai pk, a tuo rischio e pericolo

**Comment by gmocciaro** [comment]
come si chiama il gate che usate? magari posso aggiungere una flag che fa un check sull'evento della città in cui si trova

**Comment by gmocciaro** [comment]
done!

![image](https://user-images.githubusercontent.com/12816659/149157897-67ffdca2-6f70-454d-b597-94d792c6d1cb.png)
