### ISSUE TITLE
possibile bug al gate non worker

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#624]
segnalazione krachen

ti fa diventare il pg femmina

cerco di replicarlo

**Comment by thepatriot87** [comment]
ho provato a replicarlo ma nulla.

il pg aveva settato female true, gliel'ho settato false e fatto riloggare ma rimaneva femmina

**Comment by daffy55** [comment]
cambia il bodyvalue? maschio 400, femmina 401

**Comment by morpheus8888** [comment]
per il momento chiudiamo
