### ISSUE TITLE
testo errato tutorial suicide

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#631]
![screenshot_2022-01-05_03-47-02](https://user-images.githubusercontent.com/17385984/148237387-12c5d7e8-7b15-46da-8f93-d3842c4c73ea.png)

**Comment by thepatriot87** [comment]
scrivere di non fare ghosttravel

**Comment by thepatriot87** [comment]
scrivere anche di andare vicino gli omini (healer)nella stanza successiva

**Comment by morpheus8888** [comment]
fatto
