### ISSUE TITLE
testo e traduzione errati a inizio tutorial

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#632]
![screenshot_2022-01-05_03-54-34](https://user-images.githubusercontent.com/17385984/148238432-e975a3cb-8b9b-4d02-ad22-52fc1132cb54.png)

**Comment by kentar91** [comment]
si bugga sempre quello spawn di merda

**Comment by kentar91** [comment]
ora dice 
Follow the blue gate instructions to continue with the tutorial
e poi
To exit, use the brown gate
