### ISSUE TITLE
Entrata meridian full skill 

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#633]
Buongiorno 
Ormai è pratica comune di alcuni entrare dentro dentro meridian full skill per farmare 700k di exp per comprare il deed per fullare un secondo pg.
Allora due sono gli spunti di analisi 

1 è troppo difficile ( va via troppo tempo)da expare un pg partendo da 100 punti skills
2 va assolutamente vietato l’entrata ai pg full dentro meridian per expare e fare soldi senza perdere niente.

**Comment by kentar91** [comment]
@morpheus8888 potremmo fare che solo gli young possono entrare li? che ne pensi?

**Comment by thepatriot87** [comment]
se il deed si potesse redimere una volta max al mese (come quello dei tutorial ogni 6 mesi) ?

**Comment by thepatriot87** [comment]
cosí toglieresti la frustrazione a chi non vuole farmare ma comunque impediresti di floodare il server di pg full

**Comment by lyon1235** [comment]
> se il deed si potesse redimere una volta max al mese (come quello dei tutorial ogni 6 mesi) ?

Potrebbe essere una soluzione

**Comment by morpheus8888** [comment]
@kentar91  meridian è per farmare un pg e per rifare un po' di soldi dopo un po' di tempo che si è smesso. La soluzione per quanto grossolana potrebbe essere che se hai TOT soldi, conteggiando anche quelli a casa non ci puoi andare se sei full, ma se troviamo una soluzione migliore è meglio.

Mi serve capire, qual è la differenza fra portare il pg full e comprare il deed invece che portare direttamente il pg da fullare? quanto tempo si risparmia così?

**Comment by thepatriot87** [comment]
@morpheus8888 questa non è male , almeno la usano soltanto quelli per rifarsi l'equip facilmente ( che poi era l'idea iniziale)

**Comment by morpheus8888** [comment]
messe restrizione al restock
