### ISSUE TITLE
.reset 

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#646]
si può fare il .reset sul pg (non sull'account) una volta a settimana

**Comment by gmocciaro** [comment]
questo devo farlo ancora? secondo me creiamo solo lamentele

**Comment by morpheus8888** [comment]
il problema si presenta sul worker principalmente, lì si deve fare per forza, poi scegli tu se farlo generico o solo worker

**Comment by gmocciaro** [comment]
facciamolo solo sul worker in caso

**Comment by gmocciaro** [comment]
done
