### ISSUE TITLE
[Skills] "You need at least 1 skill-point to do that!" - Suggerire quale skill

### ISSUE THREAD

**Issue by andreadellacorte** [uomars/UOMars#65]
Quando si prova a usare una skill e non la si ha esce un error the dice "You need at least 1 skill-point to do that!"

![image](https://user-images.githubusercontent.com/295683/117543235-cfacaf00-b013-11eb-92eb-fced7b4fe9c3.png)

Dovrebbe dire quale skill e' necessaria (tra l'altro, non sono riuscito a trovare fishing - forse e' harvesting?).

**Comment by morpheus8888** [comment]
fatto
