### ISSUE TITLE
Select next Rossi 

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#651]
Buongiorno 
Con il mio pg rosso non riesco funziona il comando select next da client 
Se metto hostile e player mi targhetta tutti rossi blu grigi chaos ecc. si può fixare in qualche modo ?

**Comment by daffy55** [comment]
Succede anche ai pg grigi

**Comment by giga487** [comment]
La mia proposta è:

SelectNext Hostile, attacca tutto quello che non è del tuo colore. Potrebbe andare bene?

**Comment by lyon1235** [comment]
Si sì assolutamente

**Comment by giga487** [comment]
La logica implementata è la seguente:
I rossi ruoteranno i target blu, grigi e fazionati.
Gli order ruoteranno i target blu, grigi, fazione opposta e pk.
I Chaos ( QUANDO BLU ) ruoteranno i target blu, grigi, rossi e fazione opposta.
I Grigi ruoteranno i target blu, grigi, rossi. ( Da notare che i grigi vedono le fazioni come blu ). ( confermatemi questa cosa dei grigi, non sono riuscito a testare completamente )
