### ISSUE TITLE
problema npc banca pryma e ladri

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#653]
![screenshot_2022-01-06_09-30-53](https://user-images.githubusercontent.com/17385984/148447738-d8fbd548-a771-4229-a2a5-8ad38e003fd9.png)

si mette a parlare anche con gli stealther

**Comment by morpheus8888** [comment]
cancellalo direttamente quel coso, che da solo fastidio insieme al tipper

**Comment by thepatriot87** [comment]
disattivati spawner
