### ISSUE TITLE
x guido attivazione casa

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#654]
x fever seven

coordinate 2925 3775
![immagine](https://user-images.githubusercontent.com/17385984/148459053-b5d7cec6-980c-4e65-9cc1-83e7ff897886.png)

**Comment by daffy55** [comment]
Dopo la faccio

**Comment by daffy55** [comment]
@morpheus8888 a meno che non vuoi farla te

**Comment by daffy55** [comment]
fatta io, chiudo
