### ISSUE TITLE
info su talismano / probabile bug

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#655]
questo player mi ha segnalato che aveva il talismano a 0
nel controllare ho visto che il talismano aveva un valore negativo
![image](https://user-images.githubusercontent.com/83588629/148468869-07ba8fe6-608c-497c-ab0f-b7ba299ccf50.png)

dandogli le mele ho notato che il talismano aumenta di efficacia ma non aumentava il tempo di "azzeramento"
appena finito le mete il talismano cominciava a "decayare"

è passato un altro player e per controllare le differenze ho controllato le props del talismano ed è ho trovato questo valore grande
cosa vuol dire?  ti faccio presente che questo era young
![image](https://user-images.githubusercontent.com/83588629/148468901-97c00be4-67d6-44fd-8a53-b3cd3245a2e2.png)

**Comment by gmocciaro** [comment]
allora il valore negativo è un bug 100%
il valore grosso è voluto, il cap del talismano (per garantire i 10 giorni) è di 14400, e il fatto che lo ha superato è pure un bug, ora fixo tutto

**Comment by gmocciaro** [comment]
fixato
