### ISSUE TITLE
bug? tavoli da lavoro

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#658]
![image](https://user-images.githubusercontent.com/83588629/148476866-47daf4bd-4bba-48dd-ab8f-f1682e3f7ff1.png)

quando usi la gemma per comprare le risorse che mancano ti dice che il sistema non è inizializzato

**Comment by gmocciaro** [comment]
ma sei in locale? non esiste il .vs se dice quello

**Comment by kentar91** [comment]
ero su quello ufficiale, cercandolo sul .vs c'erano

**Comment by gmocciaro** [comment]
purtroppo ora non posso verificare, stasera quando torno ci guardo

**Comment by gmocciaro** [comment]
fixed
