### ISSUE TITLE
SPAWN LOST

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#660]
Ragazzi c'è lo shard aperto ( 5 player on) e ci sono gli spawn cosi
![image](https://user-images.githubusercontent.com/91663610/148503550-1bd1e8e1-bdcf-43b0-9b24-4c3991031d8e.png)
![image](https://user-images.githubusercontent.com/91663610/148503565-114bec98-2813-4853-8374-7888405f8100.png)
![image](https://user-images.githubusercontent.com/91663610/148503579-b749d4b4-b029-4564-a737-153091d4e447.png)
![image](https://user-images.githubusercontent.com/91663610/148503603-6524f2bc-5ada-428c-a0be-4180616a38ba.png)
![image](https://user-images.githubusercontent.com/91663610/148503609-7ee9cc72-1e82-4e54-a909-043189b894ab.png)

**Comment by kentar91** [comment]
Si, ne ho discusso con Alessio e al momento è inevitabile

**Comment by daffy55** [comment]
@SampinoInfernal te hai problemi seri
