### ISSUE TITLE
ladro può rubare agli young in casa

### ISSUE THREAD

**Issue by Vandervalth** [uomars/UOMars#665]
Un ladro Norberto mi ha detto che ai player young in Pryma gli dice che non può rubargli (appunto per lo status young) ma, entrando in casa di uno young, può rubargli quindi, se è voluto che un ladro non può rubare agli young in assoluto, settare le region "case" come Pryma.

**Comment by morpheus8888** [comment]
fixato, i ladri non possono rubare nelle case per ora
