### ISSUE TITLE
chest per le risorse della città

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#666]
tutti i cittadini devono poter aprire quel chest, ma nessun puoi mai prelevare le risorse

quando il mayor (sindaco è null) tutti possono depositare le risorse lì dentro

quando il mayor è assegnato nessuno può più depositare le risorse lì dentro

**Comment by Vandervalth** [comment]
mi piace come compromesso! :) io cambierei comunque il messaggio come da mio issue (non sapevo ce ne fosse già uno attivo)

**Comment by gmocciaro** [comment]
perchè devi dare la possibilità di aprirlo rischiando di causare bug? che devono vedere?
