### ISSUE TITLE
.massmove "numero"

### ISSUE THREAD

**Issue by Vandervalth** [uomars/UOMars#667]
Molti lavoratori (finora in 3 pages differenti) mi chiedono il comando .massmove "numero" per massmuovere, ad esempio, 100 picche su 300 in una sacca. Potrebbe essere implementato visto che è ritenuto utile da molti players.

**Comment by giga487** [comment]
Ok, si può fare.

**Comment by giga487** [comment]
Nella prossima patch c'è.
