### ISSUE TITLE
loot treasure map

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#668]
direi di allineare i chest dei dungeon (solo per gli scrap) a quelli delle mappe.
mi spiego meglio:
la cassa5 di hyth dà 20k di scrap
la cassa7 delle mappe del tesoro ne dà 120k....
è vero che nelle casse dei dungeon trovi cavalcature che puoi rivendere e altre cose... ma forse è un pò too much...
@morpheus8888 che ne pensi?

**Comment by morpheus8888** [comment]
per il momento no, considerando anche il rischio. Considera che essere in mezzo alla strada significa essere predabili sempre e comunque, mentre lì in fondo è più difficile essere gankati. 
In più i mostri delle mappe non danno soldi. La mappa di 7 in generale deve essere più difficile di un boss di quinto, dai vari bilanciamenti la faremo più lunga e difficile.
