### ISSUE TITLE
nerf tracking

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#669]
alcuni player mi riferiscono che con 100 tracking traccano da papua a delucia.... se non ricordo male il track massimo è 400 tile... penso sia il caso di "capparlo" a poco meno di 70

che  ne pensi? @morpheus8888

**Comment by giga487** [comment]
Secondo me è troppo poco 70

**Comment by kentar91** [comment]
una schermata quanti tile ha?

**Comment by daffy55** [comment]
O 25 o 35, non ricordo bene

**Comment by SampinoInfernal** [comment]
Tracking è vergognosa
Noi con il pk andiamo in giro a traccare gente DOVUNQUE ( semrba davvero che io giri con il gm e dica dove sta la gente per quanto è sgrava)

**Comment by kentar91** [comment]
della serie: con la arcane light non serve il gm con il whofast XD

**Comment by daffy55** [comment]
Su felucca non la toccherei, la nerferei su trammel

**Comment by morpheus8888** [comment]
si la nerfo a trammel da 400 a 200
