### ISSUE TITLE
risorse per riparare i cancelli delle città

### ISSUE THREAD

**Issue by Vandervalth** [uomars/UOMars#670]
Considerando che da .city di pryma la porta ha fallito a ripararsi 66 volte e considerando che Saro, cioè uno dei worker più attivi quindi "esperti", probabilmente vedendo il messaggio spammato in automatico mi abbia chiesto come si faccia a rigenerare le porte..... Credo che la soluzione più facile sia questa (per far sapere a tutti, anche ai meno esperti, come si riparano i cancelli).

SOSTITUIRE IL MESSAGGIO SPAMMATO IN AUTOMATICO: 

The city has not enough resources to repair Nice Gate! 

CON QUESTO NUOVO MEX:

The city has not enough resources to repair Nice Gate! Write .city and go to RESOURCES! Add the missing resources in the CITY RESOURCES CHEST (you can find it in the Bank room) in order to repair the doors.

L'ho scritto forse troppo lunghetto, magari si può accorciare ma far capire con il nuovo messaggio anche il COME si riparano le porte che evidentemente nessuno lo sa.

**Comment by Vandervalth** [comment]
![repair fail](https://user-images.githubusercontent.com/90780786/148575658-0b46f8ff-2329-4654-a2e2-20dd86caeea3.jpg)
[

**Comment by Vandervalth** [comment]
AGGIORNAMENTO: Saro non riesce a mettere i materiali nella chest, gli dice questo errore: "Only authorized people can insert items in the city resources chest" Solo il sindaco può inserire materiali nella chest? Non ricordo

**Comment by daffy55** [comment]
Mi piace il messaggio, non so come avete gestito il problema su Uomars1

Considera che lo stesso problema sta mattina lo avevano tutte le città

**Comment by Vandervalth** [comment]
Ergo il problema è diventato: gestire la riparazione dei cancelli in assenza del sindaco. Alcuni possibili soluzioni: fare in modo che tutti i worker di una determinata città possano inserire risorse OPPURE in assenza di sindaco si riparano in automatico senza bisogno di risorse. Ovviamente sono soluzioni al volo e banali, non ricordo neanche se sia un bug o meno il fatto che un worker non possa metterci risorse! :P

**Comment by daffy55** [comment]
Mi piace che chiunque possa mettere dentro risorse, non penso rompa qualcosa nelle meccaniche

**Comment by morpheus8888** [comment]
https://github.com/uomars/UOMars/issues/666 @Vandervalth @daffy55

**Comment by daffy55** [comment]
> https://github.com/uomars/UOMars/issues/666 @Vandervalth @daffy55 

Perché mi hai taggato?

**Comment by morpheus8888** [comment]
> > #666 @Vandervalth @daffy55
> 
> Perché mi hai taggato?

per farti leggere la possibile soluzione proposta già da me nel git precedente

**Comment by thepatriot87** [comment]
ma hanno ancora senso i cancelli ? ci sono le guardie, l'evento alle cittá é disattivato , c'é la scorciatoia sempre aperta...

**Comment by daffy55** [comment]
> ma hanno ancora senso i cancelli ? ci sono le guardie, l'evento alle cittá é disattivato , c'é la scorciatoia sempre aperta...
> i worker si possono settare immortali

Certo sono fondamentali

**Comment by thepatriot87** [comment]
quella sotterranea di pryma che sbuca alla montagna
non dico che non servono per sempre , dico per ora

**Comment by daffy55** [comment]
ma quella e' solo uscita, i ladri da li non possono entrare

**Comment by gmocciaro** [comment]
fixed la cosa principale del thread, ora tutti possono metere roba nella chest se non c'è il sindaco
