### ISSUE TITLE
spawn nuovi player

### ISSUE THREAD

**Issue by Vandervalth** [uomars/UOMars#671]
Se possibile, spostare i gate dei tutorial WORKER e NON WORKER nella stessa stanza in cui spawnano i nuovi player. Dico questo perchè, nel tempo, ho fatto una prova: 2 player nuovi (per nuovi intendo primo accesso), non "accogliendoli" si sono disconnessi alla stanza di Babbo Natale, per altri 2 player nuovi, sempre "bloccati" nella stanza di Babbo Natale, sono uscito allo scoperto accogliendoli e informandoli che devono fare i 2 tutorial per iniziare a capire le meccaniche base. Così facendo, hanno iniziato a fare i tutorial.

Anche se sembra assurdo che i player non trovino il tragitto verso i tutorial, in realtà è così perchè essendo nuovi si sentono spersi e non sanno che devono fare (nonostante i gate dei tutorial si trovino alla stanza immediatamente successiva e a quella dopo).

Questa è una cosa totalmente opzionale che, se si fa, è meglio per non rischiare di perdere qualche nuovo player che si disconnette alla stanza di quel fottuto Babbo Natale! XD

**Comment by morpheus8888** [comment]
concordo, rimuovetela se potete il prima possibile, anche perché è finito

**Comment by Saro-UOMars** [comment]
https://www.105.net/news/tutto-news/1302144/lalbero-di-natale-va-disfatto-il-2-febbraio-non-il-6-gennaio.html

**Comment by daffy55** [comment]
È gia stato rimosso, serve solo una patch grafica
