### ISSUE TITLE
Problemi by Kira

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#672]
Vi posto alcuni feedback da parte di un player abbastanza esperto

- Ladro pk ha ancora limitazioni tipo entrare città blu da rosso, usare le trappole che trovi nei chest da lockpiker. 
- Ladro generale non può aprire il ridgeback, non ho provato il giant beetle ancora ma penso sia uguale.
- I Pg settati (I) (non è una vagina) alle Lost, possono scappare dentro i gate per le worker e diventano invulnerabili anche se stavano sotto attacco da prima.
- Heaven Island - Fixata
- Pk hanno problemi con il sistema select next --> in fase di sistamzione by Giga Capo Ingegnere
- Wissare in qualche modo un ladro, magari con il poison quando scade il tick ALMENO uscire, con il quake quando lo hitti ALMENO uscire pure
- Aprire i tesori delle mappe anche da chi non ha tirato fuori il tesoro.
- Poter inculare le barche magari, dato che ne ho rubata una aperta, ma al massimo ho potuto nasconderla.
- Darmi 2kk

**Comment by morpheus8888** [comment]
1)il ladro pk non potrà mai entrare in città blu come i grigi e usare le trappole (lato codice creerebbe troppi problemi)
2) controllo
3) @kentar91 @daffy55 al gate fate che chi è sotto attacco non passa
4) ok
5) @giga487 guarda
6) no, le skill si caunterano con le skill, se vogliono detectare un ladro usano detect hidden altrimenti nisba, il mago non è gesu cristo
7) ci devo riflettere, non è facile soluzione, altrimenti passa qualcuno e ti si frega tutto, tipo ladro hiddato che aspetta che uccidi i mostri
8) le barche non devono poter essere rubabili, come hai fatto?
9) ti do 2kk e ti banno così non puoi usarli :D

**Comment by morpheus8888** [comment]
- fixato il problema dei ridgeback
- se si è in party con chi ha la mappa del tesoro si può aprire il chest

per gli altri problemi aprimi un git dedicato puntuale

**Comment by daffy55** [comment]
Ladro pk ha un vantaggio rispetto ai grigi, può rompere le porte
Appena fixiamo i gate dalle Lost Land chiudo il git (da fixare in entrambe le direzioni)

**Comment by giga487** [comment]
https://github.com/uomars/UOMars/issues/651#issue-1095306367
