### ISSUE TITLE
peso scraps

### ISSUE THREAD

**Issue by Vandervalth** [uomars/UOMars#673]
Mi ha chiamato via page Marchito e mi ha detto che, allo stesso peso, oggi portava 9k scraps mentre ieri 30k (ho chiesto conferma più volte e mi ha detto che fosse 100% sicuro di questo ma non posso sapere se è vero). 

Ad ogni modo, dal suo page mi sono ricordato che stamattina anche un altro di cui non ricordo il nome si era lamentato del peso degli scraps (mi pare ne aveva circa 1800 o 2200 e lo portavano a pesare più di 800). Non è un problema, è solo una riflessione/discussione da fare, ricordo che c'era una logica dietro il peso (grande) degli scraps ma non ricordo specificamente quale xD.

Inoltre, se quel che dice Marchito è vero, il peso è cambiato e, se nessuno lo ha cambiato, allora è un bug se invece è stato cambiato per un fix voluto allora gg (riflettere se questo aumento di peso o comunque il peso attuale degli scraps sia worth o meno).

**Comment by morpheus8888** [comment]
si è vero, ora sistemo. Perché si sta portando anche gli scraps dedicati al ladro, ora fixo
