### ISSUE TITLE
problema teleporter

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#677]
le watch tower all'interno sono vuote, questo fa si che se per sbaglio il gate di haven ti butta fuori puoi entrare dentro una torre.....

![image](https://user-images.githubusercontent.com/83588629/148622529-bf89694e-1112-41f8-97fb-d61a868216c8.png)

**Comment by kentar91** [comment]
riempile tutte con le montagne come hai fatto ad egitto

**Comment by daffy55** [comment]
non capisco come fai ad entrare dentro la torre, anche se riempio il bug lo fa cmq, e' un problema delle coordinate dello script, hanno mezzo Z 0, non so che farci

**Comment by giga487** [comment]
All'uscita da Heaven e dai dungeon Plus, si viene catapultati fuori in una zona non safe in base alla tua fazione. Le coordinate sono randomiche in un certo raggio. 

Penso che abbia probabilità simile al nulla, però è capitato. 

Ovviamente vengono fatti i test di can walk lato codice, e quel punto è effettivamente camminabile.


Bella la statistichica, no? eventi improbabili ma non impossibili.

**Comment by daffy55** [comment]
se e' random allora fixo io
