### ISSUE TITLE
RuneBook e Rune

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#679]
quando viene rimossa una runa dal Runebook questa diventa "recently looted" e quindi vieta il fasttravel non so se è voluto, io avviso...

**Comment by Saro-UOMars** [comment]
e a quanto pare la runa anche se "sbloccata" uscendo e rientrando si bugga e non fà più recallare, da un messaggio che dice "che non sono autorizzato ad andare in quel luogo"

**Comment by Ale1991** [comment]
fixato
