### ISSUE TITLE
Sconto Materiali Fuori Città

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#680]
Lo sconto che mi viene applicato sul consumo di pelli mi sembra sbagliato, per una full leather dentro città uso 490, fuori città uso 480, è meno dell'1% di sconto con "Bonus Risk +2" è corretto o no?

**Comment by Ale1991** [comment]
quel bonus cresce al crescere della gente che c'e' online...se e' cosi' basso e' perche non ci sono rossi o grigi che possono killarti

**Comment by Saro-UOMars** [comment]
penso che un minimo ci debba essere anche se nessuno è online poi boh

**Comment by morpheus8888** [comment]
@gmocciaro possiamo scrivere un qualcosa così ogni volta che ce lo chiedono lo possiamo dire? io lo scriverei direttamente nel bible se mi passi la formula

**Comment by Saro-UOMars** [comment]
> @gmocciaro possiamo scrivere un qualcosa così ogni volta che ce lo chiedono lo possiamo dire? io lo scriverei direttamente nel bible se mi passi la formula

si sarebbe ottimo.

**Comment by gmocciaro** [comment]
a Felucca sono massimo +20 con 10 nemici online (va scalando, quindi +10 con 5 nemici online, ma cappa a 20 anche con 2000 nemici online)
a Trammel sono massimo +50 con 10 nemici online (va scalando, quindi +10 con 5 nemici online, ma cappa a 50 anche con 2000 nemici online)

**Comment by morpheus8888** [comment]
per fare un esempio uno che ha talismano a 100 e crafting a 1, se ci sono 10 nemici online e sta a trammel, crafta con la ricetta al minimo giusto?

**Comment by gmocciaro** [comment]
cosa intendi la ricetta al minimo?

se uno ha talismano a 100 e crafting a 1, ci sono 10 nemici e sta a Trammel, ottiene +50 bonus, quindi è come se ha 51 di skill
