### ISSUE TITLE
Secure dentro casa

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#686]
in una casa, piazzare un secure al piano terra e poi andare al piano di sopra e mettere un secure alle stesse coordinate non te lo fa fare, come se non controllasse la Z

![Screenshot_20220108-191455_WhatsApp.jpg](https://user-images.githubusercontent.com/83860614/148655087-d2db7e68-8709-41ff-a99e-e83a5df6dea3.jpg)

@gmocciaro

**Comment by gmocciaro** [comment]
fixed
