### ISSUE TITLE
mi ricordi una cosa

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#687]
avevamo fatto un metodo per il prezzo di medio di mercato, dovevamo far uscire il prezzo medio di mercato sull'item, ma mi sa che non sta funzionando, tu ti ricordi come si chiamava?

**Comment by gmocciaro** [comment]
non lo abbiamo fatto più e non credo possiamo farlo perchè dentro server (items sta dentro server) non possiamo usare metodi di scripts, quindi dovremmo modificare ogni singolo item a mano

quindi anche se dovessi creare il metodo dentro CommonVariables, non potresti usarlo dentro items.cs
e se dovessi creare un metodo dentro server, non potresti avere la lista di item in vendita per lo stesso discorso
