### ISSUE TITLE
bug casa

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#689]
![image](https://user-images.githubusercontent.com/49568239/148660219-6914bc4d-ccd3-4712-b523-73ac96633ba2.png)

questo tizio non riesce a piazzare i secure in casa

**Comment by gmocciaro** [comment]
non c'è la region, è stata mappata male

**Comment by gmocciaro** [comment]
region fixata ma fa schifo sta casa, se la fixa @daffy55 è meglio

**Comment by daffy55** [comment]
> region fixata ma fa schifo sta casa, se la fixa @daffy55 è meglio

È gia in programma, se devi patchare oggi la fixo subito, avevo gia avvisato Oriente che avrei fixato il buco nel tetto

**Comment by daffy55** [comment]
fixata, chiudo
