### ISSUE TITLE
Craft Tools - Perchè?

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#690]
Perché la Piccozza, l'Accetta e la Pala hanno 100 usi a differenza del Coltello e del Falcetto che ne hanno 250? Costano la stessa quantità di materiale e raccolgono la stessa quantità per azione.

**Comment by gmocciaro** [comment]
è un bug che stiamo fixando, qui chiudo

**Comment by Saro-UOMars** [comment]
> è un bug che stiamo fixando, qui chiudo

Ah perfetto :D
