### ISSUE TITLE
casa senza porta

### ISSUE THREAD

**Issue by Vandervalth** [uomars/UOMars#697]
![casa senza porte](https://user-images.githubusercontent.com/90780786/148699330-b8da1bb5-9b47-4bd9-844b-3108f417d8ff.jpg)

**Comment by gmocciaro** [comment]
è buggato graficamente, non posso metterle

![image](https://user-images.githubusercontent.com/12816659/149027073-4bdd1702-8faf-475b-b72b-1b7a5f426cc5.png)

bisogna parlare con l'amico @daffy55

**Comment by daffy55** [comment]
Ah è gia fixato, prossima patch è up
