### ISSUE TITLE
Errori Traduzione Italiano

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#698]
House Gump sezione personalizzazione (cassapanche invece di casse) alcune poi vengono tradotte casse altre baule

**Comment by giga487** [comment]
Dovremmo vendere ad Amazon le nostre traduzioni, sono bellissime

**Comment by Saro-UOMars** [comment]
> Dovremmo vendere ad Amazon le nostre traduzioni, sono bellissime

XD, cmq uso questo post per continuare a mettere le segnalazioni

**Comment by gmocciaro** [comment]
> Dovremmo vendere ad Amazon le nostre traduzioni, sono bellissime

ha senso considerando che è amazon che le fornisce così

**Comment by Saro-UOMars** [comment]
l'item della sabbia è tradotta (minerale)
l'item del vetro è tradotto (lingotto)

**Comment by Saro-UOMars** [comment]
![image](https://user-images.githubusercontent.com/97031570/149023024-9280d921-11f8-4c7d-a792-dae858ae3f0c.png)

**Comment by Saro-UOMars** [comment]
La ROBE è tradotta in "Accappatoio" invece che in Tunica.
