### ISSUE TITLE
BUG Pet

### ISSUE THREAD

**Issue by FeverSeven** [uomars/UOMars#700]
Ho notato che c'è un po' di confusione sui vari animaletti che si trovano in giro.
Ci sono Grizzly Bear che possono essere tamati con 1 di taming, per altri serve 40.
Ho notato questo problema con vari animali,mi è capitato di trovare un coniglietto bianco e l'ho tamato, poi ne ho trovato un altro alle lost land e non era tamabile (dalla rabbia l'ho ucciso xD)

**Comment by morpheus8888** [comment]
ho controllato, il problema non è lato codice, deve essere successo qualcosa sugli spawner

**Comment by daffy55** [comment]
Penso che quelli spawnati prima della modifica lato codice hanno i vecchi settaggi.
Uccidili quando li trovi in giro, allena respawnano saranno a posto
