### ISSUE TITLE
Bug Rewards 

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#703]
Fa comprare reward coin infiniti
![image](https://user-images.githubusercontent.com/91663610/148774602-a1a36c52-18e6-440c-b2b7-593e96eed7d7.png)

**Comment by gmocciaro** [comment]
risolto da @Ale1991 credo?

**Comment by SampinoInfernal** [comment]
> risolto da @Ale1991 credo?

Si me lo ha risolto in live poi quando ha loggato
I capelli lux me li tengo maledetti
