### ISSUE TITLE
gate senza effetto grafico

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#705]
![immagine](https://user-images.githubusercontent.com/17385984/148778050-dde2af1d-69b9-46a5-8d65-f54350426390.png)

c'è un motivo o posso mettere il moongate? @daffy55

**Comment by daffy55** [comment]
e' pier che li ha piazzati per fare dei test, chiedi a lui

**Comment by kentar91** [comment]
era il gate per tornare indietro, nell'import ci siamo dimenticati di mettere lo statico associato
risolto
