### ISSUE TITLE
(forse) bug invulnerable

### ISSUE THREAD

**Issue by Vandervalth** [uomars/UOMars#708]
un tizio era alle LOST LANDS quindi invulnerable decade ma, per sbaglio, ha buttato a terra le pelli non potendole prendere più (quindi i contro dell'invulnerabile sono attivi anche alle lost lands nonostante tu non sia effettivamente immortale). Questa cosa è voluta o è un bug?

**Comment by morpheus8888** [comment]
voluta, ma può togliersi l'invulnerabile dove vuole, quindi se lo toglie anche lì e raccoglie
