### ISSUE TITLE
depositi fuori miniera

### ISSUE THREAD

**Issue by Vandervalth** [uomars/UOMars#709]
![image](https://user-images.githubusercontent.com/90780786/148817528-c147daee-4621-4cf8-a977-6ba948c6d391.png)

**Comment by Vandervalth** [comment]
depositi fuori miniera nelle lost land

**Comment by kentar91** [comment]
![image](https://user-images.githubusercontent.com/83588629/148860536-64f98a23-6847-42a6-8232-962c1fde91fe.png)
guarda di quanto usciva...

**Comment by Vandervalth** [comment]
wtf XD
