### ISSUE TITLE
Whip

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#711]
se rubo un animale con la whip non dovrebbe avere flag, perche' e' come rubare una studded o dei reagenti 

(se e' nativo di flag, perche' e' appena stato tamato da un tamer e' giusto che la erediti)

**Comment by morpheus8888** [comment]
ho appena provato in game e funziona già così, se rubi un cavallo con la flag la erediti altrimenti no

**Comment by morpheus8888** [comment]
ps: se ti risuccede scrivimi le esatte condizioni così provo a replicare
