### ISSUE TITLE
Bug gemelli phantom castle

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#712]
Al dung phantom castle i gemelli se li porti fuori dalla stanza vanno a metà vita.

**Comment by morpheus8888** [comment]
non riesco a capire bene cosa succede, mi puoi dare qualche informazione in più?

**Comment by SampinoInfernal** [comment]
> non riesco a capire bene cosa succede, mi puoi dare qualche informazione in più?

Allora 
stanza dove ci stanno i gemelli ok? come li fai uscire in un'altra stanza vanno tutti e due subito a metà vita, quindi viene semplice ammazzarli

**Comment by morpheus8888** [comment]
invece di refullarsi perdono vita, strano, ora controllo
