### ISSUE TITLE
Proposta Modifica Comandi Vendor

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#713]
### Discussed in https://github.com/uomars/UOMars/discussions/603

<div type='discussions-op-text'>

<sup>Originally posted by **Saro-UOMars** January  4, 2022</sup>
*Inserimento di un nuovo comando "Vendi Oggetti Multipli" permette di inserire un prezzo/each e una descrizione ed in seguito fà partire un puntatore a click multipli in questo modo si possono targhettare tutti gli oggetti che si vogliono inserire (es. molti tools o engraver) e si risparmia parecchio tempo perso inutilmente.

*una volta inserito un oggetto in vendita il gump del vendor si chiude, sarebbe utile che rimanesse aperto per poter continuare con altre operazioni e non dover doppiocliccare ogni volta sul vendor.

le modifiche mirano a rendere meno tedioso l'inserimento di oggetti in vendita.

</div>

**Comment by gmocciaro** [comment]
fatto entrambi
