### ISSUE TITLE
fare region delle fogne

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#716]
fare la region delle fogne per renderla non markabile
@daffy55  se puoi sulla parte superiore delle fogne facci terreno non calpestabile
@Darksuitjer  se mi fai le region io poi le scripto e le rendo non markabili

**Comment by daffy55** [comment]
> @daffy55  se puoi sulla parte superiore delle fogne facci terreno non calpestabile

Order, pk e Chaos è fattibile
A neutral no, non ho capito perché non vuoi che sopra sia non calpestabile, fissa la z alla regione tipo alle case

**Comment by daffy55** [comment]
Terreno superiore alle fogne reso tutto non calpestabile.
Ora mancano solo le regio di @Darksuitjer e potete chiudere l'issues

**Comment by Darksuitjer** [comment]
volete una region extra come per il porto in modo da settarla non markabile, ma allo stesso tempo non parte della citta? o la modifico con la citta e sticazzi? secondo me meglio la prima

**Comment by morpheus8888** [comment]
region a parte, le fogne non possono essere città

**Comment by daffy55** [comment]
Region extra

**Comment by morpheus8888** [comment]
fatto? @Darksuitjer

**Comment by Darksuitjer** [comment]
> fatto? @Darksuitjer

sisi m'ero dimenticato di scriverlo, ma le ho fatte subito
