### ISSUE TITLE
aggiungere trashcan nel gioco

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#719]
piazzarli almeno nelle banche e centri lavoratori

**Comment by morpheus8888** [comment]
![image](https://user-images.githubusercontent.com/49568239/148855440-3aac5134-5b4e-4afc-8d52-3d35e48e6f0f.png)

**Comment by kentar91** [comment]
possiamo anche inserirli nel rewards? @gmocciaro

**Comment by kentar91** [comment]
> piazzarli almeno nelle banche e centri lavoratori

fatto

**Comment by kentar91** [comment]
> Sono stati fixati? O ci troviamo in game oggetti strani?

Esistono vari tipi di barrel, ho messo quelli che deletano subito gli oggetti

**Comment by daffy55** [comment]
e come si chiamano?
