### ISSUE TITLE
Comandi per casa 

### ISSUE THREAD

**Issue by Darksuitjer** [uomars/UOMars#721]
si riesce a fare un comando per i player per girare gli oggetti in casa e per alzarli?

**Comment by Saro-UOMars** [comment]
> si riesce a fare un comando per i player per girare gli oggetti in casa e per alzarli?
già chiesto e la risposta è quella
https://github.com/uomars/UOMars/issues/592

**Comment by gmocciaro** [comment]
fatto rompicazzi, ora potete muovere items e secure come vi pare e piace (x, y, z, flip)
