### ISSUE TITLE
nella sezione dove conteggiamo l'oro riusciamo a mettere un'opzione che divide il gold totale per le ore giocate

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#722]
come da titolo, un modo per vedere abusi sarebbe anche da controllare il guadagno orario, se è easy altrimenti fa niente

**Comment by gmocciaro** [comment]
non dovrebbe essere difficile

**Comment by gmocciaro** [comment]
![image](https://user-images.githubusercontent.com/12816659/149014921-1ab735bc-d24d-446d-8e26-500c7d737b4d.png)
fatto basta passarci sopra con il mouse
