### ISSUE TITLE
ho ricevuto questo page....

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#724]
![image](https://user-images.githubusercontent.com/83588629/148863149-e113cc89-0877-4b09-adc5-84d9042759ea.png)

![image](https://user-images.githubusercontent.com/83588629/148863217-500b05ef-7ab5-4a4a-828e-d4ae751440d1.png)
![image](https://user-images.githubusercontent.com/83588629/148863297-5bd02e24-4d58-4359-9f08-d573ee4c66d7.png)

@daffy55 @morpheus8888 @Ale1991 @giga487 @gmocciaro @Darksuitjer

**Comment by daffy55** [comment]
No. Non si può

**Comment by morpheus8888** [comment]
si può scendere solo dove ci sono i porti, come ha fatto quello ad andarci? teleport dalla barca?

**Comment by kentar91** [comment]
> si può scendere solo dove ci sono i porti, come ha fatto quello ad andarci? teleport dalla barca

Poi gli ho cancellato la runa che si erano marcati

**Comment by daffy55** [comment]
> si può scendere solo dove ci sono i porti, come ha fatto quello ad andarci? teleport dalla barca?

Si scendono tutti col teleport anche ai porti xD

**Comment by morpheus8888** [comment]
fixato
