### ISSUE TITLE
BUG - Eludere Controllo ''Fast Travel Forbidden''

### ISSUE THREAD

**Issue by FeverSeven** [uomars/UOMars#725]
Non so se posso scriverlo direttamente qui,contattatemi in privato.

**Comment by Saro-UOMars** [comment]
> Non so se posso scriverlo direttamente qui,contattatemi in privato.

ciao, questo è proprio il posto giusto per scriverlo :)

**Comment by daffy55** [comment]
> > Non so se posso scriverlo direttamente qui,contattatemi in privato.
> 
> ciao, questo è proprio il posto giusto per scriverlo :)

un bug del genere non puo' scriverlo, il github e' pubblico

**Comment by Saro-UOMars** [comment]
> > > Non so se posso scriverlo direttamente qui,contattatemi in privato.
> > 
> > 
> > ciao, questo è proprio il posto giusto per scriverlo :)
> 
> un bug del genere non puo' scriverlo, il github e' pubblico

XO
