### ISSUE TITLE
CRAFTING SYSTEM MENU - ITEM DESCRIPTION

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#730]
Serve un mouse over sul gump del craft che dia una descrizione dell'oggetto che stai craftando, ho gia parlato con guido, le descrizioni le scrive lui (serve solo la possibilità di farlo lato codice)

![image](https://user-images.githubusercontent.com/83860614/148943636-ca6b3e1f-ca36-40c9-8406-3de83da0e918.png)

**Comment by morpheus8888** [comment]
abbiamo due strade, o il search nel bible o la descrizione con il mouseover, qualsiasi strada scegliamo va bene

**Comment by daffy55** [comment]
boccio il search nel bible, ma se e' la strada piu' semplice lo accettero' con odio nei vostri confronti

**Comment by Saro-UOMars** [comment]
si è un ottima cosa da inserire, pensavo di chiedere troppo in questo momento di troppe robe da fare XD ma Legil non vi da un cazzo di attimo di respiro!!!! XD vai Legil!!

**Comment by gmocciaro** [comment]
non è possibile fare il search nel bible (dovrei riscrivere mezzo client) non è un item che puoi cliccare, è un immagine stampata a schermo. Per le descrizioni nessun problema

**Comment by SampinoInfernal** [comment]
la descrizione è il top

**Comment by gmocciaro** [comment]
fatto

```
g.NewRecipe()
->     .AddDescription("descrizione bellissima!")
     .AddCraft("Yellow Boiled Fish Steak", typeof(YellowBoiledFishSteak), 1, null, false)
```
