### ISSUE TITLE
possibilità di travellarsi alle case se si è co owner

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#731]
stiamo valutando la possibilità di far travellare un player che non ha la casafissa in quella città ma è co owner di un'altra, abbiamo un metodo efficiente che non sia ciclare tutte le case?

**Comment by gmocciaro** [comment]
no

**Comment by gmocciaro** [comment]
inoltre il coowner rompe tutte le logiche, perchè un chos può mettere co-owner un order (non ci sono controlli) e capisci bene che rompe qualsiasi logica implementata fino ad ora

**Comment by gmocciaro** [comment]
chiudo per ora
