### ISSUE TITLE
segnalo un problema sul peso del REWARD chest

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#735]
ho dovuto metterglieli io in banca, perche' non ci entravano
![image](https://user-images.githubusercontent.com/83860614/148980887-ffa55035-a172-4127-86b5-2a8e4f55a550.png)

**Comment by morpheus8888** [comment]
quale chest? la reward?

**Comment by daffy55** [comment]
beh si

**Comment by morpheus8888** [comment]
@gmocciaro  mi serve una mano a capire come fare che la chest pesi 0 anche se piena di roba

**Comment by gmocciaro** [comment]
.Weight = 0?

**Comment by morpheus8888** [comment]
no, perché gli item devono conservare il loro peso ma quanto sono contenuti dentro quella cassa al player devono pesare 0

**Comment by gmocciaro** [comment]
ah ma tu puoi settare 0 al chest, poi le risorse dentro pesano quello che pesano, io lo faccio già con i chest dorati delle case fisse

![image](https://user-images.githubusercontent.com/12816659/149158341-b1cef146-0a76-4962-a191-188f0552688e.png)

il pileweight dei ginsens è sempre 160, ma il peso del chest è 0

**Comment by morpheus8888** [comment]
quindi il player in borsa ha 0?

**Comment by gmocciaro** [comment]
se ricordo bene si, dovrebbe funzionare (testalo prima ovviamente)

**Comment by morpheus8888** [comment]
ho testato, per quello non capisco @gmocciaro  a me non funziona

**Comment by morpheus8888** [comment]
chiudo, non ho trovato una soluzione, metteremo un avviso che è consigliabile comprare queste chest in una casa @gmocciaro
