### ISSUE TITLE
Worker Packhorse e Summon

### ISSUE THREAD

**Issue by FeverSeven** [uomars/UOMars#747]
Se si utilizza un packhorse un mago (worker) non può utilizzare nessuna summon ad eccezione dell'Energy Vortex.
Non so se è voluta questa cosa,ma non ci vedo molto senso ^^'

**Comment by morpheus8888** [comment]
purtroppo non è di facile risoluzione perché con quei numeri gestiamo il fatto che non se ne possa portare più di 1 a tipo. Ci devo riflettere su come sistemarlo.

**Comment by morpheus8888** [comment]
sto creando un trasportino non mountabile che occupa uno slot, nel frattempo risolviamo così, poi miglioriamo quello
