### ISSUE TITLE
Keg INFINITI

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#748]
i Keg non si svuotano mai, puoi continuare a riempire pozze all'infinito

**Comment by morpheus8888** [comment]
è quello che ti ho scritto io in privato

**Comment by daffy55** [comment]
non ho nessun tuo messaggio, questo me l'ha segnalato Ketamina via Page

**Comment by daffy55** [comment]
un povero cristo che ha inventato questa utility, ha introdotto una funzione che si attiva con la @ 
Diamogli credito, usiamola 
♥

**Comment by morpheus8888** [comment]
ok @kentar91 grazie del consiglio, lo userò

**Comment by kentar91** [comment]
Cosa c'entro io @morpheus8888 ?

**Comment by gmocciaro** [comment]
lo fixo con l'altro
