### ISSUE TITLE
Angolo BUG di Kira

### ISSUE THREAD

**Issue by KiraRockHead** [uomars/UOMars#750]
- Nel secondo step, i due boss Twin Kings (?) , se vengono fatti uscire dalla porta gli si dimezza la vita.
- Spesso in frag, colpendo o ricevendo botte, magiche o fisiche, capita che arrivano danni anomali. Per ora riscontrato con Sampino, ieri sera, provo arco + poison, scocco la prima freccia gli levo 46hp. Dopo regolare 30hp. Giorno prima, seguito da 1 mago e 1 warrior mace, mi ritrovo da solo, mi fermo per aspettare che arrivi uno dei due, mi entra in schermata solo il mago, tempo di castare explosion, mi leva 50 , flame 75hp, tutto ciò dopo 10-15 secondi di fight. Il mio pg ha 100 resist senza armature speciali. 
- Packhorse grigi se frustati crasha, ma penso abbia risolto Morpho

Aggiungo qui poi gli altri se ne trovo ancora!

**Comment by morpheus8888** [comment]
fixato tutto qui
