### ISSUE TITLE
gli ho rifatto la gilda...

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#756]
![image](https://user-images.githubusercontent.com/83588629/149237042-e0f83930-eb70-4683-8a74-3633dabaa827.png)
![image](https://user-images.githubusercontent.com/83588629/149237055-be50b872-8113-4513-88af-a0de7dcd5190.png)
 mannaccia il santo cielo che pazienza 
gli ho rifatto la gilda....

sarebbe carino poter cambiare almeno la tag della gilda

**Comment by gmocciaro** [comment]
no perchè altrimenti la cambiano ogni santo giorno, se sbagliano amen, non mi sembra una cosa da fare e nemmeno un urgenza in questo periodo

**Comment by kentar91** [comment]
spesso se ne escono con certe cose.... davvero cioè bah..

**Comment by lyon1235** [comment]
Bannali direttamente la prossima volta
