### ISSUE TITLE
runebook non apribli

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#757]
![image](https://user-images.githubusercontent.com/83588629/149240240-3e5da701-877a-4ae7-9ad5-a2611830bfbb.png)

leggiti questa storia "strana" @morpheus8888 

ha prestato il suo runebook blessed, trovato in una cassa, a un amico e poi non poteva più aprirlo, ma l'ha fatto copiare con la penna.

alla fine ho reso blessed quello che aveva copiato e mi sono preso il suo.
ho provato anche a togliere la flag che poteva essere aperta solo dai proprietari ma niente...

**Comment by morpheus8888** [comment]
ti spiego, quando muori il runebook viene lockato per evitare che chi lo looti usi quei punti. SOlo il proprietario doppiocliccandolo può sbloccarlo, ora ho aggiunto che da props possiamo sbloccarlo anche noi. @kentar91
