### ISSUE TITLE
[Cove, 0 - 2] Campo orchi esterno + [Meridian, 300 - 700] Zona Pvm Safe

### ISSUE THREAD

**Issue by andreadellacorte** [uomars/UOMars#76]
Campo Orchi a Cove da 0 a 200
Portale per Meridian da 300 a 700 collegato tramite passaggio sotterraneo - bidirezionale
Coordinate: 5840 448 10

**Comment by kentar91** [comment]
completato. 
da testare

**Comment by kentar91** [comment]
Chiudiamo ?
