### ISSUE TITLE
miglioramento non prioritario: nuovi player

### ISSUE THREAD

**Issue by Vandervalth** [uomars/UOMars#762]
Accade che quando un "nuovo" player entra in game, esce a tutti i GM in alto a sinistra la tabella per poter andarci sopra (quella con sfondo grigio). 

Noto che questa appare più volte per lo stesso account/pg ed ipotizzo sia legata alla caratteristica YOUNG (quindi per un arco di tempo ti continua ad apparire anche per player che sanno già come si gioca). 

E' possibile fare in modo che appaia SOLO per player che hanno creato il primo pg dell'account? (quindi effettivamente nuovi) OPPURE, se si vuole lasciare anche agli YOUNG, è possibile cambiare il colore dello sfondo se è vera la condizione: YOUNG + primo pg dell'account?

Questo per poter attenzionare meglio i player veramente nuovi e magari apparire loro e spiegargli un pò cosa devono fare se non riescono ad accedere almeno al tutorial dopo tot tempo che sono online.

Bella!! :D

**Comment by morpheus8888** [comment]
metto come condizione avere un solo pg per account

**Comment by morpheus8888** [comment]
prima era:
- tempo di gioco inferiore a 2 ore
- young

ora aggiunto anche un pg ad account
