### ISSUE TITLE
Stock Materiali in vendita

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#766]
si potrebbe rendere gli oggetti acquistati sul VS invendibili sul VS per 12/24 ore, questo per evitare lo scalping selvaggio.
o almeno i materiali per il crafting che sono necessari e tutti.

**Comment by morpheus8888** [comment]
lol gli scalper su uomars, che è successo di specifico?

**Comment by Saro-UOMars** [comment]
vado su VS, vedo che non ci sono Iron Wires, ne crafto 1000 e li metto in vendita al prezzo di 3GP l'uno come tutto il resto dei materiali di seconda, staves thread etc... cmq dopo neanche 5 minuti riguardo e sono stati comprati tutti direttamente dal Vendor e ritrovo in vendita 50 Wires a 6 GP -.-. scalping ok ma non a discapito della disponibilità del VS, quindi un cooldown per rimetterli in vendita bloccherebbe lo scalping selvaggio come questo.
Per rimediare ho craftato altri 2000 wires e rimessi in vendita, voglio vedere se compra anche quelli e chi finira prima i soldi o la pazienza XD cmq non posso farlo sempre...

**Comment by morpheus8888** [comment]
@gmocciaro è fattibile fare in modo che un item comprato non possa essere rimesso in vendita per 24 ore?

**Comment by gmocciaro** [comment]
ma quando metti un oggetto in vendita, nel vs è comprabile dopo 7 ore tipo, non capisco a cosa vi rierite

**Comment by gmocciaro** [comment]
ma poi è la legge del mercato, vendili tu direttametne ad un prezzo più alto, mica dobbiamo intervenire in ogni cazzata che fate perdonatemi
