### ISSUE TITLE
roba spawnata sulla lava

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#769]
![image](https://user-images.githubusercontent.com/91663610/149463287-1c22d57a-7365-4992-b5d3-37eeb96aab55.png)
 un sacco di roba spawna qui ed è irrragiungibile

**Comment by kentar91** [comment]
> ![image](https://user-images.githubusercontent.com/91663610/149463287-1c22d57a-7365-4992-b5d3-37eeb96aab55.png)
>  un sacco di roba spawna qui ed è irrragiungibile

Sì ci avevo fatto caso
Ho già chiesto a @daffy55 di rendere quei tile non calpestabili

**Comment by daffy55** [comment]
Mi sono dimenticato, domani fixo

**Comment by daffy55** [comment]
Fixato
