### ISSUE TITLE
Utilizzare Oggetti Lockati in casa

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#770]
es. poter utilizzare il DYETUBE @morpheus8888 
![image](https://user-images.githubusercontent.com/97031570/149471302-cc40078b-6e49-400c-a2b7-641c1104f455.png)

**Comment by morpheus8888** [comment]
gli oggetti lockati non possono essere utilizzati, se viene qualche ospite in casa ti consuma tutto, oltre che poter generare bug
