### ISSUE TITLE
PG Young e Ladri

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#772]
ma i pg ladri possono essere derubati? perchè giustamente un pg young oggi mi ha detto " mi hanno rubato tutto, io non sono nemmeno come counterarli, non ho manco le skill e non conosco le meccaniche del gioco" e secondo me ha ragione, non ha avuto il tempo di capire come funziona il gioco ed è stato miseramente defraudato.

**Comment by daffy55** [comment]
Non sapevo fosse nuovo, cmq se è Danij era alle worker, fuori Pryma può essere derubato, gli ho fregato 82 ironwire

**Comment by morpheus8888** [comment]
al momento uno young non può essere rubato a pryma, ma se secondo voi uno young non deve essere mai rubato si può mettere

**Comment by Saro-UOMars** [comment]
secondo me sarebbe meglio si

**Comment by morpheus8888** [comment]
ora gli young non possono essere rubati nell'intera mappa di Felucca
