### ISSUE TITLE
robe guild

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#773]
![image](https://user-images.githubusercontent.com/12816659/149579429-598ab093-bcf8-42b6-a498-6e860d165a48.png)

**Comment by daffy55** [comment]
Sarebbe fico

**Comment by Saro-UOMars** [comment]
Non ci potreste dare i Dye Tube col colore cosi da poter colorare i vestiti in generale?

**Comment by gmocciaro** [comment]
i vestiti di gilda noni potresti a prescindere
