### ISSUE TITLE
Casa Esterna GRIGI

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#778]
Ogni volta che sloggo nel letto in casa, quando riloggo mi trovo fuori dai cancelli di Pryma

**Comment by gmocciaro** [comment]
ma il problema mi sa sta nel logout non nella casa fissa, rigiro a chi di dovere @morpheus8888 @giga487

**Comment by giga487** [comment]
> ma il problema mi sa sta nel logout non nella casa fissa, rigiro a chi di dovere @morpheus8888 @giga487 

Ti faccio risparmiare strada... Di che ti lamenti

**Comment by morpheus8888** [comment]
fixo

**Comment by morpheus8888** [comment]
fixato
