### ISSUE TITLE
WORKER PK INVULNERABILI

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#779]
E' voluto?

perche' e' complicato entrare a Pryma per levarselo

**Comment by morpheus8888** [comment]
no, solo un worker blu dovrebbe poter tornare invulnerabile,

**Comment by daffy55** [comment]
mi sembra una cacata, anche i pk devono poter tornare vulnerabili

**Comment by morpheus8888** [comment]
il codice attualmente impedisce a qualsiasi player che sia diverso da blu fazionato di diventare invulnerabile, quindi non riesco a capire bene come abbia fatto. L'unica cosa che mi viene in mente è che era blu invulnerabile e poi con l'account monocolore glie l'ha colorato, questa condizione l'ho appena fixata. Metto anche che al prossimo login gli toglie automaticamente l'invulnerabile.

**Comment by daffy55** [comment]
> L'unica cosa che mi viene in mente è che era blu invulnerabile e poi con l'account monocolore glie l'ha colorato, questa condizione l'ho appena fixata.

È andata esattamente così. Ero di fretta quando ho scritto il git, sorry
