### ISSUE TITLE
Tentativo 203210 mappe tesoro

### ISSUE THREAD

**Issue by KiraRockHead** [uomars/UOMars#780]
Ho provato ad aprire una mappa di lvl 5 con il lockpicker (100 skill) penso di aver fallito 15+ volte e non riesco ad aprirlo..Worka tutto a modo? D:

**Comment by KiraRockHead** [comment]
Aggiorno, l'ho aperto con il ladro, ma non potevo prenderli, quindi il ladro non può prendere la roba se non è in party!

**Comment by morpheus8888** [comment]
che vuol dire l'hai aperto con il ladro?

**Comment by KiraRockHead** [comment]
- le mappe del tesoro ora sono lockpickabili, la difficoltà è alta, i mostri rivelano gli hiddati e il boss difficilmente si allontanerà dalla chest. Ma un lockpicker abile forse potrebbe rubare ugualmente il tesoro. Attenti alle trappole. (ogni volta che si fallisce c'è una probabilità su 10 di distruggere l'item dentro).

**Comment by KiraRockHead** [comment]
Ho il pg con 100 lockpicking, ho fallito davvero 15 volte e passa, era un secure di una mappa lvl 5 con indice 478 tipo di difficoltà, dentro c'erano 16k di scrap , solite 250 scroll e un arcane light....Non so se è normale, e comunque appena son riuscito ad aprirlo (era un secure fatto con il mio pg comunque, avevo capito che potevo aprirlo solo con lockpicking)  non potevo guardare dentro e aprirlo per prendere la roba

**Comment by morpheus8888** [comment]
lockpicking non è necessariamente una skill da ladro per quello non capivo, quindi tu con il pg con lockpicking hai aperto la cassa e questo l'ho capito ma il passaggio dopo non lo capisco bene. Tu intendi che nonostante l'avessi lockpickato poi per prenderne il contenuto hai comunque dovuto prima uccidere i mostri?

**Comment by KiraRockHead** [comment]
Ho provato ad aprirla, tralasciando che ha fallito, imho, troppe volte per avere 100 nella skill. Tolto questo, quando sono riuscito ad aprire la cassa, nonostante fosse aperta mi dava il messaggio che non potevo aprirla perchè il tesoro nn era mio

**Comment by morpheus8888** [comment]
ok, l'ultima cosa, ma tu la mappa l'hai tirata fuori con il lockpicker o con un altro pg?

**Comment by KiraRockHead** [comment]
Tirata fuori con il pg mago, ucciso i mob, poi ho loggato il Lockpicker per provare

**Comment by morpheus8888** [comment]
ok allora ho capito qual è il problema ora fixo

**Comment by morpheus8888** [comment]
ora un lockpicker può scassinare una cassa aperta anche da qualcun altro e rubare tutto il contenuto

**Comment by KiraRockHead** [comment]
Grande ty da che lvl a lvl va la difficoltà? Da 0 a 500? Perché se così fosse quella per il livello di difficoltà da aprire cmq ha dato poco niente
