### ISSUE TITLE
inserire il rischio al goldentool

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#782]
deve considerare il rischio nella produzione, aumentare la skill come se fosse il crafting

**Comment by gmocciaro** [comment]
ma il rischio non esiste come concetto nel refinement perchè è del crafting, comunque possiamo includerlo con un po di lavoro

**Comment by gmocciaro** [comment]
aggiunto sugli scraps ma sui lingotti non usa la skill quindi non posso al momento

**Comment by gmocciaro** [comment]
fatto
