### ISSUE TITLE
talismano taming

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#786]
potete verificare questa cosa? dice che non sale, io ho assistito ad una sua tamata, aperto le props del talismano e mi segna sempre 0 punti
![image](https://user-images.githubusercontent.com/83860614/149657850-a5a5fa9b-5e5a-4084-bed8-61c7666e7c96.png)

**Comment by gmocciaro** [comment]
per ora il talismano ignoralo perchè lo riscriviamo praticamente ogni giorno xD
