### ISSUE TITLE
consumo pozze e pesci anomalo

### ISSUE THREAD

**Issue by GiovGiorgio** [uomars/UOMars#789]
Buongiorno, se si hanno pozze o pescetti in stack, e si utilizzano, via macro o clickando a mano, si consumano 2 risorse. Se invece si separano in stack singoli, e si clicka sul singolo pesce o pozza, si consuma una sola risorsa

**Comment by SampinoInfernal** [comment]
ma secondo me la stessa cosa fa pure con i reagenti, cioe ne finisco sempre ogni fraggata

**Comment by Ale1991** [comment]
è ancora così o è risolto? @GiovGiorgio

**Comment by GiovGiorgio** [comment]
si è risolto dopo la serie di riavvii

**Comment by Ale1991** [comment]
perfetto allora chiudo
