### ISSUE TITLE
Tassa Esterni, diversificare

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#797]
sarebbe possibile rendere la tassa del vendor per gli esterni diversa tra le fazioni? In base agli accordi o disaccordi si potrebbe cambiare la tassazione etc...

**Comment by Saro-UOMars** [comment]
@morpheus8888 @gmocciaro @Ale1991

**Comment by gmocciaro** [comment]
non è fondamentale quindi direi di no, anche perchè la tassa è per i nemici diretti, order e chaos non sono nemici di neutral (immagini parlo di neutral) poi ci sono delle implicazioni e controlli da fare nel caso tu sia un chaos, order, pk, neutral

resoconto: non ora

**Comment by Saro-UOMars** [comment]
si appunto "nemici diretti" lo sono da poco diventati
