### ISSUE TITLE
** bug minore le mele per il talismano si fermano a 99%

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#798]
non fa mangiare l'ultima

**Comment by daffy55** [comment]
> non fa mangiare l'ultima

Basta che minano 3 depositi e torna a 100

**Comment by thepatriot87** [comment]
hai ragione per quello ho scritto minore

**Comment by gmocciaro** [comment]
talismano chiudo tanto lo stiamo rifacendo e non ha senso fixare cose che leveremo
