### ISSUE TITLE
le creature che muoiono a vulcano devono essere lotabili

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#799]
hanno ucciso il mob e non lo potevano lotare hahaah

**Comment by GiovGiorgio** [comment]
aggiungo, non sapendo se è collegato o meno al problema, che ad un certo punto mi son ritrovato il corpo in sacca. dopo averlo posato però potevo aprirlo, c'erano dei lingotti di obsidian

**Comment by gmocciaro** [comment]
> aggiungo, non sapendo se è collegato o meno al problema, che ad un certo punto mi son ritrovato il corpo in sacca. dopo averlo posato però potevo aprirlo, c'erano dei lingotti di obsidian

cioè ti sei draggato il corpo del mostro dentro la tua sacca? wtf

**Comment by morpheus8888** [comment]
forse gliel'ha messo dentro kentar perché lui non poteva lotarlo @gmocciaro

**Comment by gmocciaro** [comment]
fixed
