### ISSUE TITLE
Grafica armor legno lv 1

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#800]
visto che non piace praticamente a nessuno, avevo pensato a queste due

![image](https://user-images.githubusercontent.com/91663610/149949987-33a7abfd-1647-4031-81fb-f49ee818b8b1.png)

@morpheus8888

**Comment by morpheus8888** [comment]
ma sono in pelle non legno, purtroppo è l'unica di legno che abbiamo. Ci vorrebbe un grafico che non c'è. Queste teniamocele per qualcos altro
