### ISSUE TITLE
Tracking e Detect

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#803]
E' possibile rendere meno precisa la freccia di Tracking su un pg strealthato?

**Comment by morpheus8888** [comment]
al momento ho diminuito il range di tracking sugli hiddati, anche se fosse meno precisa comunque che vantaggi otterresti? detect a 100 ha un range grosso come una schermata @daffy55

**Comment by daffy55** [comment]
Che che si collega alla seconda richiesta

**Comment by morpheus8888** [comment]
fammi capire se ha senso rendere la freccia leggermente distorta adesso con tutto il resto fixato

**Comment by morpheus8888** [comment]
presumo vada bene così
