### ISSUE TITLE
possibilità di usare cloth colorate per i vestiti al tailor 

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#812]
fammi sapere se è possibile

**Comment by gmocciaro** [comment]
Allora, attualmente non è possibile perchè il sistema si basa sul fatto che la risorsa di base ha l'attributo resource, in base a quello assegna la resource o l'eventuale colore all'item craftato.

Immagino che con un po di lavoro posso estendere la logica pure a oggetti che non siano di tipo resources (come appunto le cloth) ma ci sono un po di problemi:

1) Il colore non ha un nome, quindi l'utente non potrà scegliere il colore ma verrà preso in automatico uno randomico tra quelli possibili nello zaino, quindi se ho le cloth di 3 colori diversi, non posso fare scegliere il colore al player, visto che il colore non ha un nome ma solo un ID.

2) a conseguenza del punto 1, se ne prendo random, devo cambiare la logica del crafting perchè non posso più andare per la logica "usa le risorse di quel tipo" ma devo anche fare il check sul colore, perchè se una shirt mi costa 10 e ho 5 cloth rosse e 5 cloth blu io non posso fargliele mescolare immagino, dovrei dirgli che non ha abbastanza risorse quando invece le avrebbe. O anche se per assurdo le faccio mescolare, il colore risultante è un colore a random tra i due, l'utente non è in grado di decidere quale dei due lui vuole come risultante.

al netto dei problemi comunque per fare questa cosa ci vorrà un po di tempo e un po di test

**Comment by morpheus8888** [comment]
quindi si fa prima a creare una resources per il cloth?

**Comment by gmocciaro** [comment]
anche li è un mezzo casino in realtà, perchè le resource sono quelle di base del gioco che vengono aggiunte nel CraftResource.cs, non so cosa comporta aggiungerle li, quindi in lista avresti tutti i materiali del gioco + i colori, si potrebbe fare volendo ma chiedo ad @Ale1991 che ne sa più di me su ste cose

**Comment by morpheus8888** [comment]
aspetto la risposta di ale e poi procedo

**Comment by Ale1991** [comment]
si basta aggiungere le risorse... solo che non è un aggiunta di un enum semplice ma vanno aggiunte una marea di logiche...alcune vanno completate da zero... se mi dai i nomi e i colori provo ad aggiungerle oggi ma conta che seguiranno la logica dei nomi delle armor tipo Juppo Robe o Juppo Long Pants
