### ISSUE TITLE
crafting dal packhorse

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#819]
fare in modo che durante il crafting il personaggio non debba avere bisogno di craftare mettendo la roba in borsa ma legge anche le backpack dei followers se sono entro 2 tile dal personaggio, se possibile fare in modo che il craft vada direttamente in borsa del packhorse se questo può ancora contenere peso, altrimenti in borsa al player

**Comment by Saro-UOMars** [comment]
questo per risolvere quale problema? non trovo particolari scomodità a riguardo

**Comment by gmocciaro** [comment]
secondo me è più scomodo che comodo, alla fine il packhorse si avvicina e ti sposti le cose, magari lo puoi anche usare per mettere le risorse che non vuoi usare anche involontariamente, poi se lo hanno segnalato in tanti si fa, ma se è solo 1 che si lamenta cazzi

**Comment by morpheus8888** [comment]
il problema è che se ricevi un attacco mentre crafti tanta roba sei praticamente morto, non fai intempo a spostare tutto rapidamente nel packhorse, avvantaggi troppo gli assassini. Sei sempre staminato.

Secondo problema è che per craftare roba enorme come ad esempio una barca fai fatica ad avere tutto nel backpack.

**Comment by gmocciaro** [comment]
facciamo un ibrido per facilitarmi la vita, le risorse le considero anche dal packhorse ma crafto sempre dentro lo zaino del player, capiamo cosa ne pensano e in caso si implementa la seconda parte se necessario, cosa ne dici?

**Comment by daffy55** [comment]
Che sta rosicando perché è stato pkappato :look:
Cmq si approvo, sorgente dal packhorse, prodotto finito in backpack
