### ISSUE TITLE
death shroud

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#824]
Sara' la terza che trovo in giro per la mappa
qualcuno di voi se la crea, ma essendo Travel Forbitten la droppa a terra.

(questa l'ha trovata Kira, ce l'ha in banca)

**Comment by morpheus8888** [comment]
non c'è scritto in qualche props chi la crea?

**Comment by Darksuitjer** [comment]
ieri ce n'era una loccata su un ponte ad est delle worker per andar a chaos durante il pvp

**Comment by morpheus8888** [comment]
fixato
