### ISSUE TITLE
forse già noto - morte a meridian

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#825]
![image](https://user-images.githubusercontent.com/83588629/150118806-3f93155f-47b2-45a8-9224-1e3adbb5f521.png)
quando muori 50 volte a meridian ti trovi un macello di roba nello zaino perchè vai a rilootare il corpo all'infinito...

ti direi di fare un controllo ogni x secondi che va a pulire questa spazzatura oppure non puoi lootare la roba dungeon0 dal corpo

**Comment by Ale1991** [comment]
andrebbe bene come fix che quella roba si distrugge quando muori? tanto ti viene ridata quando ressi. Se si domattina lo faccio

**Comment by morpheus8888** [comment]
si per me va bene

**Comment by daffy55** [comment]
Perfetto, tanto nessuno ci si affeziona
