### ISSUE TITLE
morte meridian - healer

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#826]
consiglio di introdurre una funzione che ti recalla all'healer + vicino a dove sei morto

**Comment by morpheus8888** [comment]
non è fattibile, l'unica cosa che potrei fare è inserire meridian nel ghost travel, se vi va bene lo faccio

**Comment by kentar91** [comment]
a patto che disattivi quello normale... altrimenti la gente si trova a pryma

**Comment by daffy55** [comment]
> a patto che disattivi quello normale... altrimenti la gente si trova a pryma

nel ghosttravel scegli la destinazione per come e' ora, se la gente sceglie pryma e' cogliona

**Comment by morpheus8888** [comment]
quindi?

**Comment by daffy55** [comment]
Quindi ci sono 9 healer a meridian e tutti segnati in mappa, va bene aiutali, ma non esageriamo, anche perché quando si ressano hanno tutto l equip in borsa

**Comment by morpheus8888** [comment]
ok
