### ISSUE TITLE
bug death shroud

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#834]
non è nessuno di noi gm che lascia le death x terra
![image](https://user-images.githubusercontent.com/91663610/150235443-5541a116-2ce7-49b0-b8a6-bbb02d91c280.png)
delmer è morto, è entrato in un gate da morto e l'ha lasciata per terra
oppure l'abbiamo ressato, è entrato nel gate e l'ok l'hapremuto dopo

**Comment by morpheus8888** [comment]
praticamente se da fantasmino ci entri, la veste del "morto" cade a terra lol

**Comment by daffy55** [comment]
e' un problema perche' i pg possono raccoglierle

**Comment by morpheus8888** [comment]
fixato
