### ISSUE TITLE
**grave usando stealing usa tracking

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#837]
anche mettendo useskill da macro

**Comment by thepatriot87** [comment]
https://user-images.githubusercontent.com/17385984/150238715-866d66bf-aacb-42bd-ae3d-6ef5e1d45395.mp4

**Comment by thepatriot87** [comment]
@morpheus8888

**Comment by daffy55** [comment]
si lo fa solo la prima volta a pg

**Comment by thepatriot87** [comment]
che significa solo la prima volta? io non riesco ad usare stealing

**Comment by daffy55** [comment]
significa che se usi .steal (come richiede il tutorial), poi non ti da piu' il problema

**Comment by thepatriot87** [comment]
si vero

**Comment by morpheus8888** [comment]
io non ho capito, potete essere più precisi? usare la skill fa uscire il gump tracking? sempre?

**Comment by thepatriot87** [comment]
fino a quando non si usa .steal

**Comment by thepatriot87** [comment]
@morpheus8888  gui intanto puoi modificare il gate learn snooping and stealing , al posto di usare skill stealing metti .steal

**Comment by morpheus8888** [comment]
ma non ho capito, questa cosa la fa in tutto il mondo o solo lì a jhelom?

**Comment by thepatriot87** [comment]
non so dopo pranzo provo con un nuovo pg

**Comment by morpheus8888** [comment]
io ho creato un pg, sto provando ad usare stealing dallo skills gump (paperdoll) ma niente, mi ruba tranquillamente, sia a jhelom che non a jhelom

**Comment by morpheus8888** [comment]
bho sto provando in tutti i modi ma nulla, credo sia un bug del client a questo punto @giga487

**Comment by giga487** [comment]
Non è un bug del client, è che secondo me lui ha copiato la cartella vecchia di uo mars o qualcosa  del genere. Deve cancellare il file skillsgroup.txt all'interno del "..\ClassicUo\Data\Profiles\$NOMEACCOUNT$\UoMars.it\$NOME_PG$\skillsgroups.xml"

**Comment by thepatriot87** [comment]
ho provato con un altro account non me lo fa. Il problema non é a me ma é successo sia ieri che  oggi a pg nuovi ci stava anche legil

**Comment by thepatriot87** [comment]
ho provato a creare un nuovo pg e non me lo fa. legil diceva che é un bug vecchio e che succede random

**Comment by thepatriot87** [comment]
![immagine](https://user-images.githubusercontent.com/17385984/150371527-118730fc-5cd3-45fa-b802-3c55e0203b03.png)

**Comment by thepatriot87** [comment]
![immagine](https://user-images.githubusercontent.com/17385984/150373148-66f6cd54-3bec-495e-a7bf-83382324dedc.png)

**Comment by giga487** [comment]
Ho gia risposto a tutto
