### ISSUE TITLE
Disguise kit

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#841]
Se si slogga in disguise il nome rimane quello del disguise anche riloggando dopo la scadenza (dura 1 ora)

(Neanche il set name funziona, ho dovuto andare di .kill per fixare)

**Comment by morpheus8888** [comment]
mi sa che dura 2 ore, comunque verifico

**Comment by morpheus8888** [comment]
@daffy55 ho controllato, dura 1 ora anche effettivamente, ora sistemo

**Comment by daffy55** [comment]
@morpheus8888 si il problema sorge se slogghi, ma tu intendi un ora di gioco o di orologio? perche' deve essere un ora reale

**Comment by morpheus8888** [comment]
per il momento ho fatto tempo giocato, mi ci trovavo, se poi pensi che così sia sbagliato riaprimi un git e metto che scorre anche da sloggato

**Comment by morpheus8888** [comment]
XD
