### ISSUE TITLE
mob lostland

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#844]
1) Filo che se ci passi vicino ti frozza 
2) _Goblin snooper di pack horse. Fa uscire un timer sul tuo cavallo di 3 secondi poi ruba parte del bottino e corre verso la sua caverna. (5 secondi per ucciderlo poi sparisce in stealth se resta in stealth 10 secondi il mob scompare per sempre._  - brigante ruba i worker
_3) hunter, mob che se gli passi vicino Usa un fischio e ti fa inseguire da due cani da caccia per x secondi i cani hanno la possibilità di rallentarti_ 
4) se sei pk o grigio le sentinelle della foresta ti Attaccheranno - pixie
5) se sei blu i predoni della palude ti attaccheranno

by Samuel

**Comment by morpheus8888** [comment]
mob ladro fatto:
- è hiddato, quando trova qualcuno si stealtha per andargli sotto il culo e inizia a rubarlo a profusione, quando ha rubato tutto lo attacca
L'ho fatto brigante così si vede umano, con i guanti da ladro, gli possiamo mettere anche gli item che gli fanno il buff

**Comment by morpheus8888** [comment]
ma filo è il filo oggetto o il player? XD

**Comment by morpheus8888** [comment]
scriptata la pixie, attacca solo criminali e pk

**Comment by kentar91** [comment]
> ma filo è il filo oggetto o il player? XD
> 

È mob

**Comment by morpheus8888** [comment]
> > ma filo è il filo oggetto o il player? XD
> 
> È mob

non l'avevo capito ahahah top kentauro

**Comment by kentar91** [comment]
@morpheus8888  743 filo

**Comment by kentar91** [comment]
aggiornato al 24/01/2022
- pixie  - attacca rossi e grigi ed è un mago di livello2
- brigant raider, che attacca solo i blu - è random tra fencer poisoner, macer fader, sword weakener
- brigant thief - che ruba e attacca solo i worker - melee - cammina in stealth
- animated root - hiddata - appena ti avvicini (3 tile)  esce dall'hiding, ti frozza,  e ti fa un danno minimo. verrà posizionata vicino ai mostri precedenti - ogni 4 secondi ripete il ciclo - quando esci dal suo raggio di azione si resetta

**Comment by morpheus8888** [comment]
nuovi mob  lvl3
matrona litch             bodyvalue  78   mage
cavaliere delle prigioni    (umanoide a cavallo scheletrico 793 bodycavallo)
drago osso maledetto        bodyvalue 104

bardabili  tutti lvl1
ciclope   bodyvalue 75    macer
moloch    bodyvalue 785   mage
caprone putrefatto  1427  fencer o sword

**Comment by morpheus8888** [comment]
Special Abilities, Flame Strike.

Tira un flame
ogni 12 secondi
che toglie 1 hp di danno puro ogni 100 di intelligenza 
a che distanza, 12 tiles


Special Abilities, Chain Lightning.

Tira un chain
ogni 12 secondi
che toglie 1,2 hp di danno puro ogni 100 di intelligenza 
a che distanza, 12 tiles

**Comment by morpheus8888** [comment]
aggiunti 
cyclop
rottengoat
molochmage
SkeletalDrake
SkeletalKnightRider
MatronLeech

**Comment by morpheus8888** [comment]
si può chiudere
