### ISSUE TITLE
problemi abbandono casa

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#845]
quando abbandoni una casa:

- letto e dragon head non vengono rimossi e piazzati nel goldenchest (non e' neanche possibile rimuoverli successivamente)
- il cavallo rimane attaccato all'hitchingpost e non e' piu' possibile recuperarlo

**Comment by gmocciaro** [comment]
perà gli addon non fanno parte della casa ma sono piazzati a cazzo e basta, ora vedo di sistemarlo questo, per il cavallo che facciamo? stamiamo? uccidiamo? shrinkiamo?

**Comment by gmocciaro** [comment]
- Ora quando si abbandona la casa e c'è un pet attaccato all'hiching post, il pet viene sganciato. Se l'owner della casa non ha spazio per portare il pet (ha troppi pet), il pet viene stamato

**Comment by morpheus8888** [comment]
ci deve essere qualche bug allora perché ieri uno diceva che aveva preso una casa fissa dove c'era ancora il vecchio lallo attaccato, vogliamo fare il controllo anche all'acquisto?

**Comment by gmocciaro** [comment]
ma magari la casa era stata abbandoanta prima del fix, possiamo farlo anche all'acquisto volendo (lo faccio)

**Comment by gmocciaro** [comment]
messo anche all'acquisto
