### ISSUE TITLE
impossibile uscire da nighmar

### ISSUE THREAD

**Issue by GiovGiorgio** [uomars/UOMars#846]
Salve, purtroppo con l'aggiunta del guardiano prima del secondo boss, se si procede lungo il dungeon fino al terzo quarto boss, è impossibile uscire dal dungeon. l'unica alternativa è depositare tutto in banca e andare di travelbook. Pensate sia possibile aggiungere una leva che apra la porta per i più spilorci che vogliono risparmiare, o va bene così?

**Comment by morpheus8888** [comment]
che mi ricordi è proprio voluto che non si possa uscire, l'alternativa è l'escaperope

**Comment by kentar91** [comment]
Confermo
