### ISSUE TITLE
rel por case fisse

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#848]
siccome e' vietato il rel por da fuori a dentro (come giusto che sia)
vietiamo anche da dentro o fuori, perche' se no la gente entra in casa, lamera e rel porta via

**Comment by daffy55** [comment]
gia che ci sei evita anche gli attacchi da fuori a dentro

**Comment by gmocciaro** [comment]
lo dici come se fosse la cosa più semplice del mondo, non ho idea se possiamo farlo devo indagare

**Comment by gmocciaro** [comment]
fatto il teleport, non la cosa dei danni
