### ISSUE TITLE
Spellbook craftabili

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#85]
Abilitare il craft degli spellbook nelle varie pelli disponibili.
Renderli già pieni oppure riempibili ?
Chi li riempirebbe questi libri? Lo scriba? Esiste un item che duplica gli spellbook e i runebook.

**Comment by Ale1991** [comment]
aggiunta la recipe tra i craft di tailoring. 
I libri craftati saranno vuoti e le scroll per riempirli verranno inserite nel lootsystem.
Chiudo e sposto l'idea dell'item che duplica spellbook/runebook nella discussion recal/gate/travel
