### ISSUE TITLE
camperano le due entrate alle lost lands

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#850]
possibile soluzione?

**Comment by Saro-UOMars** [comment]
area no fight intorno alle entrate/uscite?

**Comment by daffy55** [comment]
> area no fight intorno alle entrate/uscite? @morpheus8888

anche no

**Comment by Saro-UOMars** [comment]
non può funzionare cosi il gioco, che esco dalle lost e incontro qualche idiota che non ha intenzione di "giocare" ma vuole solo rompere il cazzo agli altri lo killa perchè è indifeso e lo fulloota e gli ammazza pure il packhorse, che gioco è?

**Comment by morpheus8888** [comment]
un'area no fight purtroppo in zona nera non si può fare, facciamo un'altra uscita?
posso fare anche che l'arrivo del travelbook ha un po' di zone random

**Comment by Saro-UOMars** [comment]
un altra uscita non serve, se la vogliono camperare lo faranno cmq, basta 1 solo perchè un worker contro un pk/rosso pvppparo cosa può fare? niente... se incontra pure il bulletto che vuole divertirsi solo lui non hai nulla per caunterarlo... ci flammi e basta e poi quitti... perchè lui doveva divertirsi...

**Comment by GiovGiorgio** [comment]
Perdonami saro, ma non è vero che non puoi counterare il pk che campera l'uscita a felucca. puoi benissimo mettere le skill difensive al lavoratore: healing anatomy, res spell, e parry (o ancora meglio hidding e stealth). Difficilmente un gruppo di 2-3 pk riesce ad ucciderti dall'uscita fino a pryma. E se proprio vuoi farti il packhorse pieno, puoi procurarti le pozioni carota
