### ISSUE TITLE
la resurrection potion non deve poter essere bevuta/acquistata nella region delle case

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#851]

**Comment by gmocciaro** [comment]
fatto

**Comment by morpheus8888** [comment]
@daffy55  ha segnalato che possono ancora ressarsi

**Comment by gmocciaro** [comment]
si ma solo owner, friends e co-owner, se volete levo pure quelli

**Comment by morpheus8888** [comment]
il bug è che loro iniziano a ressarsi fuori dalla casa e poi entrano dentro e si ressano dentro, quindi o li frozziamo per tutto il tempo o bisogna mettere il controllo all'inizio e alla fine @gmocciaro

**Comment by gmocciaro** [comment]
ma è già così, sia il fatto che sia frozzato sia il fatto che c'è un altrro check alla fine del timer, ora ritesto in caso

**Comment by gmocciaro** [comment]
inoltre aggiungo che ora chi non è proprietario, owner o coowner manco può entrare in casa, è bloccato a livello di region

**Comment by gmocciaro** [comment]
l'unica cosa che posso pensare è che la casa in questione sia mappata male e saltano tutti i check sulla region (perchè non esiste), di che casa si tratta?
