### ISSUE TITLE
Malus 50% danni sui player per i worker

### ISSUE THREAD

**Issue by GiovGiorgio** [uomars/UOMars#852]
Alle worker il malus non funziona. Viene fatto il danno pieno. Ho il sospetto che lo stesso avvenga a felucca, ma non ho avuto modo di testare. 
Forse ciò dipende dal fatto che il mio pg era senza skill lavorative?

**Comment by Ale1991** [comment]
Fixato. C'era un bug con il quale saltava la riduzione. Ora è del 20% come doveva essere e non del 50% @GiovGiorgio
