### ISSUE TITLE
hiding e stealth

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#856]
è incounterabile, anche con detect e traking a 100 non serve proprio a nulla, il player si hidda di nuovo subito dopo e il tuo cooldown dura una vita... cosi non si può giocare... è inutile pure giocare sembra una presa per il culo XD

**Comment by morpheus8888** [comment]
ho appena provato in locale, una volta rivelati per 3 secondi non ci si può hiddare, un tempo sufficiente per attaccare qualcuno.  sei sicuro che si è hiddato istantaneamente dopo averlo rivelato? Se invece ritieni che 3 secondi sia troppo poco, si può alzare. Ma vorrei prima capire bene il problema.

**Comment by Saro-UOMars** [comment]
si assolutamente, 3 secondi è troppo poco, lui continua a sparire curarsi e poi attaccare di nuovo apparendo dal nulla, tu perdi il target ed il tempo, se calcoli che in media per sferrare un colpo ci vogliono 3/4 secondi è impossibile se sei da solo. Se io ci spendo 200 di punti skill come lui, deve essere efficace il mio Detect, se dici potresti aumentare a 5 secondi e inoltre fare in modo che il cooldown della skill hiding non parta dopo averla usata ma dopo essere usciti dall'hide, inoltre sarebbe giusto che se uno sthealther ti viene "addosso" quindi si trova sul tuo stesso tile venga rivelato anche se ho 0 di detect e trak... non puoi "inciampare" su di me e io non vederti per niente...

**Comment by daffy55** [comment]
> è incounterabile, anche con detect e traking a 100 non serve proprio a nulla, il player si hidda di nuovo subito dopo e il tuo cooldown dura una vita... cosi non si può giocare... è inutile pure giocare sembra una presa per il culo

ahahahahahahahahahahahahahahahahaahahahahahahaa
aahahahahahahaha
aahahhaahaha
hahahaahahahahahaha
ahahahahahaa
ahahahaha

**Comment by dumbo85** [comment]
ieri i non fazionati mi hanno chiamato durante una live, parlavano di questo, due hiddati avanti la sede che li aspettavano e l unica soluzione che avevano era quella di andarsi a macrare due skill... per ora sono stati aiutati da uno young che si e cambiato momentaneamente le skill e li ha rivelati. la loro domanda principale era una
come mai sullo shard sono le uniche due skill che come risposta hanno una sola via? 
il poison si risolve con benda pozza magia per esempio
se non ho respell cmq posso uccidere il mio rivale, posso curarmi dagli incenti danni e farmi aiutare nella cura, ho le pozze, le armature. certo sono in svantaggio ma ora per gli stalth è come se chi non ha respell non possa targhettare un mago...
potrebbe essere una soluzione creare un armatura che rivela chi è hiddato? una spell? un arma? una risposta alla skill come per il resto delle cose?
non so, sono proposte, io non ho mai giocato lo stelter, lo provero oggi in giornata
a mio avviso, dopo una breve chiacchierata con legil e dopo una discussione con chi reclamava, forse in molti non conoscono bene le debolezze dei ladri, ma forse le soluzioni sono anche poche.. se domani tutti facessero un ladro, tutti dovrebbero avere detech e stealt, un bardo a cosa rinuncerà? oppure si fara rubare uccidere a loop?

**Comment by daffy55** [comment]
il mio worker ha detect e tracking

**Comment by dumbo85** [comment]
> il mio worker ha detect e tracking

il tuo mago? il tuo war? 
bardo
musicanship
pacemaking
provocation
discordance
deteck 
tracking
o cosi oppure rubato gli stealth sono gm
il mago?
magery
respell
meditation
ritualism
healing 
iscription
eva int
wrestling
tracking 
detect
a cosa daresti priorità per riuscire a fraggare oltre a non farti trollare, uccidere, rubare senza che tu abbia armi?
o sia chiaro, io non sono ne pro e ne contro lo stealth ma bisogna fare il bene dello shard..
e ancora non ricevo risposta sul "quale altra skill ha come risposta solo un altra skill?"

**Comment by kentar91** [comment]
a prescindere dalle skill, che comunque è una considerazione sensata, mi sembra strano che uno stealther quando beve una pozione stamina non esce dall'hiding, anche perchè la STAMA è la base del camminare hiddato.

**Comment by daffy55** [comment]
> > il mio worker ha detect e tracking
> 
> il tuo mago? il tuo war? bardo musicanship pacemaking provocation discordance deteck tracking o cosi oppure rubato gli stealth sono gm il mago? magery respell meditation ritualism healing iscription eva int wrestling tracking detect a cosa daresti priorità per riuscire a fraggare oltre a non farti trollare, uccidere, rubare senza che tu abbia armi? o sia chiaro, io non sono ne pro e ne contro lo stealth ma bisogna fare il bene dello shard.. e ancora non ricevo risposta sul "quale altra skill ha come risposta solo un altra skill?"

usi le pozze pagane ed eviti di mettere una skill

**Comment by Saro-UOMars** [comment]
però legil la pozza pagana la stanno mettendo solo adesso da quanto ho capito, modifica di oggi.

**Comment by dumbo85** [comment]
![image](https://user-images.githubusercontent.com/58265907/150688437-af33894c-3501-4a23-9ab4-eb560b2f2fb6.png)
![image](https://user-images.githubusercontent.com/58265907/150688469-079a8303-9424-4a2a-a8fa-06ecf2feb607.png)

**Comment by dumbo85** [comment]
un pg, ha appena fatto da pk alle lost correndo con il pg passando in mezzo senza uscire praticamente mai. bho, da stelether a gm

**Comment by GiovGiorgio** [comment]
una considerazione veloce. Il martello in obsidian può arrivare a togliere 69 da appiedato e con il bless di strenght. 2 macer ti tolgono 138, ovvero un'instantkill (con l'armatura nera diventano 124, anche qui instant kill nel 99% dei casi). Se volessimo proprio parlare di incounterabile, stiamo parlando di questo. Non ci sono tempi di reazione che tengano. Fossi in voi valuterei la possibilità di introdurre una sorta di delay tra il momento dell'uscita dallo stealth e l'attacco vero e proprio, così come prolungare il tempo necessario per tornare in stealth dopo un attacco. Per il resto ci sono anche le trappole che rivelano. Basta posizionarle in posti strategici e già è un problema in meno. A tal proposito, la reveal trap potrebbe avere un range di 2 tile, ed avere effetto persistente per N secondi (proprio per evitare che in un gruppo di stealth killer ne venga mandato avanti 1 a far scattare le trappole, tanto gli altri restano comunque efficaci)

**Comment by Saro-UOMars** [comment]
si anche quel discorso li è da vedere, non puoi attaccare e hiddarti subito dopo, e sicuramente il delay per attaccare ci sta. Infine le trappone al momento sono inutilizzabili, non se se hanno fixato ma sono buggate.

**Comment by morpheus8888** [comment]
hiding e stealthing verranno reworkate a breve in modo totalmente differente da come sono oggi
