### ISSUE TITLE
Lockare oggetti a casa

### ISSUE THREAD

**Issue by SampinoInfernal** [uomars/UOMars#860]
vorrei lockare un runebook in casa, ma se lo locko non me lo fa usare.. voluto?

**Comment by Saro-UOMars** [comment]
si, avevo già chiesto io, per una serie di casi di abusi hanno deciso di disattivare questa cosa, magari con la calma si potrebbe riabilitare ed evitare gli abusi... cosi mi avevano detto.

**Comment by morpheus8888** [comment]
per il momento rimane così, lo mettiamo in una futura grande patch
