### ISSUE TITLE
Sirene Pryma

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#865]
le sirene devono suonare non appena parte un attacco ai cancelli altrimenti sono inutili, non appena suonano hai ancora 20 secondi prima che vada giù e anche se ripari non serve.

@morpheus8888 @gmocciaro

**Comment by gmocciaro** [comment]
le logiche sono tarate in modo preciso, non sono messe a caso, se sono da rivalutare parlane con guido

**Comment by gmocciaro** [comment]
ps: il sistema fa in modo che se uno ripara e uno attacca, quello che ripara vince

**Comment by Saro-UOMars** [comment]
> le logiche sono tarate in modo preciso, non sono messe a caso, se sono da rivalutare parlane con guido

l'ho scritto su GIT apposta

**Comment by Saro-UOMars** [comment]
> ps: il sistema fa in modo che se uno ripara e uno attacca, quello che ripara vince

questo è ottimo, ovvio se sono in 2 a colpire ti attacchi giustamente...

**Comment by morpheus8888** [comment]
le sirene partono al 70% della vita dei cancelli, con il .city ti puoi recallare sulla porta in 5 secondi cliccando direttamente sul cancello, abbiamo fatto diversi test, se un worker vuole ce la fa sempre appena parte la sirena. Come diceva Guglielmo, la riparazione vince sempre sull'attacco.

**Comment by Saro-UOMars** [comment]
mmm dici al 70% della vita e non al 70% di danno? allora la velocità di decadimento è molto più veloce di quella che pensavo, io mi sono recallato immediatamente quando è suonata in 6 secondi eri li davanti ed eravamo già al 10% mi sono messo a riparare ma siccome erano in 2 ho guadagnato solo qualche secondo... forse il problema non è la sirena ma il cancello che è troppo squishy
