### ISSUE TITLE
dilemma bonus Immortale alle lostlands

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#871]
Parlando con guido é uscito sto problema

Se uno va alle lostlands da immortale é ovviamente scoperto dalla protezione finché riattraversa il gate.
Non avendo il bonus rischio peró non ha alcuna motivazione per rimanere a craftare lí

perché non lasciare comunque una parte del bonus per questo tipo di situazione?

**Comment by daffy55** [comment]
troppo facile, se uno vuole essere immortale e' giusto che si porti dietro tutti i malus

**Comment by thepatriot87** [comment]
ma cosí tenterá di scappare sempre, se conserva tipo il 33% del bonus (se il bonus é 45 ottiene 15% )é sempre avvantaggiato nel togliersi la I peró qualcuno potrebbe rischiare creando gioco per pk

**Comment by GiovGiorgio** [comment]
Personale opinione, da player. Io sarei per rimuovere la possibilità di entrare da immortale nelle lost, in modo da risolvere il problema alla radice.

**Comment by morpheus8888** [comment]
@gmocciaro attualmente avere la I, influenza il bonus alle lost lands?

**Comment by thepatriot87** [comment]
@morpheus8888 oggi ho fatto dei test perché uno ha fatto page, se non  ho sbagliato qualcosa  hai 0 bonus se hai la I 
![immagine](https://user-images.githubusercontent.com/17385984/151038622-6d8c3508-0ff1-4b3e-9bd9-33b2da420252.png)

**Comment by daffy55** [comment]
> @morpheus8888 oggi ho fatto dei test perché uno ha fatto page, se non ho sbagliato qualcosa hai 0 bonus se hai la I ![immagine](https://user-images.githubusercontent.com/17385984/151038622-6d8c3508-0ff1-4b3e-9bd9-33b2da420252.png)

ma non si vede nulla dallo screen, e' un bonus rischio, se non si vede chi c'e' online non ha senso

**Comment by thepatriot87** [comment]
giá l'ho detto a legil cmq per chiarire c'erano pk

**Comment by morpheus8888** [comment]
fatto
