### ISSUE TITLE
x hurricane

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#872]
controllare fencing se a 100
pg akasha account viseriOn 
save sicuro 22/01 alle 20
@Ale1991

**Comment by morpheus8888** [comment]
riflettendoci meglio, per me per una cosa del genere, invece che perdere tempo diamogli direttamente la skill, tanto siamo in beta, ovviamente 1,2 massimo richieste per player se ne fanno di più ignoriamo direttamente perché vuol dire che è ritardato o in malafede

**Comment by thepatriot87** [comment]
gliel'ho messi dopo aver chiesto ad alessio peró voleva controllare se c'é stato qualche bug
