### ISSUE TITLE
aumentare gli slot lockabili in casa

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#874]
fare un oggetto comprabile con rewards token che aumenta gli slot per gli oggetti lockabili in casa. 
Ogni token ti da un biglietto che se consumato aumenta di 10 slot. Ovviamente se uno lascia la casa perde tutto, anche questi bonus.

**Comment by gmocciaro** [comment]
non gli bastano 50?

**Comment by morpheus8888** [comment]
no, abbiamo avuto richieste di aumento

**Comment by gmocciaro** [comment]
oppure raddoppi un singolo chest e te lo fa selezionare (passi da 8k a 16k) ovviamente se lo levi o perdi la casa hai perso il bonus

**Comment by KiraRockHead** [comment]
Sarebbe carino avere dei secure capienti per un tot. e poi se proprio dovete metterli a pagamento più capienti...Anche se mi sembra un po' too much, per quanto vi butto soldi anche a random. Ma una comodità simile sarebbe carino che ne abbia accesso anche gente che non paghi imho. Se mi dite che avere chest da 20k di peso per il server è un problema okey, ma purtroppo reagenti, ecc pesano un bel po', non potendo alleggerire quelli altrimenti chi li farma ne farma 20000000 a botta, direi di aumentare il peso al doppio dei secure, e al massimo con GP in game.

**Comment by morpheus8888** [comment]
per i chest non possiamo fare un aumento fisso con  i rewards, l'aumento deve sempre entrare nel rinnovo mensile, però si, invece di far piazzare un chest in più possiamo fare che pagano tot al mese in più per l'aumento
