### ISSUE TITLE
Fauna Scomparsa Tempistiche

### ISSUE THREAD

**Issue by FeverSeven** [uomars/UOMars#875]
Volevo sapere a che punto erano i lavori riguardo l'estinzione di massa di tutti gli animaletti xD torneremo a vedere conigli e pecorelle?

**Comment by Darksuitjer** [comment]
basta guardare le conigliette di playboy a pecora... ti fa male!

**Comment by daffy55** [comment]
povero Kentar, che c'entra? xD
