### ISSUE TITLE
despawn depositi

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#876]
@kentar91  ci stanno dei depositi che spawnano in posti irraggiungibili ma senza despawn( o duration non ricordo) si "accumulano" 
tipo 
![immagine](https://user-images.githubusercontent.com/17385984/151033851-80dede2e-5f06-4d82-8a41-30c3c1815d5a.png)

qual'era l'impostazione per farli despawnare despawn o duration?

**Comment by kentar91** [comment]
fatto qualche giorno fa
