### ISSUE TITLE
gate tutorial archery

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#877]
![immagine](https://user-images.githubusercontent.com/17385984/151036650-074836bf-b55c-4c5c-8ea4-d92e73c3eaf9.png)

gui il punto 6 é incompleto, o scrivi di sparare sempre da appiedato o devi scrive di DIREZIONARSI verso il maiale e fare .scocca quando la shooting bar é verso la fine

@morpheus8888

**Comment by morpheus8888** [comment]
fatto
