### ISSUE TITLE
bug craft del keg

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#893]
se cerchi di craftare un keg ma non hai tutti i reagenti in borsa, ma i reagenti sono nel packhorse, la roba che è nella borsa si deleta. Credo che generalmente se ci sta un po' di qua e un po' di la bugga.

**Comment by Giboud** [comment]
Il bug non riguarda solo il keg anche a tutti gli oggetti crftabili con i materiali divisi tra pack horse e borsa... Esempio le Dragon plate se le shaft sono nel packhorse e i lingotti nella borsa spariscono i lingotti...

**Comment by gmocciaro** [comment]
ma l'item lo crafta o ti dice che non hai abbastanza materiali e ti cancella una parte degli item richiesti?

**Comment by gmocciaro** [comment]
todo personale:

spostare la logica del consumo dei materiali dopo il craft, non prima

**Comment by Giboud** [comment]
> ma l'item lo crafta o ti dice che non hai abbastanza materiali e ti cancella una parte degli item richiesti?

Non crafta l'item e cancella i Mats nel backpack
