### ISSUE TITLE
Secure giallo rilascio casa

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#894]
Guglie' aiutaci, perche' quando la gentem cambia casa e capita piu' di quanto credi, passargli tutti gli item a mano e' un parto

Non so quale puo' essere la soluzione ma magari fa si che i secure dentro li possa aprire anche lui, perche' diventiamo scemi ..... ci sono case da 30/40 secure e la gente ti assicuro che non sa cosa sia l'ordine

**Comment by gmocciaro** [comment]
... appena ci becchiamo su discord ricordamelo che ti faccio vedere che sei un pirla
