### ISSUE TITLE
Invulnerabile alle Lost

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#909]
se si entra da INV alle lost si hanno le stessi limitazioni di Felucca (non usi pozze, non raccogli, non prendi bonus craft) considerando che alle lost l'INV non è attivo la cosa di mantenere i malus è voluta o una svista? @morpheus8888

**Comment by morpheus8888** [comment]
al momento è voluto, ma si può sempre cambiare, nel caso apri una discussione anche per quello che stasera mi leggo tutto

**Comment by Saro-UOMars** [comment]
ok, no beh non è un vero problema al momento perché puoi sempre togliere INV mentre sei alle Lost quindi è solo una "scomodità"...
