### ISSUE TITLE
il condition teleporter deve avere un'opzione nuova

### ISSUE THREAD

**Issue by morpheus8888** [uomars/UOMars#918]
di bloccare solo i worker invulnerabili sotto attacco

**Comment by morpheus8888** [comment]
fatto @kentar91 sistema i gate delle lostlands, mettigli la nuova opzione denyworkerinvulnerableUA @kentar91

**Comment by kentar91** [comment]
Guido ho messo questo flag

visto che esiste ora questa condizione, pensavo di togliere il combat check dalle lost a fuori, perchè altrimenti i lavoratori non hanno nessun modo per scappare...
fammi sapere
