### ISSUE TITLE
Cast che non si vedono

### ISSUE THREAD

**Issue by KiraRockHead** [uomars/UOMars#920]
In game ci sono i furbi che usano colori per i cast che non si leggono, c'è un modo da client per vedere a prescindere da come li settino gli altri, un colore visibile? Ty

**Comment by GiovGiorgio** [comment]
![image](https://user-images.githubusercontent.com/97342267/151659058-3feb2179-ce75-4af4-b386-968f19f0cee4.png)
Con spell format spunta il nome della spell accanto alle parole magiche es"Kal Vas Flam (Flmaestrike)"
Con spell hue puoi decidere quale colore personalizzato dare ai cast, dividendolo tra benefici, offensivi e neutrali

**Comment by KiraRockHead** [comment]
Ottimo, ma worka anche con gli altri? Perchè i mie li vedi così gli altri no

**Comment by GiovGiorgio** [comment]
in teoria sì
 su fonts prova a togliere la spunta override game font

**Comment by morpheus8888** [comment]
@giga487 possiamo impedire che la gente cambi colore al cast?

**Comment by giga487** [comment]
Indago e cerco di capire meglio il problema

**Comment by GiovGiorgio** [comment]
Le modifiche nella pagina che ho messo influenzano solo quello che si vede nel client, per cambiare il colore del cast, se le opzioni nello screen sono disabilitate, basta cambiare il colore dello speech

**Comment by giga487** [comment]
> Le modifiche nella pagina che ho messo influenzano solo quello che ognuno vede nella propria finestra di gioco, per cambiare il colore del cast, se le opzioni nello screen sono disabilitate, basta cambiare il colore dello speech

Come al solito ha ragione Giovanni giorgio.

Chiudo, bastava leggere.
