### ISSUE TITLE
Le mappe sono troppo difficili da fare

### ISSUE THREAD

**Issue by GiovGiorgio** [uomars/UOMars#921]
Le mappe sono molto difficili da fare, considerato che sono necessarie. Sono l'unico modo per ottenere le recall scroll e le pen of wisdom

**Comment by morpheus8888** [comment]
ora che sono più libero posso nerfarle un po', quale pensi sia troppo difficile?

**Comment by GiovGiorgio** [comment]
ho provato una livello 2, col tank. I mostri normali sono facili, il guardiano (un orco macer/mage) è qualcosa di estremamente potente. Mi toglieva 30 hp sullo scudo, ogni 2 secondi. In più aveva l'AI che cercava di colpirti alle spalle, e nel mentre aveva la rotazione di in nox,  3 lightning e cor por. L'unico modo per buttarlo giù è stato a cavallo, davo e ricevevo un colpo, scappavo e mi bendavo, e ripetevo. Da fermo, a meno di avere 2 maghi a curare, non credo si regga. In più con il fatto che si recallano, anche col bardo immagino diventi complicato farle, dato che avvicinandoti rischi la combo rel por, colpo, fulmine.

Invece qualche giorno fa avevo provato ad aprire una liv 6, i mostri avevano 235 eva int, tiravano fulmini da una 60ina di hp

**Comment by morpheus8888** [comment]
a furia di potenziarle sono diventate troppo forti XD abbasso la difficoltá dei boss delle mappe dal livello 1 a 3,

**Comment by morpheus8888** [comment]
sono state depotenziate
