### ISSUE TITLE
Guild Title

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#923]
dopo aver settato il title di gilda lo attivo da pannello della gilda "show guild title" se però sloggo e riloggo  toglie il flag a "show guild title" @morpheus8888 @gmocciaro @Ale1991

**Comment by gmocciaro** [comment]
non mi pare o comunque non riesco a replicare il problema, qualche info in più?

**Comment by daffy55** [comment]
Quando clicchi su "guild" nel paperdoll ha 2 voci 
Show Guild Tag
Show guild title (questa compare SOLO se hai un titolo sul personaggio)

Al logout lo show guild tag rimane, mentre show guild title si resetta

È un po che volevo segnalartelo ma mi scordavo sempre

**Comment by gmocciaro** [comment]
a me funziona

**Comment by gmocciaro** [comment]
provato sia con l'owner della gilda, sia con un gidlato, a riavviare il server a chiudere il client e a fare logout e mi rimane il titolo

**Comment by daffy55** [comment]
Eh a tutto il resto del server no :(

**Comment by gmocciaro** [comment]
poi lo proviamo assieme

**Comment by daffy55** [comment]
se slogghi e rilogghi rimane, se slogghi, aspetti 30 minuti e rilogghi la toglie

**Comment by gmocciaro** [comment]
nel codice non trovo nulla che interviene su quella variabile, sta cosa non mi torna
