### ISSUE TITLE
Contattare un Amministratore

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#925]
gli e' uscito durante il frag a Giovanni Giorgio
![image](https://user-images.githubusercontent.com/83860614/151678955-096b204f-aba6-4ac0-aae9-3fd00823d242.png)

**Comment by GiovGiorgio** [comment]
è uscito mentre un compagno di gilda provava a castarmi arch protection. il primo cast non è andato a buon fine, il secondo è entrato

**Comment by daffy55** [comment]
Si il primo cast lo possono fare solo gli admin che fraggano :look:

**Comment by Ale1991** [comment]
fixed
