### ISSUE TITLE
Dungeon Wrong

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#926]
non e' neanche casa sua
![image](https://user-images.githubusercontent.com/83860614/151679079-c7ec1b37-75b1-4d2e-b59e-5939af162df5.png)

**Comment by giga487** [comment]
Lo so. 
Posso diminuire il raggio di random.

Purtroppo mi avete messo i teleport in un posto sbagliato, perché così defilati e fuori centraggio della mappa, non vanno minimamente a mettere a rischio i player.

Il gioco è centrale nella mappa e i teleport sono di fatto sempre safe, quindi perché mai pagare e fare l altro teleport? Peccato perché ci ho perso del tempo.

Ormai è così, possiamo riflettere sullo spostarli? Io rifletterei sul perché fare le modifiche senza riflettere o magari senza parlarne con tutti.

La fretta è una brutta consigliera.

**Comment by daffy55** [comment]
Non capisco cosa centri la watchtower con wrong, la quale è stata spostata ragionandoci tutti insieme, visto che è l'unico Teleport dove si ci può recallare con la roba recentemente Craftata
È un punto di arrivo per worker che tornano dalle lost land o che raccolgono in giro per la mappa

**Comment by giga487** [comment]
È anche un punto di uscita per i dungeon

**Comment by daffy55** [comment]
Usa le vecchie coordinate
