### ISSUE TITLE
Trappole ladro non per rossi 

### ISSUE THREAD

**Issue by KiraRockHead** [uomars/UOMars#930]
È voluto? Non posso usare nessuna trappola da rosso, perché mi dice che devo essere in criminale.. Nessuna delle trappole è usabile da rosso ladro

**Comment by morpheus8888** [comment]
si è voluto perché altrimenti tutti i pk, anche non ladri finirebbero per cadere nelle trappole. Non penso che in pvp vogliate questo genere di situazione. Poi se volete ve lo metto, nel caso riapri il git.
