### ISSUE TITLE
LostLand Bonus Craft

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#934]
alle lostland con bonus +50 e senza invulnerabile, la ricetta della medium boat non giova della riduzione dei materiali, infatti sono la stessa quantità di quelli usati in città

@morpheus8888 @gmocciaro

**Comment by morpheus8888** [comment]
strano, deve essere un bug

**Comment by gmocciaro** [comment]
dimmi i valori di skill che avevi e talismano

**Comment by gmocciaro** [comment]
![image](https://user-images.githubusercontent.com/12816659/151716692-bf4ec470-5e1f-46f2-8203-dc1c0f4b0f38.png)
![image](https://user-images.githubusercontent.com/12816659/151716739-652c485a-0fe1-4f96-bb3c-42d71d44fdde.png)

9 board di base  + (9 * (5 taslimano + 2 skill) = 72

sta funzionando tutto

**Comment by gmocciaro** [comment]
![image](https://user-images.githubusercontent.com/12816659/151716841-bdf51dd0-780e-4cf3-98cf-9b09124f31db.png)

300 board di base + (300 * (5+2)) = 2400

**Comment by Saro-UOMars** [comment]
penso di aver guardato con un pg senza skill carpentry e il totale era uguale, con il pg carpenter invece c'è lo sconto
