### ISSUE TITLE
Craft Shaft/Staves/Iron Wires

### ISSUE THREAD

**Issue by Saro-UOMars** [uomars/UOMars#938]
hanno segnalato che le shaft e le staves si possono craftare anche con legno speciale, quando invece le iron wires si possono fare solo con iron base
@morpheus8888 @gmocciaro

**Comment by gmocciaro** [comment]
si chiamano "iron" wires, immagino sera l'iron?

**Comment by morpheus8888** [comment]
saro si riferisce al problema che non c'è coerenza di craft, quindi o togliamo alle staves che si craftano con legno spegnale o lo mettiamo all'iron wires che si fanno con metalli speciali.

**Comment by gmocciaro** [comment]
pensaci e fammi sapere

**Comment by morpheus8888** [comment]
togli gli speciali a staves e shaft

**Comment by gmocciaro** [comment]
fatto
