### ISSUE TITLE
[Server ] Splittare le skills lavorative e non-lavorative

### ISSUE THREAD

**Issue by andreadellacorte** [uomars/UOMars#94]
Alcune skill lavorative, come Lumberjacking o Mining, hanno una doppia vita.

Quando utilizzate da un lavoratore, permettono di farmare materiali.

Quando utilizzate da un non-worker, aggiungono particolari effetti al danno (e.g., mining distrugge armature).

Detto cio', essendo worker e non-worker categorie esclusive, le due abilita' di cui sopra non hanno nessuna relazione l'una con l'altra, generando confusione.

Il suggerimento qui e' evitare questa doppia vita delle skill - una skill e' fermamente worker o non-worker. Effetti non-worker (come quello di mining di cui sopra) dovrebbero essere spostati su una skill separata.

**Comment by gmocciaro** [comment]
Abbiamo tolo Mining e Lumberjacking al non.worker, reworkando gli effetti e cambiando le skill per la parte PVP, rispettivamente:

- Mining -> Fading (frozza)
- Lumberjacking -> Weakening (cursa)
