### ISSUE TITLE
rework auc

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#943]
siccome tutti si lamentano dell'auc tra tasse, min start, min bet, rilanci, farei la seguenti cose:

- [x]  levare la tassa fissa (attualmente 500gp dall'npc e 1k dal .auc)
  - [x] TESTARE
- [x] impostare 2 tasse variabili che sarebbero:

#### dall'NPC
**2%** sul valore di asta iniziale + **1%** sul valore di fine asta

quindi se ad esempio metto un pet a 20k e l'asta finisce a 50k, il proprietario paga in tasse: 
dall'NPC: (20000 x 0.02=400 + 50000 x 0.01 = 500): **900 gp**

- [x] TESTARE

#### dal comando `.auc`
**4%** sul valore di asta iniziale + **2%** sul valore di asta finale

quindi se ad esempio metto un pet a 20k e l'asta finisce a 50k, il proprietario paga in tasse: 
dal .auc: (20000 x 0.04=800 + 50000 x 0.02 = 1000) **1800 gp**

- [x] TESTARE

- [x] ogni rilancio allunga l'asta di 12 ore (attualmente non si allunga al rilancio)
  - [x] TESTARE
- [x] la base minima di partenza dell'asta è 2k (ora è a 10 gp)
  - [x] TESTARE
- [x] il massimo per la partenza dell'asta è 200k (ora è 10k)
  - [x] TESTARE
- [x] i minimi rilanci sono di 200gp (ora è a 100 gp)
  - [x] TESTARE
- [x] L'instant win deve essere minimo il 200% della base d'asta (quindi se base è 20k, l'IW minimo è 40k)
  - [x] TESTARE

**Comment by Ket4mina** [comment]
Pienamente d'accordo. Allungherei però di più il periodo dopo il rilancio per evitare rilanci notturni a cui è difficile rispondere in tempo

**Comment by gmocciaro** [comment]
poi si allunga di troppo il tempo, non deve durare 2 mesi un asta

**Comment by gmocciaro** [comment]
ovviamente per fare ciò bloccherò le aste, faccio finire tutte quelle attuali in corso e poi le riattivo, altrimenti poi la gente paga alla fine per gli items messi all'asta senza la sua volontà

**Comment by morpheus8888** [comment]
concordo con ketamina, se uno vuole vendere subito va di .vs mentre all'asta cerca di massimizzare, quindi più dura meglio è per chi vende

**Comment by gmocciaro** [comment]
allora, proposta:
la durata aumenta in base a quanto rilanci, quindi:

min raise: 1h
doppio del min raise: 2h
triplo del min raise: 3h

e così via fino ad un massimo di 8 ore (quindi anche 100 volte minraise sono 8h di dalay)

**Comment by gmocciaro** [comment]
la logica è: se voglio fare minraise quasi a rompere le palle allora aumenta solo di 1 ora, se sono interessato e voglio che domani mattina non mi inculano, alzo di 8 volte il min raise (il min raise è 200 quindi significa 1.6k o superiore)

**Comment by Ket4mina** [comment]
In realtà con questa logica conviene aspettare tra le 2:00 e le 5:00 di mattina, quando online ci sono pochissimi player, per fare un'offerta al minimo e portarsi via l'oggetto. Secondo me il rilancio dovrebbe ritardare la chiusura di almeno 12h così da dare tempo a chi la sta seguendo di rilanciare.

**Comment by gmocciaro** [comment]
vabhe facciamo che ogni rilancio allunga l'asta di 12h e bona, non ho voglia di pensare alternative assurde

**Comment by giga487** [comment]
Cose semplici e bona.
