### ISSUE TITLE
Deletare item dal vendor

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#947]
No sense, toglilo pure

**Comment by gmocciaro** [comment]
quindi se mette in vendita un item resterà li a vita e pagherà le tasse a vita?

**Comment by Saro-UOMars** [comment]
un player può anche decidere di non vendere più un oggetto o lo vuole vendere direttamente ad un pg "amico"

**Comment by daffy55** [comment]
In quel caso lo ritira

**Comment by gmocciaro** [comment]
ma se decide di rimuoverlo è libero di farlo, deve solo pagare una piccola tassa (non ricordo quanto)

**Comment by daffy55** [comment]
eh, si
il problema infatti e' il delete, non capisco cosa intende Saro

**Comment by gmocciaro** [comment]
> quindi se mette in vendita un item resterà li a vita e pagherà le tasse a vita?

*

**Comment by daffy55** [comment]
Allora cambiamo il messaggio, 
Deletare un item dallo shop non è abbastanza chiaro

**Comment by gmocciaro** [comment]
posso mettere un warning gump che dice che verrà perso per sempre

**Comment by daffy55** [comment]
perfetto
