### ISSUE TITLE
throwing non consuma le pozze heal

### ISSUE THREAD

**Issue by GiovGiorgio** [uomars/UOMars#949]
come da titolo, avrò lanciato una ventina di pozze GH su un alleato, le pozze erano e rimangono 6

**Comment by daffy55** [comment]
si possono lanciare anche su se stessi senza consumarle

**Comment by morpheus8888** [comment]
solo le gh, le altre si consumano?

**Comment by daffy55** [comment]
no nessuna pozza, se ti fischiano le orecchie e' Ale che te le sta mandando dietro

**Comment by morpheus8888** [comment]
ho fatto un regalo allo shard

**Comment by Ale1991** [comment]
fixato ieri, chiudo
