### ISSUE TITLE
pg banca

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#951]
![immagine](https://user-images.githubusercontent.com/17385984/152111668-5b193548-c533-4bc5-be4b-b8953f0c9ff5.png)
si lascia come sfogo per gli accumulatori seriali? 

@morpheus8888

**Comment by Darksuitjer** [comment]
non ho idea della linea che si voglia prendere, ma di base rinunceresti all'utilizzo di un pg

**Comment by morpheus8888** [comment]
si abbiamo deciso che lo consentiamo, tanto comunque devono prendere casa e sprecare un pg, oltre che essere frustrante
