### ISSUE TITLE
Slog lost land 

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#952]
Buonasera, 
Volevo sapere se fosse possibile eliminare questa dinamica, in quanto capita che chi ha un’emergenza deve sloggare immediatamente e non ha il tempo di tornare in città. 
a me capita spesso di dover sloggare è così per me significa non andare alle lost

**Comment by morpheus8888** [comment]
il problema di sloggare alle lost lands è che poi diventa troppo facile appostarsi ai vari respawn, specialmente quando poi metteremo anche quelli di terzo
