### ISSUE TITLE
Case esterne

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#956]
Player Neutrale in casa esterna PK, quando slogga viene buttato fuori casa e si ritrova alle porte di città Pk

**Comment by morpheus8888** [comment]
quando scriptate le case dovete anche scriptare che sono case esterne, c'è una variabile chiamata isincity, che va messo a false nel caso di casa esterna

**Comment by gmocciaro** [comment]
se mi dici quale casa esterna è lo metto che sarà saltato
