### ISSUE TITLE
bug nygmar

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#958]
![immagine](https://user-images.githubusercontent.com/17385984/152263976-3739c6aa-6586-4c28-91cd-76d4674d8f99.png)
attraversato il gate forse con un rel por

**Comment by morpheus8888** [comment]
non ho capito, puoi essere più specifico?

**Comment by thepatriot87** [comment]
in qualche modo ha passato il gate ed é arrivato in questa zona killando tutti

**Comment by morpheus8888** [comment]
forse ha castato un lamp attack mentre quelli scappavano nel gate e li ha inseguiti anche dall'altro lato

**Comment by thepatriot87** [comment]
![immagine](https://user-images.githubusercontent.com/17385984/153263592-88339395-caf4-46fd-9d65-7cf3bdd0d4f5.png)
successo ancora @morpheus8888

**Comment by morpheus8888** [comment]
sará il lamp attack

**Comment by thepatriot87** [comment]
non si puo far nulla?

**Comment by morpheus8888** [comment]
no, il lamp attack e'progettato per andare sempre a segno, se quelli scappano nel gate sono cazzi loro, si puo mettere la special ability recall home al mostro se deve tornare indietro, ma e' un boss?

**Comment by thepatriot87** [comment]
no sono quelli prima del prince a nygmar

**Comment by morpheus8888** [comment]
fai una prova, scrivi .specialabilities e aggiungici recallhome

**Comment by thepatriot87** [comment]
si torna
