### ISSUE TITLE
[Playtest] May, Alpha Playtest

### ISSUE THREAD

**Issue by andreadellacorte** [uomars/UOMars#96]
Una serie di cose da fare per organizzare un playtest di 6+ ore nel weekend nel mese di Maggio, tanto per iniziare una discussione.

# Pre-Approvals dei Boss

- [ ] @morpheus8888 
- [ ] @gmocciaro 
- [ ] @Ale1991 

# Work to be done (work in progress)

- [ ] Separare tickets in una milestone a se stante @morpheus8888  -> https://github.com/uomars/UOMars/milestone/5
- [ ] Finire i tickets @andreadellacorte -> https://github.com/uomars/UOMars/milestone/5
- [ ] Prepare una introduction for players @kentar91 
- [ ] Assicurarsi che i players non possano entrare sul server dopo il playtest (server a casa di Alessio?) @morpheus8888 
- [ ] Trovare 5+ players @kentar91 
- [ ] Decidere su chi sara' online dello staff @kentar91 
- [ ] Decidere su come raccogliere il feedback dei players @andreadellacorte 

# Go / No Go

- [ ] Server @morpheus8888 @gmocciaro 
- [ ] Patcher @Ale1991 
- [ ] Client @giga487 
- [ ] Spawner @kentar91
- [ ] Decorator @daffy55 
- [ ] Tester @andreadellacorte

**Comment by gmocciaro** [comment]
mi sa che non è stato fatto...
