### ISSUE TITLE
Trowing pozze e altro

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#961]
Pozze trowing

Pozza fire - non fa danno ne animazione 
Pozze paralyze- dovrebbe durare in base alle skill ma dura sempre 0,5 sec quindi inutile
Attenuament - dovrebbe dare 50 ress alle magia ma non da nessun bonus 

arch cure 
Non funziona sugli alleati dopo l’ultima patch

**Comment by morpheus8888** [comment]
la pozza fire sarebbe la conflagration?

**Comment by lyon1235** [comment]
Si

**Comment by Ale1991** [comment]
puoi mettere uno screen del .caps con il pg con cui hai visto queste cose? 
- La conflagration non faceva ne danno ne animazione a causa di un bug che faceva comparire le animazioni sul tile sotto terra (fixato)
- Il paralyze era 1 secondo e scalava con la resistenza al froze ovviamente, adesso l'ho aumentato a 3
- le attunement potion non danno alcuna resistenza...assorbono i prossimi 50 danni da qualsiasi fonte
 ti riporto lo screen del bible dove e' scritto: 
![image](https://user-images.githubusercontent.com/21221719/152690959-c98a43f8-4ae3-4046-8acc-4d2d3399c9df.png)
