### ISSUE TITLE
item con tempo di distruzione

### ISSUE THREAD

**Issue by kentar91** [uomars/UOMars#963]
mi servirebbe un oggetto con questa grafica 0x1872 con tempo settabile da props come robe of rite

**Comment by morpheus8888** [comment]
fatto si chiama beefcarcass

**Comment by kentar91** [comment]
con 1 ora di tempo mi dice che scade fra 0 secondi.

![image](https://user-images.githubusercontent.com/83588629/152851780-9993e00b-384e-4d65-8f8c-aa29c7891f4b.png)

**Comment by kentar91** [comment]
poi lo puoi chiamare "ITEMQUEST" ?

**Comment by kentar91** [comment]
fatto
