### ISSUE TITLE
smoke potion non fa evitare i cast

### ISSUE THREAD

**Issue by GiovGiorgio** [uomars/UOMars#964]
Salve, la smoke bomb ha uno strano comportamento con last target. Infatti le magie arrivano lo stesso, anche se si è hiddati

**Comment by morpheus8888** [comment]
la smokebomb ti hidda, come se fosse hiding, se ti arrivano le magie arrivano vuol dire che arrivano anche sugli hiddati normali.  Hai veriticato per caso?

**Comment by GiovGiorgio** [comment]
no, pensavo la stessa cosa, ma non ho verificato

**Comment by morpheus8888** [comment]
vedi se riesci a fare qualche test, poi appena ho un attimo indago anche io

**Comment by morpheus8888** [comment]
@GiovGiorgio  novità?

**Comment by GiovGiorgio** [comment]
no, non ho avuto modo di testare. eppure sto dando una scusa per flammarmi

**Comment by GiovGiorgio** [comment]
ho fatto le prove, con GMTime, ma non siamo riusciti a replicare il bug. Forse nella foga del frag mi sono confuso

**Comment by morpheus8888** [comment]
ok allora chiudo
