### ISSUE TITLE
Sonic bomb e smoke potion 

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#965]
Propongo di tornare alla vecchia dinamica.
Non trovo corretto che chi non ha trowing possa utilizzare queste pozze, che sono di prerogativa di un pg che usa dei punti nella skill trowing

**Comment by morpheus8888** [comment]
le stanno usando in molti adesso?

**Comment by lyon1235** [comment]
Eh si

**Comment by morpheus8888** [comment]
ma è divertente?

**Comment by lyon1235** [comment]
Assolutamente si però credo che per usarla debba essere necessario almeno 10 trowing come abbiamo fatto per le cure ecc

**Comment by lyon1235** [comment]
E ma con 10 puoi lanciarle basta togliere 10 punti

**Comment by morpheus8888** [comment]
la dinamica è tornata coerente per tutte le pozze pagane
