### ISSUE TITLE
disguise kit e testa

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#966]
la testa non viene consumata con l'uso

https://user-images.githubusercontent.com/17385984/152560012-5431bf25-3933-4cd5-92c1-164ef7d12309.mp4

**Comment by thepatriot87** [comment]
@morpheus8888

**Comment by morpheus8888** [comment]
al momento ho messo che hai il 50% di probabilità di cancellarla, se volete il 100% lo metto

**Comment by thepatriot87** [comment]
quanto dura l'effetto? poi non so perché a me che ero lavoratore mi uscivano 2 [W]

**Comment by morpheus8888** [comment]
2 [w] lol, eh non è facile da fixare, l'effetto dovrebbe durare un'ora o due, non ricordo

**Comment by thepatriot87** [comment]
@morpheus8888  aggiungere al gump delle teste di usare .resetbodyform

**Comment by morpheus8888** [comment]
fatto
