### ISSUE TITLE
attunement potion sono "lanciabili"su se stessi

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#967]
@morpheus8888

**Comment by Ale1991** [comment]
sicuro? ho appena provato e non va (cioe' fa cliccare su di te senza alcun messaggio di errore ma non ti applica l'effetto della pozza)

**Comment by thepatriot87** [comment]
https://user-images.githubusercontent.com/17385984/152649676-59df8ffc-777b-425b-a7e6-203da09c7488.mp4

si forse non avevi healing e ritualism

**Comment by Ale1991** [comment]
io con tutte le skill a 100 non riesco a farlo, forse era un bug che non e' piu presente. Puoi riprovare pier?

**Comment by thepatriot87** [comment]
@Ale1991 ok riprovato e non lo fa piú
