### ISSUE TITLE
strano bug watchtower portal opener

### ISSUE THREAD

**Issue by GiovGiorgio** [uomars/UOMars#970]
una volta utilizzato il watchtower portal opener, è possibile continuare ad utilizzare lo stesso, anche mentre si è frozzati, non sembra un bug particolarmente grave (anche se non escludo la possibilità si possa sfruttarlo per farne usi infiniti, magari traddandolo o mettendolo in un packhorse), l'unico effetto è lasciare una scia di gate, una volta sfrozzato, l'item si deleta come di prassi

**Comment by morpheus8888** [comment]
top, fixo
