### ISSUE TITLE
veleno incurabile da mostri

### ISSUE THREAD

**Issue by GiovGiorgio** [uomars/UOMars#971]
alcuni mostri, ad esempio il desert scorpion fuori pryma, hanno più di 100 poisoning, ciò rende impossibile curarsi dal veleno con la pozione, si traduce quindi in un veleno perenne, molto dannoso
![image](https://user-images.githubusercontent.com/97342267/152655224-c64c8e85-4407-4c93-8f47-f0e3bc34c8d2.png)

**Comment by giga487** [comment]
é un bug, anzi è colpa degli spawner, dovremmo aver fixato, vanno solo respawnati tutti
