### ISSUE TITLE
bug outbidding .auc

### ISSUE THREAD

**Issue by GiovGiorgio** [uomars/UOMars#976]
è possibile fare outbid con la stessa puntata già presente. nell'immagine si vede che ci sono 3 puntate a 15k (la base d'asta), delle quali la prima e l'ultima sono mie.
in più il gump da come minima puntata disponibile sempre 15k
![image](https://user-images.githubusercontent.com/97342267/152686882-04b10720-4ba3-44e7-8334-78ec7dc3e89c.png)

**Comment by gmocciaro** [comment]
già risolto 10 min dopo aver creato il bug 🤣
