### ISSUE TITLE
veleno ophidian non curabile con le cure potion

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#981]
ma curabile con an nox
@kentar91

**Comment by thepatriot87** [comment]
![immagine](https://user-images.githubusercontent.com/17385984/152899435-15d13afd-76de-4737-a0fe-ca68e7f6e04b.png)

**Comment by kentar91** [comment]
@morpheus8888

**Comment by Ale1991** [comment]
fixato
