### ISSUE TITLE
Escape Rope - non funzionante

### ISSUE THREAD

**Issue by Lollo336** [uomars/UOMars#987]
Salve, negli ultimi due giorni durante il pvm ho provato ad usare l'escape rope per tornare a casa (sia dalle lost che da felucca) ma mi scrive : you cannot use it right now!

Ho provato sia con il loot appena preso dalle lost, poi da felucca, e infine senza lot da felucca ma niente scrive sempre la stessa frase

Usata con un pg NON Worker

**Comment by morpheus8888** [comment]
eri sotto attacco?

**Comment by morpheus8888** [comment]
ho appena visto il codice era stato inserito un bug ora ho corretto, grazie per la segnalazione
