### ISSUE TITLE
problemi wrong

### ISSUE THREAD

**Issue by thepatriot87** [uomars/UOMars#988]
![immagine](https://user-images.githubusercontent.com/17385984/153086010-9e4abdaa-6214-4bf0-a29c-b3950d9f9be1.png)
@giga487

**Comment by giga487** [comment]
@kentar91 è giusto da taggare, io non sono lo spawner

**Comment by kentar91** [comment]
Sono stati diminuiti drasticamente i Bones... Ho aumentato di un po' il numero degli scheletri e ho aggiunto un altra chest


Comunque @giga487 ho sistemato lo spawn di quel mob nuovo e ho chiesto agli arredatori di sistemare il terreno che spuntava dalle montagne

**Comment by giga487** [comment]
Io invece ho inserito la porta particolare che si apre solo con un item nel backpack
