### ISSUE TITLE
Bendata 

### ISSUE THREAD

**Issue by lyon1235** [uomars/UOMars#996]
Buonasera a tutti
Gli stack della nuova bendata non risolvono il problema che quando ti bende hai 4 sec in cui non puoi fare nulla… continua ad essere più conveniente heal normale. 
per rendere più interessante quella dinamiche è possibile far si che la bendata sia di 2.5 sec e curi di 20/25 ??? Così inizia ad essere una valida alternativa

**Comment by GiovGiorgio** [comment]
Personalmente penso che la bendata in 4 secondi non sia male, considerando i tick. Il warrior soffre molto, un mago è sicuramente più performante nelle cure, ma dimezzare tempo di bendata e quantità di cure può essere decisamente controproducente, dato che aumenta il rischio di sovrascrivere la bendata
