### ISSUE TITLE
. rewards

### ISSUE THREAD

**Issue by daffy55** [uomars/UOMars#999]
Creare un npc come il .rewards così gli faccio la bancarella in ogni città
@gmocciaro

**Comment by daffy55** [comment]
@Ale1991 lo fai te?

**Comment by morpheus8888** [comment]
che deve fare? che lo doppioclicchi e ti apre il .rewards?

**Comment by SampinoInfernal** [comment]
> che deve fare? che lo doppioclicchi e ti apre il .rewards?

guido parlando con ale ( che mi ha dato l'ok) mi è venuto in mente di fare in ogni città i mercanti che doppio cliccando o scrivendo vendor buy ti apre il .rewards
legil ha gia fatto tutte le bancarelle vicino alle banche
e' un idea carina rende piu viva la città e il .rewards

**Comment by morpheus8888** [comment]
va bene, appena ho 5 minuti lo faccio

**Comment by SampinoInfernal** [comment]
> va bene, appena ho 5 minuti lo faccio

fammi sapere gui, gia l'arredamento è up

**Comment by kentar91** [comment]
fatto
